// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package billing_source_oci

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BillingSourceOciResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_type_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Account Type ID is the corresponding billing source account's type.\n26 - OCI Commercial\n27 - OCI Government\n28 - OCI Federal",
				MarkdownDescription: "The Account Type ID is the corresponding billing source account's type.\n26 - OCI Commercial\n27 - OCI Government\n28 - OCI Federal",
			},
			"billing_start_date": schema.StringAttribute{
				Required:            true,
				Description:         "Start date of billing source (YYYY-MM).",
				MarkdownDescription: "Start date of billing source (YYYY-MM).",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^\\d{4}-(?:0[1-9]|1[0-2])$"), ""),
				},
			},
			"fingerprint": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The api access fingerprint",
				MarkdownDescription: "The api access fingerprint",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the OCI billing source.",
				MarkdownDescription: "The ID of the OCI billing source.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"is_parent_tenancy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether the billing source is a parent OCI tenancy.",
				MarkdownDescription: "Indicates whether the billing source is a parent OCI tenancy.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the billing source.",
				MarkdownDescription: "Name of the billing source.",
			},
			"private_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "The private key used for API Access",
				MarkdownDescription: "The private key used for API Access",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The OCI default api region",
				MarkdownDescription: "The OCI default api region",
			},
			"skip_validation": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, will skip validating the connection to the billing source",
				MarkdownDescription: "When true, will skip validating the connection to the billing source",
			},
			"tenancy_ocid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The OCID of the tenancy",
				MarkdownDescription: "The OCID of the tenancy",
			},
			"use_focus_reports": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Use FOCUS Reports - If true, Kion will use FOCUS reports for this billing source",
				MarkdownDescription: "Use FOCUS Reports - If true, Kion will use FOCUS reports for this billing source",
			},
			"use_proprietary_reports": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Use Proprietary Reports - If true, Kion will use proprietary reports for this billing source",
				MarkdownDescription: "Use Proprietary Reports - If true, Kion will use proprietary reports for this billing source",
			},
			"user_ocid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The OCID of the api user",
				MarkdownDescription: "The OCID of the api user",
			},
		},
		Description: "Manages a Kion OCI Billing Source.",
	}
}

type BillingSourceOciModel struct {
	AccountTypeId         types.Int64  `tfsdk:"account_type_id"`
	BillingStartDate      types.String `tfsdk:"billing_start_date"`
	Fingerprint           types.String `tfsdk:"fingerprint"`
	Id                    types.String `tfsdk:"id"`
	IsParentTenancy       types.Bool   `tfsdk:"is_parent_tenancy"`
	Name                  types.String `tfsdk:"name"`
	PrivateKey            types.String `tfsdk:"private_key"`
	Region                types.String `tfsdk:"region"`
	SkipValidation        types.Bool   `tfsdk:"skip_validation"`
	TenancyOcid           types.String `tfsdk:"tenancy_ocid"`
	UseFocusReports       types.Bool   `tfsdk:"use_focus_reports"`
	UseProprietaryReports types.Bool   `tfsdk:"use_proprietary_reports"`
	UserOcid              types.String `tfsdk:"user_ocid"`
}
