package kimport

import (
	"fmt"
	"sort"
	"strings"
)

// RenderImports writes a Terraform configuration containing one import block per
// enumerated record.
//
// Import blocks, not a state file: `terraform plan -generate-config-out` turns
// these into configuration, and `terraform apply` writes the state through the
// provider's own Read and ImportState. That is why this tool serializes nothing
// itself -- the provider already does it, correctly.
func RenderImports(results []Result, providerVersion string) string {
	var b strings.Builder

	b.WriteString("# Generated by kion-import. Review before applying.\n")
	b.WriteString("#\n")
	b.WriteString("#   terraform init\n")
	b.WriteString("#   terraform plan -generate-config-out=generated.tf\n")
	b.WriteString("#   terraform apply\n\n")

	b.WriteString("terraform {\n  required_providers {\n    kion = {\n")
	b.WriteString("      source  = \"kionsoftware/kion\"\n")
	fmt.Fprintf(&b, "      version = %q\n", providerVersion)
	b.WriteString("    }\n  }\n}\n\n")

	sorted := append([]Result(nil), results...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].TFType < sorted[j].TFType })

	var labeler Labeler
	for _, res := range sorted {
		if len(res.Records) == 0 {
			continue
		}
		fmt.Fprintf(&b, "# %s (%d)\n", res.TFType, len(res.Records))
		for _, rec := range res.Records {
			label := labeler.Allocate(res.TFType, rec.Name, rec.ID)
			fmt.Fprintf(&b, "import {\n  to = %s.%s\n  id = %q\n}\n", res.TFType, label, rec.ID)
		}
		b.WriteString("\n")
	}

	var gaps []Result
	for _, res := range sorted {
		if res.Status == "unsupported" || res.Status == "error" {
			gaps = append(gaps, res)
		}
	}
	if len(gaps) > 0 {
		b.WriteString("# Not imported:\n")
		for _, res := range gaps {
			fmt.Fprintf(&b, "# %-45s %-12s %s\n", res.TFType, res.Status, res.Reason)
		}
	}

	// A successful read can still carry a real gap in Reason: records
	// skipped for having no usable id, association records skipped for a
	// missing key field, or a flat list that 405'd and fell back to a
	// parent-scoped read. Those results are status "ok" (or "empty"), so
	// they never land in the "Not imported:" block above -- but dropping
	// the fact silently would tell the customer nothing was skipped when
	// something was. Report them separately.
	var caveats []Result
	for _, res := range sorted {
		if res.Reason == "" {
			continue
		}
		if res.Status == "unsupported" || res.Status == "error" {
			continue // already reported above
		}
		caveats = append(caveats, res)
	}
	if len(caveats) > 0 {
		b.WriteString("# Read with caveats:\n")
		for _, res := range caveats {
			fmt.Fprintf(&b, "# %-45s %-12s %s\n", res.TFType, res.Status, res.Reason)
		}
	}

	return b.String()
}
