package kimport

import (
	"fmt"
	"sort"
	"strings"
)

// RenderImports writes a Terraform configuration containing one import block per
// enumerated record.
//
// Import blocks, not a state file: `terraform plan -generate-config-out` turns
// these into configuration, and `terraform apply` writes the state through the
// provider's own Read and ImportState. That is why this tool serializes nothing
// itself -- the provider already does it, correctly.
func RenderImports(results []Result, providerVersion string) string {
	var b strings.Builder

	b.WriteString("# Generated by kion-import. Review before applying.\n")
	b.WriteString("#\n")
	b.WriteString("#   terraform init\n")
	b.WriteString("#   terraform plan -generate-config-out=generated.tf\n")
	b.WriteString("#   terraform apply\n\n")

	b.WriteString("terraform {\n  required_providers {\n    kion = {\n")
	b.WriteString("      source  = \"kionsoftware/kion\"\n")
	fmt.Fprintf(&b, "      version = %q\n", providerVersion)
	b.WriteString("    }\n  }\n}\n\n")

	sorted := append([]Result(nil), results...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].TFType < sorted[j].TFType })

	// Labeler.Allocate keys identity on (tfType, id) and deliberately returns
	// the same label for two records that share an id (id is the documented
	// identity). Emitting one "import" block per record would then produce
	// two blocks with the same "to =" address; Terraform rejects the whole
	// file on a duplicate import address, so one such collision would destroy
	// every other block in the run. Dedup here implements the labeler's
	// stated intent instead of only half-applying it, and the dropped count
	// is surfaced below as a caveat rather than silently disappearing.
	var labeler Labeler
	emitted := map[string]bool{}  // tfType + "\x00" + id -> already rendered
	dupCounts := map[string]int{} // tfType -> duplicate records skipped
	for _, res := range sorted {
		if len(res.Records) == 0 {
			continue
		}
		var blocks strings.Builder
		for _, rec := range res.Records {
			key := res.TFType + "\x00" + rec.ID
			if emitted[key] {
				dupCounts[res.TFType]++
				continue
			}
			emitted[key] = true
			label := labeler.Allocate(res.TFType, rec.Name, rec.ID)
			fmt.Fprintf(&blocks, "import {\n  to = %s.%s\n  id = %q\n}\n", res.TFType, label, escapeHCLTemplate(rec.ID))
		}
		if blocks.Len() == 0 {
			continue // every record for this type was a duplicate
		}
		fmt.Fprintf(&b, "# %s (%d)\n", res.TFType, len(res.Records))
		b.WriteString(blocks.String())
		b.WriteString("\n")
	}

	// A render-time duplicate drop (above) is only knowable here, not from
	// Enumerate's Reason -- fold it into a copy of sorted before handing off
	// to the shared gaps/caveats split, so it surfaces as a caveat the same
	// way any other partial-read gap does.
	effective := sorted
	if len(dupCounts) > 0 {
		effective = append([]Result(nil), sorted...)
		for i, res := range effective {
			d := dupCounts[res.TFType]
			if d == 0 {
				continue
			}
			note := fmt.Sprintf("%d duplicate record(s) skipped", d)
			if res.Reason == "" {
				effective[i].Reason = note
			} else {
				effective[i].Reason = res.Reason + "; " + note
			}
		}
	}

	gaps, caveats := partition(effective)
	if len(gaps) > 0 {
		b.WriteString("# Not imported:\n")
		for _, res := range gaps {
			fmt.Fprintf(&b, "# %-45s %-12s %s\n", res.TFType, res.Status, res.Reason)
		}
	}
	if len(caveats) > 0 {
		if len(gaps) > 0 {
			b.WriteString("\n")
		}
		b.WriteString("# Read with caveats:\n")
		for _, res := range caveats {
			fmt.Fprintf(&b, "# %-45s %-12s %s\n", res.TFType, res.Status, res.Reason)
		}
	}

	return b.String()
}

// partition splits results into gaps -- unsupported/error results, reported
// under "Not imported" -- and caveats: a successful read (status "ok" or
// "empty") that still carries a real gap in Reason, such as records skipped
// for having no usable id, association records skipped for a missing key
// field, or a flat list that 405'd and fell back to a parent-scoped read.
// Those never land in gaps, but dropping the fact silently would tell the
// customer nothing was skipped when something was, so they are reported
// separately. This is the tool's central "no record disappears without a
// count, a reason, and a line in the output" contract; RenderImports and
// FormatReport both call this instead of each re-implementing the split.
func partition(results []Result) (gaps, caveats []Result) {
	for _, r := range results {
		if r.Status == "unsupported" || r.Status == "error" {
			gaps = append(gaps, r)
			continue
		}
		if r.Reason != "" {
			caveats = append(caveats, r)
		}
	}
	return gaps, caveats
}

// escapeHCLTemplate escapes HCL template interpolation ("${") and directive
// ("%{") markers in id so %q-quoting it does not produce a string HCL
// reinterprets. Go's %q leaves both sequences literal; HCL treats them as
// syntax unless doubled.
func escapeHCLTemplate(id string) string {
	id = strings.ReplaceAll(id, "${", "$${")
	id = strings.ReplaceAll(id, "%{", "%%{")
	return id
}
