// Code generated by kgen crud. DO NOT EDIT.

package global_permission_mapping

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/framework"
)

// Data source name constant.
const (
	DSNameGlobalPermissionMapping = "Global Permission Mapping Data Source"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &globalPermissionMappingDataSource{}
	_ datasource.DataSourceWithConfigure = &globalPermissionMappingDataSource{}
)

// listItemAttrTypes defines the schema of each item inside the `list` attribute.
var listItemAttrTypes = map[string]attr.Type{
	"app_role_id":     types.Int64Type,
	"user_groups_ids": types.SetType{ElemType: types.Int64Type},
	"user_ids":        types.SetType{ElemType: types.Int64Type},
}

// NewGlobalPermissionMappingDataSource returns a new instance of the data source.
func NewGlobalPermissionMappingDataSource() datasource.DataSource {
	return &globalPermissionMappingDataSource{}
}

type globalPermissionMappingDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *globalPermissionMappingDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_permission_mapping"
}

func (d *globalPermissionMappingDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion Global Permission Mappings.",
		Attributes: map[string]schema.Attribute{
			"list": schema.ListNestedAttribute{
				Description: "List of permission mappings.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_role_id": schema.Int64Attribute{
							Computed: true,
						},
						"user_groups_ids": schema.SetAttribute{
							Computed:    true,
							ElementType: types.Int64Type,
						},
						"user_ids": schema.SetAttribute{
							Computed:    true,
							ElementType: types.Int64Type,
						},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *globalPermissionMappingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data globalPermissionMappingDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The global permission mapping is a singleton collection: no parent id.
	out, err := conn.GetGlobalUserMappingIndex(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			fmt.Sprintf("reading %s", DSNameGlobalPermissionMapping),
			err.Error(),
		)
		return
	}

	listResp, ok := out.(*generated.GlobalUserMappingListResponse)
	if !ok {
		resp.Diagnostics.Append(errs.ResponseDiagnostics(fmt.Sprintf("reading %s", DSNameGlobalPermissionMapping), out)...)
		return
	}

	// Convert filter blocks to the shared filter model type.
	filters := make([]filter.Model, len(data.Filter))
	for i, f := range data.Filter {
		filters[i] = filter.Model{
			Name:   f.Name,
			Values: f.Values,
			Regex:  f.Regex,
		}
	}

	// Apply client-side filters.
	matched := make([]generated.UserMapping, 0, len(listResp.Data))
	for _, item := range listResp.Data {
		row := userMappingToRow(item)
		ok, matchDiags := filter.Match(ctx, filters, row)
		resp.Diagnostics.Append(matchDiags...)
		if resp.Diagnostics.HasError() {
			return
		}
		if ok {
			matched = append(matched, item)
		}
	}

	listVal, listDiags := buildPermissionMappingList(matched)
	resp.Diagnostics.Append(listDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.List = listVal

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// userMappingToRow converts a UserMapping to the map[string]any shape that
// filter.Match expects.
func userMappingToRow(item generated.UserMapping) map[string]any {
	row := map[string]any{}
	if !item.AppRoleID.Null {
		row["app_role_id"] = int64(item.AppRoleID.Value)
	}
	if item.UserGroupsIds.Set && !item.UserGroupsIds.Null {
		ids := make([]any, 0, len(item.UserGroupsIds.Value))
		for _, id := range item.UserGroupsIds.Value {
			ids = append(ids, int64(id))
		}
		row["user_groups_ids"] = ids
	}
	if item.UserIds.Set && !item.UserIds.Null {
		ids := make([]any, 0, len(item.UserIds.Value))
		for _, id := range item.UserIds.Value {
			ids = append(ids, int64(id))
		}
		row["user_ids"] = ids
	}
	return row
}

// buildPermissionMappingList converts a slice of UserMapping into a
// framework types.List suitable for the `list` attribute.
func buildPermissionMappingList(items []generated.UserMapping) (types.List, diag.Diagnostics) {
	var diags diag.Diagnostics

	objs := make([]attr.Value, 0, len(items))
	for _, item := range items {
		var itemDiags diag.Diagnostics

		userGroupsSet := flattenUint64Set(item.UserGroupsIds, &itemDiags)
		userIDsSet := flattenUint64Set(item.UserIds, &itemDiags)
		diags.Append(itemDiags...)
		if diags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listItemAttrTypes}), diags
		}

		appRoleID := types.Int64Null()
		if !item.AppRoleID.Null {
			appRoleID = types.Int64Value(int64(item.AppRoleID.Value))
		}

		vals := map[string]attr.Value{
			"app_role_id":     appRoleID,
			"user_groups_ids": userGroupsSet,
			"user_ids":        userIDsSet,
		}

		obj, objDiags := types.ObjectValue(listItemAttrTypes, vals)
		diags.Append(objDiags...)
		if diags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listItemAttrTypes}), diags
		}
		objs = append(objs, obj)
	}

	listVal, listDiags := types.ListValue(types.ObjectType{AttrTypes: listItemAttrTypes}, objs)
	diags.Append(listDiags...)
	return listVal, diags
}

type globalPermissionMappingDataSourceFilterModel struct {
	Name   types.String `tfsdk:"name"`
	Values types.List   `tfsdk:"values"`
	Regex  types.Bool   `tfsdk:"regex"`
}

type globalPermissionMappingDataSourceModel struct {
	List   types.List                                     `tfsdk:"list"`
	Filter []globalPermissionMappingDataSourceFilterModel `tfsdk:"filter"`
}

type globalPermissionMappingItemModel struct {
	AppRoleID     types.Int64 `tfsdk:"app_role_id"`
	UserGroupsIDs types.Set   `tfsdk:"user_groups_ids"`
	UserIDs       types.Set   `tfsdk:"user_ids"`
}
