# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_scope" "this" {
  alias          = var.alias
  criteria       = var.criteria
  description    = var.description
  end_datecode   = var.end_datecode
  name           = var.name
  project_id     = var.project_id
  start_datecode = var.start_datecode
}
