# Generated by `kgen module` from the provider schema. Do not edit.

module "this" {
  source = "../.."

  account_type_id    = 1
  aws_account_number = "example"
  billing_start_date = "2026-01"
  linked_role        = "example"
  name               = "example"
}
