// Code generated by kgen crud. DO NOT EDIT.

// Package gcp_service_account implements the Terraform resource and data source for gcp_service_account.
package gcp_service_account

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameGcpServiceAccount = "GcpServiceAccount"

var (
	_ resource.Resource                = &gcp_service_accountResource{}
	_ resource.ResourceWithConfigure   = &gcp_service_accountResource{}
	_ resource.ResourceWithImportState = &gcp_service_accountResource{}
)

// NewGcpServiceAccountResource returns a new instance of the resource.
func NewGcpServiceAccountResource() resource.Resource {
	return &gcp_service_accountResource{}
}

type gcp_service_accountResource struct {
	framework.ResourceWithConfigure
}

func (r *gcp_service_accountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gcp_service_account"
}

func (r *gcp_service_accountResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Schema is generated from the OpenAPI spec (gcp_service_account_schema_gen.go); the
	// bits the spec can't express come from codegen/schema_overrides.yaml.
	resp.Schema = GcpServiceAccountResourceSchema(ctx)
}

func (r *gcp_service_accountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan GcpServiceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.GoogleCloudServiceAccountCreate{
		Description:             flex.OptStringFromFramework(plan.Description),
		Disabled:                flex.OptNilBoolFromFramework(plan.Disabled),
		DisplayName:             flex.OptStringFromFramework(plan.DisplayName),
		Email:                   flex.StringValueFromFramework(plan.Email),
		EnableFederationSupport: flex.NilBoolFromFramework(plan.EnableFederationSupport),
		GcpProjectID:            flex.StringValueFromFramework(plan.GcpProjectId),
		Name:                    flex.StringValueFromFramework(plan.Name),
		OAuthClientID:           flex.OptStringFromFramework(plan.OauthClientId),
		OAuthClientSecret:       flex.OptStringFromFramework(plan.OauthClientSecret),
		UniqueID:                flex.StringValueFromFramework(plan.UniqueId),
	}

	out, err := conn.PostServiceAccount(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameGcpServiceAccount), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back the resource to populate computed fields.
	readOut, readErr := conn.GetServiceAccount(ctx, generated.GetServiceAccountParams{ID: id})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameGcpServiceAccount, id), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenGcpServiceAccount(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gcp_service_accountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	conn := r.Meta().Client

	var state GcpServiceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.GetServiceAccount(ctx, generated.GetServiceAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameGcpServiceAccount, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenGcpServiceAccount(out, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *gcp_service_accountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan GcpServiceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.GoogleCloudServiceAccountUpdate{
		Description:             flex.OptStringFromFramework(plan.Description),
		DisplayName:             flex.OptStringFromFramework(plan.DisplayName),
		EnableFederationSupport: flex.OptNilBoolFromFramework(plan.EnableFederationSupport),
		Name:                    flex.OptStringFromFramework(plan.Name),
		OAuthClientID:           flex.OptStringFromFramework(plan.OauthClientId),
		OAuthClientSecret:       flex.OptStringFromFramework(plan.OauthClientSecret),
	}

	idInt, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.PatchServiceAccount(ctx, input, generated.PatchServiceAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameGcpServiceAccount, idInt), err.Error())
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameGcpServiceAccount), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read back the resource to get the latest state.
	readOut, readErr := conn.GetServiceAccount(ctx, generated.GetServiceAccountParams{ID: idInt})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameGcpServiceAccount, idInt), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenGcpServiceAccount(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gcp_service_accountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state GcpServiceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteServiceAccount(ctx, generated.DeleteServiceAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameGcpServiceAccount, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameGcpServiceAccount), out)
	resp.Diagnostics.Append(diags...)
}

func (r *gcp_service_accountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

func flattenGcpServiceAccount(apiObject any, model *GcpServiceAccountModel) diag.Diagnostics {
	switch v := apiObject.(type) {
	case *generated.GCPServiceAccountResponse:
		if v.Data.Set {
			model.Description = flex.OptStringToFramework(v.Data.Value.Description)
			model.Disabled = flex.OptNilBoolToFramework(v.Data.Value.Disabled)
			model.DisplayName = flex.OptStringToFramework(v.Data.Value.DisplayName)
			model.Email = flex.OptStringToFramework(v.Data.Value.Email)
			model.EnableFederationSupport = flex.OptNilBoolToFramework(v.Data.Value.EnableFederationSupport)
			model.GcpProjectId = flex.OptStringToFramework(v.Data.Value.GcpProjectID)
			if v.Data.Value.ID.Set {
				model.Id = types.StringValue(strconv.FormatUint(v.Data.Value.ID.Value, 10))
			}
			model.Name = flex.OptStringToFramework(v.Data.Value.Name)
			model.OauthClientId = flex.OptStringToFramework(v.Data.Value.OAuthClientID)
			model.OauthClientSecret = flex.OptStringToFramework(v.Data.Value.OAuthClientSecret)
			model.UniqueId = flex.OptStringToFramework(v.Data.Value.UniqueID)
		}
		return nil
	default:
		return errs.ResponseDiagnostics("reading "+ResNameGcpServiceAccount, apiObject)
	}
}
