// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package idms_open_id_access_rule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IdmsOpenIdAccessRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"assertion_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "AssertionName name of the assertion in OpenID.",
				MarkdownDescription: "AssertionName name of the assertion in OpenID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"assertion_regex": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "AssertionRegex is the regular expression used to determine a match.",
				MarkdownDescription: "AssertionRegex is the regular expression used to determine a match.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cloudtamer_access_level_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "CloudtamerAccessLevelID is the ID that represents access level. 1 represents full access, 2 represents no cloud account access and 3 represents no access.",
				MarkdownDescription: "CloudtamerAccessLevelID is the ID that represents access level. 1 represents full access, 2 represents no cloud account access and 3 represents no access.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Access Rule ID.",
				MarkdownDescription: "Access Rule ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"open_id_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the OpenID IDMS the access rule belongs to.",
				MarkdownDescription: "The ID of the OpenID IDMS the access rule belongs to.",
			},
		},
		Description: "Manages an access rule for a Kion OpenID Connect IDMS.",
	}
}

type IdmsOpenIdAccessRuleModel struct {
	AssertionName           types.String `tfsdk:"assertion_name"`
	AssertionRegex          types.String `tfsdk:"assertion_regex"`
	CloudtamerAccessLevelId types.Int64  `tfsdk:"cloudtamer_access_level_id"`
	Id                      types.String `tfsdk:"id"`
	OpenIdId                types.Int64  `tfsdk:"open_id_id"`
}
