# Generated by `kgen module` from the provider schema. Do not edit.

output "created_at" {
  description = "created_at of the kion_compliance_check."
  value       = kion_compliance_check.this.created_at
}

output "ct_managed" {
  description = "ct_managed of the kion_compliance_check."
  value       = kion_compliance_check.this.ct_managed
}

output "id" {
  description = "id of the kion_compliance_check."
  value       = kion_compliance_check.this.id
}

output "last_scan_id" {
  description = "last_scan_id of the kion_compliance_check."
  value       = kion_compliance_check.this.last_scan_id
}
