// Code generated by kgen crud. DO NOT EDIT.

package iam_policy_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionIamPolicy_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_iam_policy.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckIamPolicyDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccIamPolicyConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckIamPolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc IAM policy"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
					resource.TestCheckResourceAttrSet(resourceName, "policy"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionIamPolicy_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_iam_policy.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckIamPolicyDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccIamPolicyConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckIamPolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc IAM policy"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
					resource.TestCheckResourceAttrSet(resourceName, "policy"),
				),
			},
			{
				Config: testAccIamPolicyConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckIamPolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc IAM policy updated"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
					resource.TestCheckResourceAttrSet(resourceName, "policy"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckIamPolicyExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		out, err := conn.Client.GetIAMPolicy(ctx, generated.GetIAMPolicyParams{ID: id})
		if err != nil {
			return fmt.Errorf("reading kion_iam_policy (%d): %w", id, err)
		}
		if errs.IsNotFound(out) {
			return fmt.Errorf("kion_iam_policy (%d) not found", id)
		}

		return nil
	}
}

func testAccCheckIamPolicyDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_iam_policy" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			out, err := conn.Client.GetIAMPolicy(ctx, generated.GetIAMPolicyParams{ID: id})
			if errs.IsNotFound(out) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_iam_policy (%d): %w", id, err)
			}

			return fmt.Errorf("kion_iam_policy (%d) still exists", id)
		}

		return nil
	}
}

func testAccIamPolicyConfig_basic(rName string) string {
	return fmt.Sprintf(`
resource "kion_iam_policy" "test" {
  description = "test-acc IAM policy"
  name = "%[1]s"
  owner_user_ids = [1]
  policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Deny", Action = "s3:*", Resource = "*" }] })
}
`, rName)
}

func testAccIamPolicyConfig_update(rName string) string {
	return fmt.Sprintf(`
resource "kion_iam_policy" "test" {
  description = "test-acc IAM policy updated"
  name = "%[1]s"
  owner_user_ids = [1]
  policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Deny", Action = "s3:*", Resource = "*" }] })
}
`, rName)
}
