// Code generated by kgen crud. DO NOT EDIT.

// Package billing_source_aws implements the Terraform resource for billing_source_aws: public ops go
// through the typed Kion SDK; private ops (the by-id read)
// are absent from the SDK and are served over raw HTTP.
package billing_source_aws

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/conns"
	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameBillingSourceAws = "BillingSourceAws"

var (
	_ resource.Resource                = &billing_source_awsResource{}
	_ resource.ResourceWithConfigure   = &billing_source_awsResource{}
	_ resource.ResourceWithImportState = &billing_source_awsResource{}
)

// NewBillingSourceAwsResource returns a new instance of the resource.
func NewBillingSourceAwsResource() resource.Resource {
	return &billing_source_awsResource{}
}

type billing_source_awsResource struct {
	framework.ResourceWithConfigure
}

func (r *billing_source_awsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_billing_source_aws"
}

func (r *billing_source_awsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = BillingSourceAwsResourceSchema(ctx)
}

// billing_source_awsWire is the private by-id read JSON shape (declared read_shape). Kion
// wraps the payload in {"data": …}.
type billing_source_awsWire struct {
	Data struct {
		AwsPayer struct {
			Id                         uint64 `json:"id"`
			Name                       string `json:"name"`
			AccountNumber              string `json:"account_number"`
			BillingStartDate           int64  `json:"billing_start_date"`
			BucketAccessRole           string `json:"bucket_access_role"`
			BillingRegion              string `json:"billing_region"`
			BillingReportBucket        string `json:"billing_report_bucket"`
			BillingReportBucketRegion  string `json:"billing_report_bucket_region"`
			BillingReportName          string `json:"billing_report_name"`
			BillingReportPrefix        string `json:"billing_report_prefix"`
			BillingBucketAccountNumber string `json:"billing_bucket_account_number"`
		} `json:"aws_payer"`
	} `json:"data"`
}

// read fetches the record over the private API; found is false on a 404.
func (r *billing_source_awsResource) read(ctx context.Context, id int64) (billing_source_awsWire, bool, error) {
	body, err := r.Meta().RawGet(ctx, strings.Replace("/v1/payer/{id}", "{id}", strconv.FormatInt(id, 10), 1))
	if err != nil {
		if conns.IsRawNotFound(err) {
			return billing_source_awsWire{}, false, nil
		}
		return billing_source_awsWire{}, false, err
	}
	var w billing_source_awsWire
	if err := json.Unmarshal(body, &w); err != nil {
		return billing_source_awsWire{}, false, fmt.Errorf("decoding response: %w", err)
	}
	return w, true, nil
}

func (r *billing_source_awsResource) flatten(ctx context.Context, w billing_source_awsWire, m *BillingSourceAwsModel) diag.Diagnostics {
	var diags diag.Diagnostics
	m.Id = types.StringValue(strconv.FormatUint(w.Data.AwsPayer.Id, 10))
	m.Name = types.StringValue(w.Data.AwsPayer.Name)
	m.AwsAccountNumber = types.StringValue(w.Data.AwsPayer.AccountNumber)
	m.BillingStartDate = flex.DatecodeToFramework(w.Data.AwsPayer.BillingStartDate)
	m.BucketAccessRole = types.StringValue(w.Data.AwsPayer.BucketAccessRole)
	m.BillingRegion = types.StringValue(w.Data.AwsPayer.BillingRegion)
	m.CurBucket = types.StringValue(w.Data.AwsPayer.BillingReportBucket)
	m.CurBucketRegion = types.StringValue(w.Data.AwsPayer.BillingReportBucketRegion)
	m.CurName = types.StringValue(w.Data.AwsPayer.BillingReportName)
	m.CurPrefix = types.StringValue(w.Data.AwsPayer.BillingReportPrefix)
	m.BillingBucketAccountNumber = types.StringValue(w.Data.AwsPayer.BillingBucketAccountNumber)

	return diags
}

func (r *billing_source_awsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan BillingSourceAwsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.AWSBillingSourceCreateWithValidation{
		AWSAccountNumber:                flex.StringValueFromFramework(plan.AwsAccountNumber),
		AccountCreation:                 flex.OptNilBoolFromFramework(plan.AccountCreation),
		AccountTypeID:                   flex.NilUint64FromFramework(plan.AccountTypeId),
		BillingBucketAccountNumber:      flex.OptStringFromFramework(plan.BillingBucketAccountNumber),
		BillingRegion:                   flex.OptStringFromFramework(plan.BillingRegion),
		BillingReportType:               flex.OptStringFromFramework(plan.BillingReportType),
		BillingStartDate:                flex.StringValueFromFramework(plan.BillingStartDate),
		BucketAccessRole:                flex.OptStringFromFramework(plan.BucketAccessRole),
		CurBucket:                       flex.OptStringFromFramework(plan.CurBucket),
		CurBucketRegion:                 flex.OptStringFromFramework(plan.CurBucketRegion),
		CurName:                         flex.OptStringFromFramework(plan.CurName),
		CurPrefix:                       flex.OptStringFromFramework(plan.CurPrefix),
		FocusBillingBucketAccountNumber: flex.OptStringFromFramework(plan.FocusBillingBucketAccountNumber),
		FocusBillingReportBucket:        flex.OptStringFromFramework(plan.FocusBillingReportBucket),
		FocusBillingReportBucketRegion:  flex.OptStringFromFramework(plan.FocusBillingReportBucketRegion),
		FocusBillingReportName:          flex.OptStringFromFramework(plan.FocusBillingReportName),
		FocusBillingReportPrefix:        flex.OptStringFromFramework(plan.FocusBillingReportPrefix),
		FocusBucketAccessRole:           flex.OptStringFromFramework(plan.FocusBucketAccessRole),
		KeyID:                           flex.OptStringFromFramework(plan.KeyId),
		KeySecret:                       flex.OptStringFromFramework(plan.KeySecret),
		LinkedRole:                      flex.StringValueFromFramework(plan.LinkedRole),
		MrBucket:                        flex.OptStringFromFramework(plan.MrBucket),
		Name:                            flex.StringValueFromFramework(plan.Name),
		OnlyDbr:                         flex.OptNilBoolFromFramework(plan.OnlyDbr),
		SkipValidation:                  flex.OptNilBoolFromFramework(plan.SkipValidation),
		UseFocusReports:                 flex.OptNilBoolFromFramework(plan.UseFocusReports),
	}

	out, err := conn.PostAWSBillingSource(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameBillingSourceAws), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back over the private API to populate computed fields.
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameBillingSourceAws, id), err.Error())
		return
	}
	if found {
		resp.Diagnostics.Append(r.flatten(ctx, w, &plan)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *billing_source_awsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state BillingSourceAwsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameBillingSourceAws, id), err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(r.flatten(ctx, w, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *billing_source_awsResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not supported", "kion_billing_source_aws cannot be updated in place; changes force replacement.")
}

func (r *billing_source_awsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state BillingSourceAwsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseUint(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteBillingSource(ctx, generated.DeleteBillingSourceParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameBillingSourceAws, idInt), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameBillingSourceAws), out)
	resp.Diagnostics.Append(diags...)
}

func (r *billing_source_awsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
