// Code generated by kgen crud. DO NOT EDIT.

package azure_policy_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionAzurePolicy_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_azure_policy.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAzurePolicyDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccAzurePolicyConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckAzurePolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "azure_policy"),
					resource.TestCheckResourceAttrSet(resourceName, "owner_users"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionAzurePolicy_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_azure_policy.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAzurePolicyDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccAzurePolicyConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckAzurePolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "azure_policy"),
					resource.TestCheckResourceAttrSet(resourceName, "owner_users"),
				),
			},
			{
				Config: testAccAzurePolicyConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckAzurePolicyExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "azure_policy"),
					resource.TestCheckResourceAttrSet(resourceName, "owner_users"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckAzurePolicyExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		out, err := conn.Client.GetAzurePolicyByID(ctx, generated.GetAzurePolicyByIDParams{ID: id})
		if err != nil {
			return fmt.Errorf("reading kion_azure_policy (%d): %w", id, err)
		}
		if errs.IsNotFound(out) {
			return fmt.Errorf("kion_azure_policy (%d) not found", id)
		}

		return nil
	}
}

func testAccCheckAzurePolicyDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_azure_policy" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			out, err := conn.Client.GetAzurePolicyByID(ctx, generated.GetAzurePolicyByIDParams{ID: id})
			if errs.IsNotFound(out) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_azure_policy (%d): %w", id, err)
			}

			return fmt.Errorf("kion_azure_policy (%d) still exists", id)
		}

		return nil
	}
}

func testAccAzurePolicyConfig_basic(rName string) string {
	return fmt.Sprintf(`
resource "kion_azure_policy" "test" {
  azure_policy = { name = "%[1]s", description = "test-acc Azure policy", policy = jsonencode({ policyRule = { if = { field = "type", equals = "Microsoft.Resources/subscriptions" }, then = { effect = "audit" } } }) }
  owner_users = [1]
}
`, rName)
}

func testAccAzurePolicyConfig_update(rName string) string {
	return fmt.Sprintf(`
resource "kion_azure_policy" "test" {
  azure_policy = { name = "%[1]s", description = "test-acc Azure policy updated", policy = jsonencode({ policyRule = { if = { field = "type", equals = "Microsoft.Resources/subscriptions" }, then = { effect = "audit" } } }) }
  owner_users = [1]
}
`, rName)
}
