// Code generated by kgen migrate. DO NOT EDIT.

package azure_policy

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"terraform-provider-kion/internal/migratehelper"
)

var _ resource.ResourceWithUpgradeState = &azure_policyResource{}

// UpgradeState migrates v0 (SDKv2 provider) state to the current schema by
// transforming the raw old-state JSON map and decoding it against the current
// schema. A shape that no longer fits (an object whose fields changed, etc.)
// fails in ValueFromJSON rather than silently.
func (r *azure_policyResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	return map[int64]resource.StateUpgrader{
		0: {
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				var old map[string]json.RawMessage
				if err := json.Unmarshal(req.RawState.JSON, &old); err != nil {
					resp.Diagnostics.AddError("upgrading azure_policy state", err.Error())
					return
				}
				nw := map[string]json.RawMessage{
					"azure_policy":      migratehelper.Null,
					"id":                migratehelper.OrNull(old["id"]),
					"owner_user_groups": migratehelper.ProjectIDs(old["owner_user_groups"], "id"),
					"owner_users":       migratehelper.ProjectIDs(old["owner_users"], "id"),
				}
				b, err := json.Marshal(nw)
				if err != nil {
					resp.Diagnostics.AddError("upgrading azure_policy state", err.Error())
					return
				}
				val, err := tftypes.ValueFromJSON(b, resp.State.Schema.Type().TerraformType(ctx))
				if err != nil {
					resp.Diagnostics.AddError("upgrading azure_policy state", err.Error())
					return
				}
				resp.State = tfsdk.State{Raw: val, Schema: resp.State.Schema}
			},
		},
	}
}
