// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package azure_policy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AzurePolicyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"azure_policy": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"description": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The human-readable description of the policy",
						MarkdownDescription: "The human-readable description of the policy",
					},
					"name": schema.StringAttribute{
						Required:            true,
						Description:         "Human-readable name of the Azure Policy Definition",
						MarkdownDescription: "Human-readable name of the Azure Policy Definition",
					},
					"parameters": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The parameters for the policy",
						MarkdownDescription: "The parameters for the policy",
					},
					"policy": schema.StringAttribute{
						Required:            true,
						Description:         "The JSON for the policy",
						MarkdownDescription: "The JSON for the policy",
					},
				},
				CustomType: AzurePolicyType{
					ObjectType: types.ObjectType{
						AttrTypes: AzurePolicyValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "AzurePolicyDefinitionCreate represents an create Azure Policy Definition, complete with the policy itself and its parameters.",
				MarkdownDescription: "AzurePolicyDefinitionCreate represents an create Azure Policy Definition, complete with the policy itself and its parameters.",
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID.",
				MarkdownDescription: "ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"owner_user_groups": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of user group IDs that will be owners of the azure policy.",
				MarkdownDescription: "List of user group IDs that will be owners of the azure policy.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"owner_users": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of user IDs that will be owners of the azure policy.",
				MarkdownDescription: "List of user IDs that will be owners of the azure policy.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Description: "Manages a Kion Azure Policy.",
	}
}

type AzurePolicyModel struct {
	AzurePolicy     AzurePolicyValue `tfsdk:"azure_policy"`
	Id              types.String     `tfsdk:"id"`
	OwnerUserGroups types.Set        `tfsdk:"owner_user_groups"`
	OwnerUsers      types.Set        `tfsdk:"owner_users"`
}

var _ basetypes.ObjectTypable = AzurePolicyType{}

type AzurePolicyType struct {
	basetypes.ObjectType
}

func (t AzurePolicyType) Equal(o attr.Type) bool {
	other, ok := o.(AzurePolicyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AzurePolicyType) String() string {
	return "AzurePolicyType"
}

func (t AzurePolicyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	parametersAttribute, ok := attributes["parameters"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parameters is missing from object`)

		return nil, diags
	}

	parametersVal, ok := parametersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parameters expected to be basetypes.StringValue, was: %T`, parametersAttribute))
	}

	policyAttribute, ok := attributes["policy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`policy is missing from object`)

		return nil, diags
	}

	policyVal, ok := policyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`policy expected to be basetypes.StringValue, was: %T`, policyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AzurePolicyValue{
		Description: descriptionVal,
		Name:        nameVal,
		Parameters:  parametersVal,
		Policy:      policyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewAzurePolicyValueNull() AzurePolicyValue {
	return AzurePolicyValue{
		state: attr.ValueStateNull,
	}
}

func NewAzurePolicyValueUnknown() AzurePolicyValue {
	return AzurePolicyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAzurePolicyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AzurePolicyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AzurePolicyValue Attribute Value",
				"While creating a AzurePolicyValue value, a missing attribute value was detected. "+
					"A AzurePolicyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AzurePolicyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AzurePolicyValue Attribute Type",
				"While creating a AzurePolicyValue value, an invalid attribute value was detected. "+
					"A AzurePolicyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AzurePolicyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AzurePolicyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AzurePolicyValue Attribute Value",
				"While creating a AzurePolicyValue value, an extra attribute value was detected. "+
					"A AzurePolicyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AzurePolicyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAzurePolicyValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewAzurePolicyValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAzurePolicyValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	parametersAttribute, ok := attributes["parameters"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parameters is missing from object`)

		return NewAzurePolicyValueUnknown(), diags
	}

	parametersVal, ok := parametersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parameters expected to be basetypes.StringValue, was: %T`, parametersAttribute))
	}

	policyAttribute, ok := attributes["policy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`policy is missing from object`)

		return NewAzurePolicyValueUnknown(), diags
	}

	policyVal, ok := policyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`policy expected to be basetypes.StringValue, was: %T`, policyAttribute))
	}

	if diags.HasError() {
		return NewAzurePolicyValueUnknown(), diags
	}

	return AzurePolicyValue{
		Description: descriptionVal,
		Name:        nameVal,
		Parameters:  parametersVal,
		Policy:      policyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewAzurePolicyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AzurePolicyValue {
	object, diags := NewAzurePolicyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAzurePolicyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AzurePolicyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAzurePolicyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAzurePolicyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAzurePolicyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAzurePolicyValueMust(AzurePolicyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AzurePolicyType) ValueType(ctx context.Context) attr.Value {
	return AzurePolicyValue{}
}

var _ basetypes.ObjectValuable = AzurePolicyValue{}

type AzurePolicyValue struct {
	Description basetypes.StringValue `tfsdk:"description"`
	Name        basetypes.StringValue `tfsdk:"name"`
	Parameters  basetypes.StringValue `tfsdk:"parameters"`
	Policy      basetypes.StringValue `tfsdk:"policy"`
	state       attr.ValueState
}

func (v AzurePolicyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["parameters"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["policy"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Parameters.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["parameters"] = val

		val, err = v.Policy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["policy"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AzurePolicyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AzurePolicyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AzurePolicyValue) String() string {
	return "AzurePolicyValue"
}

func (v AzurePolicyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"parameters":  basetypes.StringType{},
		"policy":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description": v.Description,
			"name":        v.Name,
			"parameters":  v.Parameters,
			"policy":      v.Policy,
		})

	return objVal, diags
}

func (v AzurePolicyValue) Equal(o attr.Value) bool {
	other, ok := o.(AzurePolicyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Parameters.Equal(other.Parameters) {
		return false
	}

	if !v.Policy.Equal(other.Policy) {
		return false
	}

	return true
}

func (v AzurePolicyValue) Type(ctx context.Context) attr.Type {
	return AzurePolicyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AzurePolicyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"parameters":  basetypes.StringType{},
		"policy":      basetypes.StringType{},
	}
}
