// Code generated by kgen crud. DO NOT EDIT.

package azure_policy

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const (
	DSNameAzurePolicy = "AzurePolicy Data Source"
)

var (
	_ datasource.DataSource              = &azure_policyDataSource{}
	_ datasource.DataSourceWithConfigure = &azure_policyDataSource{}
)

// listObjectAttrTypes is the schema of an entry inside the `list` attribute.
var listObjectAttrTypes = map[string]attr.Type{
	"id":                          types.Int64Type,
	"description":                 types.StringType,
	"name":                        types.StringType,
	"parameters":                  types.StringType,
	"policy":                      types.StringType,
	"azure_managed_policy_def_id": types.StringType,
	"ct_managed":                  types.BoolType,
	"enabled":                     types.BoolType,
}

// NewAzurePolicyDataSource returns a new instance of the data source.
func NewAzurePolicyDataSource() datasource.DataSource {
	return &azure_policyDataSource{}
}

type azure_policyDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *azure_policyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azure_policy"
}

// Schema is dual-mode: `id` fetches one by primary key; omitting `id` and
// supplying `filter` blocks paginates the index and returns every match in
// `list`. `id` and `filter` are mutually exclusive.
func (d *azure_policyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion AzurePolicys. Supports lookup by id (recommended) or by filter blocks (legacy).",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of a single azure_policy to fetch. Mutually exclusive with `filter` blocks.",
				Optional:    true,
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"parameters": schema.StringAttribute{
				Computed: true,
			},
			"policy": schema.StringAttribute{
				Computed: true,
			},
			"list": schema.ListNestedAttribute{
				Description: "All azure_policys matching the supplied id or filter blocks.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"parameters": schema.StringAttribute{
							Computed: true,
						},
						"policy": schema.StringAttribute{
							Computed: true,
						},
						"azure_managed_policy_def_id": schema.StringAttribute{
							Computed: true,
						},
						"ct_managed": schema.BoolAttribute{
							Computed: true,
						},
						"enabled": schema.BoolAttribute{
							Computed: true,
						},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *azure_policyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data azure_policyDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idSet := !data.Id.IsNull() && !data.Id.IsUnknown()
	filterSet := len(data.Filter) > 0

	if idSet && filterSet {
		resp.Diagnostics.AddError(
			fmt.Sprintf("invalid %s configuration", DSNameAzurePolicy),
			"`id` and `filter` blocks are mutually exclusive.",
		)
		return
	}

	if idSet {
		d.readByID(ctx, conn, &data, &resp.Diagnostics)
	} else {
		d.readByFilter(ctx, conn, &data, &resp.Diagnostics)
	}

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *azure_policyDataSource) readByID(ctx context.Context, conn *generated.Client, data *azure_policyDataSourceModel, diags *diag.Diagnostics) {
	out, err := conn.GetAzurePolicyByID(ctx, generated.GetAzurePolicyByIDParams{ID: data.Id.ValueInt64()})
	if err != nil {
		diags.AddError(fmt.Sprintf("reading %s", DSNameAzurePolicy), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		diags.AddError(fmt.Sprintf("reading %s", DSNameAzurePolicy), "azure_policy not found")
		return
	}
	api, ok := out.(*generated.AzurePolicyResponse)
	if !ok || !api.Data.Set {
		diags.Append(errs.ResponseDiagnostics("reading "+DSNameAzurePolicy, out)...)
		return
	}

	lbl := api.Data.Value
	data.Id = flex.OptUint64ToFramework(lbl.AzurePolicy.Value.ID)
	data.Description = flex.OptStringToFramework(lbl.AzurePolicy.Value.Description)
	data.Name = flex.OptStringToFramework(lbl.AzurePolicy.Value.Name)
	data.Parameters = flex.OptStringToFramework(lbl.AzurePolicy.Value.Parameters)
	data.Policy = flex.OptStringToFramework(lbl.AzurePolicy.Value.Policy)

	listVal, listDiags := buildAzurePolicyList(ctx, []generated.AzurePolicyAugmented{lbl})
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal
}

func (d *azure_policyDataSource) readByFilter(ctx context.Context, conn *generated.Client, data *azure_policyDataSourceModel, diags *diag.Diagnostics) {
	all, fetchDiags := fetchAllAzurePolicy(ctx, conn)
	diags.Append(fetchDiags...)
	if diags.HasError() {
		return
	}

	matched := make([]generated.AzurePolicyAugmented, 0, len(all))
	for _, lbl := range all {
		ok, matchDiags := filter.Match(ctx, data.Filter, azure_policyToRow(lbl))
		diags.Append(matchDiags...)
		if diags.HasError() {
			return
		}
		if ok {
			matched = append(matched, lbl)
		}
	}

	listVal, listDiags := buildAzurePolicyList(ctx, matched)
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal

	// Scalar fields stay null in filter mode.
	data.Id = types.Int64Null()
	data.Description = types.StringNull()
	data.Name = types.StringNull()
	data.Parameters = types.StringNull()
	data.Policy = types.StringNull()
}

// fetchAllAzurePolicy returns the full set from GetAzurePolicyAll, which is not
// paginated: one call yields the whole collection.
func fetchAllAzurePolicy(ctx context.Context, conn *generated.Client) ([]generated.AzurePolicyAugmented, diag.Diagnostics) {
	var diags diag.Diagnostics
	var all []generated.AzurePolicyAugmented

	out, err := conn.GetAzurePolicyAll(ctx)
	if err != nil {
		diags.AddError(fmt.Sprintf("listing %s", DSNameAzurePolicy), err.Error())
		return nil, diags
	}
	resp, ok := out.(*generated.AzurePolicyListResponse)
	if !ok {
		diags.Append(errs.ResponseDiagnostics("listing "+DSNameAzurePolicy, out)...)
		return nil, diags
	}
	items := resp.Data
	all = append(all, items...)

	return all, diags
}

// azure_policyToRow converts an element into the map filter.Match expects.
func azure_policyToRow(lbl generated.AzurePolicyAugmented) map[string]any {
	row := map[string]any{
		"description":                 lbl.AzurePolicy.Value.Description.Or(""),
		"name":                        lbl.AzurePolicy.Value.Name.Or(""),
		"parameters":                  lbl.AzurePolicy.Value.Parameters.Or(""),
		"policy":                      lbl.AzurePolicy.Value.Policy.Or(""),
		"azure_managed_policy_def_id": lbl.AzurePolicy.Value.AzureManagedPolicyDefID.Or(""),
		"ct_managed":                  lbl.AzurePolicy.Value.CtManaged.Or(false),
		"enabled":                     lbl.AzurePolicy.Value.Enabled.Or(false),
	}
	if lbl.AzurePolicy.Value.ID.Set {
		row["id"] = int64(lbl.AzurePolicy.Value.ID.Value)
	}
	return row
}

// buildAzurePolicyList converts elements into a types.List of objects.
func buildAzurePolicyList(ctx context.Context, items []generated.AzurePolicyAugmented) (types.List, diag.Diagnostics) {
	objs := make([]attr.Value, 0, len(items))
	for _, lbl := range items {
		idVal := types.Int64Null()
		if lbl.AzurePolicy.Value.ID.Set {
			idVal = types.Int64Value(int64(lbl.AzurePolicy.Value.ID.Value))
		}
		obj, objDiags := types.ObjectValue(listObjectAttrTypes, map[string]attr.Value{
			"id":                          idVal,
			"description":                 types.StringValue(lbl.AzurePolicy.Value.Description.Or("")),
			"name":                        types.StringValue(lbl.AzurePolicy.Value.Name.Or("")),
			"parameters":                  types.StringValue(lbl.AzurePolicy.Value.Parameters.Or("")),
			"policy":                      types.StringValue(lbl.AzurePolicy.Value.Policy.Or("")),
			"azure_managed_policy_def_id": types.StringValue(lbl.AzurePolicy.Value.AzureManagedPolicyDefID.Or("")),
			"ct_managed":                  types.BoolValue(lbl.AzurePolicy.Value.CtManaged.Or(false)),
			"enabled":                     types.BoolValue(lbl.AzurePolicy.Value.Enabled.Or(false)),
		})
		if objDiags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listObjectAttrTypes}), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, types.ObjectType{AttrTypes: listObjectAttrTypes}, objs)
}

type azure_policyDataSourceModel struct {
	Id          types.Int64    `tfsdk:"id"`
	Description types.String   `tfsdk:"description"`
	Name        types.String   `tfsdk:"name"`
	Parameters  types.String   `tfsdk:"parameters"`
	Policy      types.String   `tfsdk:"policy"`
	Filter      []filter.Model `tfsdk:"filter"`
	List        types.List     `tfsdk:"list"`
}
