// Code generated by kgen crud. DO NOT EDIT.

// Package billing_source_gcp implements the Terraform resource for billing_source_gcp: public ops go
// through the typed Kion SDK; private ops (the by-id read)
// are absent from the SDK and are served over raw HTTP.
package billing_source_gcp

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/conns"
	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameBillingSourceGcp = "BillingSourceGcp"

var (
	_ resource.Resource                = &billing_source_gcpResource{}
	_ resource.ResourceWithConfigure   = &billing_source_gcpResource{}
	_ resource.ResourceWithImportState = &billing_source_gcpResource{}
)

// NewBillingSourceGcpResource returns a new instance of the resource.
func NewBillingSourceGcpResource() resource.Resource {
	return &billing_source_gcpResource{}
}

type billing_source_gcpResource struct {
	framework.ResourceWithConfigure
}

func (r *billing_source_gcpResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_billing_source_gcp"
}

func (r *billing_source_gcpResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = BillingSourceGcpResourceSchema(ctx)
}

// billing_source_gcpWire is the private by-id read JSON shape (declared read_shape). Kion
// wraps the payload in {"data": …}.
type billing_source_gcpWire struct {
	Data struct {
		GcpBillingAccount struct {
			BillingAccount struct {
				Id               uint64 `json:"id"`
				Name             string `json:"name"`
				GcpId            string `json:"gcp_id"`
				BillingStartDate int64  `json:"billing_start_date"`
				IsReseller       bool   `json:"is_reseller"`
				ServiceAccountId int64  `json:"service_account_id"`
			} `json:"billing_account"`
		} `json:"gcp_billing_account"`
	} `json:"data"`
}

// read fetches the record over the private API; found is false on a 404.
func (r *billing_source_gcpResource) read(ctx context.Context, id int64) (billing_source_gcpWire, bool, error) {
	body, err := r.Meta().RawGet(ctx, strings.Replace("/v1/payer/{id}", "{id}", strconv.FormatInt(id, 10), 1))
	if err != nil {
		if conns.IsRawNotFound(err) {
			return billing_source_gcpWire{}, false, nil
		}
		return billing_source_gcpWire{}, false, err
	}
	var w billing_source_gcpWire
	if err := json.Unmarshal(body, &w); err != nil {
		return billing_source_gcpWire{}, false, fmt.Errorf("decoding response: %w", err)
	}
	return w, true, nil
}

func (r *billing_source_gcpResource) flatten(ctx context.Context, w billing_source_gcpWire, m *BillingSourceGcpModel) diag.Diagnostics {
	var diags diag.Diagnostics
	m.Id = types.StringValue(strconv.FormatUint(w.Data.GcpBillingAccount.BillingAccount.Id, 10))
	GcpBillingAccountCreateVal, GcpBillingAccountCreateValDiags := NewGcpBillingAccountCreateValue(GcpBillingAccountCreateValue{}.AttributeTypes(ctx), map[string]attr.Value{
		"name":                                   types.StringValue(w.Data.GcpBillingAccount.BillingAccount.Name),
		"gcp_id":                                 types.StringValue(w.Data.GcpBillingAccount.BillingAccount.GcpId),
		"billing_start_date":                     types.Int64Value(w.Data.GcpBillingAccount.BillingAccount.BillingStartDate),
		"is_reseller":                            types.BoolValue(w.Data.GcpBillingAccount.BillingAccount.IsReseller),
		"service_account_id":                     types.Int64Value(w.Data.GcpBillingAccount.BillingAccount.ServiceAccountId),
		"big_query_export":                       m.GcpBillingAccountCreate.BigQueryExport,
		"billing_account_attribution_account_id": m.GcpBillingAccountCreate.BillingAccountAttributionAccountId,
		"use_focus":                              m.GcpBillingAccountCreate.UseFocus,
		"use_proprietary":                        m.GcpBillingAccountCreate.UseProprietary,
	})
	diags.Append(GcpBillingAccountCreateValDiags...)
	m.GcpBillingAccountCreate = GcpBillingAccountCreateVal

	return diags
}

func (r *billing_source_gcpResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan BillingSourceGcpModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	gcpBillingAccountCreate := generated.GCPBillingAccountWithStart{
		BillingAccountAttributionAccountID: flex.OptNilUint64FromFramework(plan.GcpBillingAccountCreate.BillingAccountAttributionAccountId),
		BillingStartDate:                   flex.StringValueFromFramework(plan.GcpBillingAccountCreate.BillingStartDate),
		GcpID:                              flex.StringValueFromFramework(plan.GcpBillingAccountCreate.GcpId),
		IsReseller:                         flex.OptNilBoolFromFramework(plan.GcpBillingAccountCreate.IsReseller),
		Name:                               flex.StringValueFromFramework(plan.GcpBillingAccountCreate.Name),
		ServiceAccountID:                   flex.NilUint64FromFramework(plan.GcpBillingAccountCreate.ServiceAccountId),
		UseFocus:                           flex.OptNilBoolFromFramework(plan.GcpBillingAccountCreate.UseFocus),
		UseProprietary:                     flex.OptNilBoolFromFramework(plan.GcpBillingAccountCreate.UseProprietary),
	}
	input := &generated.GCPBillingSource{
		AccountTypeID:           flex.NilUint64FromFramework(plan.AccountTypeId),
		GcpBillingAccountCreate: gcpBillingAccountCreate,
	}

	out, err := conn.PostGCPBillingSource(ctx, input, generated.PostGCPBillingSourceParams{})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameBillingSourceGcp), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back over the private API to populate computed fields.
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameBillingSourceGcp, id), err.Error())
		return
	}
	if found {
		resp.Diagnostics.Append(r.flatten(ctx, w, &plan)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *billing_source_gcpResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state BillingSourceGcpModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameBillingSourceGcp, id), err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	resp.Diagnostics.Append(r.flatten(ctx, w, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *billing_source_gcpResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not supported", "kion_billing_source_gcp cannot be updated in place; changes force replacement.")
}

func (r *billing_source_gcpResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state BillingSourceGcpModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseUint(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteBillingSource(ctx, generated.DeleteBillingSourceParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameBillingSourceGcp, idInt), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameBillingSourceGcp), out)
	resp.Diagnostics.Append(diags...)
}

func (r *billing_source_gcpResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
