// Code generated by kgen crud. DO NOT EDIT.

package cft

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const (
	DSNameCft = "Cft Data Source"
)

var (
	_ datasource.DataSource              = &cftDataSource{}
	_ datasource.DataSourceWithConfigure = &cftDataSource{}
)

// listObjectAttrTypes is the schema of an entry inside the `list` attribute.
var listObjectAttrTypes = map[string]attr.Type{
	"id":                     types.Int64Type,
	"description":            types.StringType,
	"name":                   types.StringType,
	"policy":                 types.StringType,
	"region":                 types.StringType,
	"sns_arns":               types.StringType,
	"template_parameters":    types.StringType,
	"termination_protection": types.BoolType,
}

// NewCftDataSource returns a new instance of the data source.
func NewCftDataSource() datasource.DataSource {
	return &cftDataSource{}
}

type cftDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *cftDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cft"
}

// Schema is dual-mode: `id` fetches one by primary key; omitting `id` and
// supplying `filter` blocks paginates the index and returns every match in
// `list`. `id` and `filter` are mutually exclusive.
func (d *cftDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion Cfts. Supports lookup by id (recommended) or by filter blocks (legacy).",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of a single cft to fetch. Mutually exclusive with `filter` blocks.",
				Optional:    true,
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"policy": schema.StringAttribute{
				Computed: true,
			},
			"region": schema.StringAttribute{
				Computed: true,
			},
			"sns_arns": schema.StringAttribute{
				Computed: true,
			},
			"template_parameters": schema.StringAttribute{
				Computed: true,
			},
			"termination_protection": schema.BoolAttribute{
				Computed: true,
			},
			"list": schema.ListNestedAttribute{
				Description: "All cfts matching the supplied id or filter blocks.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"policy": schema.StringAttribute{
							Computed: true,
						},
						"region": schema.StringAttribute{
							Computed: true,
						},
						"sns_arns": schema.StringAttribute{
							Computed: true,
						},
						"template_parameters": schema.StringAttribute{
							Computed: true,
						},
						"termination_protection": schema.BoolAttribute{
							Computed: true,
						},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *cftDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data cftDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idSet := !data.Id.IsNull() && !data.Id.IsUnknown()
	filterSet := len(data.Filter) > 0

	if idSet && filterSet {
		resp.Diagnostics.AddError(
			fmt.Sprintf("invalid %s configuration", DSNameCft),
			"`id` and `filter` blocks are mutually exclusive.",
		)
		return
	}

	if idSet {
		d.readByID(ctx, conn, &data, &resp.Diagnostics)
	} else {
		d.readByFilter(ctx, conn, &data, &resp.Diagnostics)
	}

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *cftDataSource) readByID(ctx context.Context, conn *generated.Client, data *cftDataSourceModel, diags *diag.Diagnostics) {
	out, err := conn.GetCFT(ctx, generated.GetCFTParams{ID: data.Id.ValueInt64()})
	if err != nil {
		diags.AddError(fmt.Sprintf("reading %s", DSNameCft), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		diags.AddError(fmt.Sprintf("reading %s", DSNameCft), "cft not found")
		return
	}
	api, ok := out.(*generated.CFTResponseWithOwnersAndTags)
	if !ok || !api.Data.Set {
		diags.Append(errs.ResponseDiagnostics("reading "+DSNameCft, out)...)
		return
	}

	lbl := api.Data.Value
	data.Id = flex.OptUint64ToFramework(lbl.Cft.Value.ID)
	data.Description = flex.OptStringToFramework(lbl.Cft.Value.Description)
	data.Name = flex.OptStringToFramework(lbl.Cft.Value.Name)
	data.Policy = flex.OptStringToFramework(lbl.Cft.Value.Policy)
	data.Region = flex.OptStringToFramework(lbl.Cft.Value.Region)
	data.SnsArns = flex.OptStringToFramework(lbl.Cft.Value.SnsArns)
	data.TemplateParameters = flex.OptStringToFramework(lbl.Cft.Value.TemplateParameters)
	data.TerminationProtection = flex.OptNilBoolToFramework(lbl.Cft.Value.TerminationProtection)

	listVal, listDiags := buildCftList(ctx, []generated.CFTWithOwnersAndTags{lbl})
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal
}

func (d *cftDataSource) readByFilter(ctx context.Context, conn *generated.Client, data *cftDataSourceModel, diags *diag.Diagnostics) {
	all, fetchDiags := fetchAllCft(ctx, conn)
	diags.Append(fetchDiags...)
	if diags.HasError() {
		return
	}

	matched := make([]generated.CFTWithOwnersAndTags, 0, len(all))
	for _, lbl := range all {
		ok, matchDiags := filter.Match(ctx, data.Filter, cftToRow(lbl))
		diags.Append(matchDiags...)
		if diags.HasError() {
			return
		}
		if ok {
			matched = append(matched, lbl)
		}
	}

	listVal, listDiags := buildCftList(ctx, matched)
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal

	// Scalar fields stay null in filter mode.
	data.Id = types.Int64Null()
	data.Description = types.StringNull()
	data.Name = types.StringNull()
	data.Policy = types.StringNull()
	data.Region = types.StringNull()
	data.SnsArns = types.StringNull()
	data.TemplateParameters = types.StringNull()
	data.TerminationProtection = types.BoolNull()
}

// fetchAllCft returns the full set from GetCFTIndex, which is not
// paginated: one call yields the whole collection.
func fetchAllCft(ctx context.Context, conn *generated.Client) ([]generated.CFTWithOwnersAndTags, diag.Diagnostics) {
	var diags diag.Diagnostics
	var all []generated.CFTWithOwnersAndTags

	out, err := conn.GetCFTIndex(ctx)
	if err != nil {
		diags.AddError(fmt.Sprintf("listing %s", DSNameCft), err.Error())
		return nil, diags
	}
	resp, ok := out.(*generated.CFTListResponseWithOwnersAndTags)
	if !ok {
		diags.Append(errs.ResponseDiagnostics("listing "+DSNameCft, out)...)
		return nil, diags
	}
	items := resp.Data
	all = append(all, items...)

	return all, diags
}

// cftToRow converts an element into the map filter.Match expects.
func cftToRow(lbl generated.CFTWithOwnersAndTags) map[string]any {
	row := map[string]any{
		"description":            lbl.Cft.Value.Description.Or(""),
		"name":                   lbl.Cft.Value.Name.Or(""),
		"policy":                 lbl.Cft.Value.Policy.Or(""),
		"region":                 lbl.Cft.Value.Region.Or(""),
		"sns_arns":               lbl.Cft.Value.SnsArns.Or(""),
		"template_parameters":    lbl.Cft.Value.TemplateParameters.Or(""),
		"termination_protection": lbl.Cft.Value.TerminationProtection.Or(false),
	}
	if lbl.Cft.Value.ID.Set {
		row["id"] = int64(lbl.Cft.Value.ID.Value)
	}
	return row
}

// buildCftList converts elements into a types.List of objects.
func buildCftList(ctx context.Context, items []generated.CFTWithOwnersAndTags) (types.List, diag.Diagnostics) {
	objs := make([]attr.Value, 0, len(items))
	for _, lbl := range items {
		idVal := types.Int64Null()
		if lbl.Cft.Value.ID.Set {
			idVal = types.Int64Value(int64(lbl.Cft.Value.ID.Value))
		}
		obj, objDiags := types.ObjectValue(listObjectAttrTypes, map[string]attr.Value{
			"id":                     idVal,
			"description":            types.StringValue(lbl.Cft.Value.Description.Or("")),
			"name":                   types.StringValue(lbl.Cft.Value.Name.Or("")),
			"policy":                 types.StringValue(lbl.Cft.Value.Policy.Or("")),
			"region":                 types.StringValue(lbl.Cft.Value.Region.Or("")),
			"sns_arns":               types.StringValue(lbl.Cft.Value.SnsArns.Or("")),
			"template_parameters":    types.StringValue(lbl.Cft.Value.TemplateParameters.Or("")),
			"termination_protection": types.BoolValue(lbl.Cft.Value.TerminationProtection.Or(false)),
		})
		if objDiags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listObjectAttrTypes}), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, types.ObjectType{AttrTypes: listObjectAttrTypes}, objs)
}

type cftDataSourceModel struct {
	Id                    types.Int64    `tfsdk:"id"`
	Description           types.String   `tfsdk:"description"`
	Name                  types.String   `tfsdk:"name"`
	Policy                types.String   `tfsdk:"policy"`
	Region                types.String   `tfsdk:"region"`
	SnsArns               types.String   `tfsdk:"sns_arns"`
	TemplateParameters    types.String   `tfsdk:"template_parameters"`
	TerminationProtection types.Bool     `tfsdk:"termination_protection"`
	Filter                []filter.Model `tfsdk:"filter"`
	List                  types.List     `tfsdk:"list"`
}
