// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package cft

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CftResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the Cloudformation template in the application.",
				MarkdownDescription: "Description of the Cloudformation template in the application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "CloudFormation template ID.",
				MarkdownDescription: "CloudFormation template ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the Cloudformation template in the application.",
				MarkdownDescription: "Name of the Cloudformation template in the application.",
			},
			"owner_user_group_ids": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of groups IDs who will own the CloudFormation template. Is required if no user IDs are listed.",
				MarkdownDescription: "List of groups IDs who will own the CloudFormation template. Is required if no user IDs are listed.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"owner_user_ids": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of user IDs who will own the CloudFormation template. Is required if no group IDs are listed.",
				MarkdownDescription: "List of user IDs who will own the CloudFormation template. Is required if no group IDs are listed.",
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.UseStateForUnknown(),
				},
			},
			"policy": schema.StringAttribute{
				Required:            true,
				Description:         "Body of the CloudFormation template in JSON or YAML.",
				MarkdownDescription: "Body of the CloudFormation template in JSON or YAML.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "DEPRECATED! USE THE regions FIELD.\nAWS region where the CloudFormation template applies.",
				MarkdownDescription: "DEPRECATED! USE THE regions FIELD.\nAWS region where the CloudFormation template applies.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"regions": schema.SetAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "List of the AWS regions where the CloudFormation template applies.",
				MarkdownDescription: "List of the AWS regions where the CloudFormation template applies.",
			},
			"sns_arns": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "List of comma separated AWS SNS ARNs that will trigger once the CFT is done applying.",
				MarkdownDescription: "List of comma separated AWS SNS ARNs that will trigger once the CFT is done applying.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"tags": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"tag_key": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "Key of the stack tag.",
							MarkdownDescription: "Key of the stack tag.",
						},
						"tag_value": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "Value of the stack tag.",
							MarkdownDescription: "Value of the stack tag.",
						},
					},
					CustomType: TagsType{
						ObjectType: types.ObjectType{
							AttrTypes: TagsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "AWS Stack Tags used in this role when accessing the AWS console.",
				MarkdownDescription: "AWS Stack Tags used in this role when accessing the AWS console.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"template_parameters": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "List of CloudFormation parameters in a JSON array.",
				MarkdownDescription: "List of CloudFormation parameters in a JSON array.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"termination_protection": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Sets the termination protection status for this CFT.",
				MarkdownDescription: "Sets the termination protection status for this CFT.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Description: "Manages a Kion Cft.",
	}
}

type CftModel struct {
	Description           types.String `tfsdk:"description"`
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	OwnerUserGroupIds     types.Set    `tfsdk:"owner_user_group_ids"`
	OwnerUserIds          types.Set    `tfsdk:"owner_user_ids"`
	Policy                types.String `tfsdk:"policy"`
	Region                types.String `tfsdk:"region"`
	Regions               types.Set    `tfsdk:"regions"`
	SnsArns               types.String `tfsdk:"sns_arns"`
	Tags                  types.List   `tfsdk:"tags"`
	TemplateParameters    types.String `tfsdk:"template_parameters"`
	TerminationProtection types.Bool   `tfsdk:"termination_protection"`
}

var _ basetypes.ObjectTypable = TagsType{}

type TagsType struct {
	basetypes.ObjectType
}

func (t TagsType) Equal(o attr.Type) bool {
	other, ok := o.(TagsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TagsType) String() string {
	return "TagsType"
}

func (t TagsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	tagKeyAttribute, ok := attributes["tag_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_key is missing from object`)

		return nil, diags
	}

	tagKeyVal, ok := tagKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_key expected to be basetypes.StringValue, was: %T`, tagKeyAttribute))
	}

	tagValueAttribute, ok := attributes["tag_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_value is missing from object`)

		return nil, diags
	}

	tagValueVal, ok := tagValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_value expected to be basetypes.StringValue, was: %T`, tagValueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TagsValue{
		TagKey:   tagKeyVal,
		TagValue: tagValueVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewTagsValueNull() TagsValue {
	return TagsValue{
		state: attr.ValueStateNull,
	}
}

func NewTagsValueUnknown() TagsValue {
	return TagsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTagsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TagsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TagsValue Attribute Value",
				"While creating a TagsValue value, a missing attribute value was detected. "+
					"A TagsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TagsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TagsValue Attribute Type",
				"While creating a TagsValue value, an invalid attribute value was detected. "+
					"A TagsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TagsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TagsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TagsValue Attribute Value",
				"While creating a TagsValue value, an extra attribute value was detected. "+
					"A TagsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TagsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTagsValueUnknown(), diags
	}

	tagKeyAttribute, ok := attributes["tag_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_key is missing from object`)

		return NewTagsValueUnknown(), diags
	}

	tagKeyVal, ok := tagKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_key expected to be basetypes.StringValue, was: %T`, tagKeyAttribute))
	}

	tagValueAttribute, ok := attributes["tag_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_value is missing from object`)

		return NewTagsValueUnknown(), diags
	}

	tagValueVal, ok := tagValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_value expected to be basetypes.StringValue, was: %T`, tagValueAttribute))
	}

	if diags.HasError() {
		return NewTagsValueUnknown(), diags
	}

	return TagsValue{
		TagKey:   tagKeyVal,
		TagValue: tagValueVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewTagsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TagsValue {
	object, diags := NewTagsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTagsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TagsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTagsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTagsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTagsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTagsValueMust(TagsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TagsType) ValueType(ctx context.Context) attr.Value {
	return TagsValue{}
}

var _ basetypes.ObjectValuable = TagsValue{}

type TagsValue struct {
	TagKey   basetypes.StringValue `tfsdk:"tag_key"`
	TagValue basetypes.StringValue `tfsdk:"tag_value"`
	state    attr.ValueState
}

func (v TagsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["tag_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tag_value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.TagKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tag_key"] = val

		val, err = v.TagValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tag_value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TagsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TagsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TagsValue) String() string {
	return "TagsValue"
}

func (v TagsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"tag_key":   basetypes.StringType{},
		"tag_value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"tag_key":   v.TagKey,
			"tag_value": v.TagValue,
		})

	return objVal, diags
}

func (v TagsValue) Equal(o attr.Value) bool {
	other, ok := o.(TagsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TagKey.Equal(other.TagKey) {
		return false
	}

	if !v.TagValue.Equal(other.TagValue) {
		return false
	}

	return true
}

func (v TagsValue) Type(ctx context.Context) attr.Type {
	return TagsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TagsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"tag_key":   basetypes.StringType{},
		"tag_value": basetypes.StringType{},
	}
}
