// Code generated by kgen crud. DO NOT EDIT.

package cft

import (
	"context"
	"fmt"
	"strings"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func init() {
	resource.AddTestSweepers("kion_cft", &resource.Sweeper{
		Name: "kion_cft",
		F:    sweepCft,
	})
}

// sweepCft reads GetCFTIndex (not paginated: one call yields the whole
// collection) collecting ids whose test resources carry the acceptance-test
// prefix, then deletes them via DeleteCFT.
func sweepCft(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	ctx := context.Background()

	var ids []int64
	// GetCFTIndex is not paginated: one call returns the whole collection.
	out, err := conn.Client.GetCFTIndex(ctx)
	if err != nil {
		return fmt.Errorf("listing kion_cft: %w", err)
	}
	if resp, ok := out.(*generated.CFTListResponseWithOwnersAndTags); ok {
		items := resp.Data
		for _, item := range items {
			if item.Cft.Value.ID.Set && sweepCftMatch(item) {
				ids = append(ids, int64(item.Cft.Value.ID.Value))
			}
		}
	}

	for _, id := range ids {
		if _, err := conn.Client.DeleteCFT(ctx, generated.DeleteCFTParams{ID: id}); err != nil {
			return fmt.Errorf("deleting kion_cft (%d): %w", id, err)
		}
	}
	return nil
}

func sweepCftMatch(item generated.CFTWithOwnersAndTags) bool {
	for _, s := range []string{
		item.Cft.Value.Description.Or(""),
		item.Cft.Value.Name.Or(""),
		item.Cft.Value.Policy.Or(""),
		item.Cft.Value.Region.Or(""),
		item.Cft.Value.SnsArns.Or(""),
		item.Cft.Value.TemplateParameters.Or(""),
	} {
		if strings.HasPrefix(s, "test-acc") {
			return true
		}
	}
	return false
}
