// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package project_line_item

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ProjectLineItemResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"amount": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Amount for the project line item in the application.",
				MarkdownDescription: "Amount for the project line item in the application.",
			},
			"category_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Category ID of related Category of the Project Line Item in the application.",
				MarkdownDescription: "Category ID of related Category of the Project Line Item in the application.",
			},
			"datecode": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Datecode for the project line item in the application.",
				MarkdownDescription: "Datecode for the project line item in the application.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description for the project line item in the application.",
				MarkdownDescription: "Description for the project line item in the application.",
			},
			"funding_source_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Funding Source ID of related Funding Source of the Project Line Item in the application.",
				MarkdownDescription: "Funding Source ID of related Funding Source of the Project Line Item in the application.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Project line item ID.",
				MarkdownDescription: "Project line item ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"payer_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Payer ID of related Payer of the Project Line Item in the application.",
				MarkdownDescription: "Payer ID of related Payer of the Project Line Item in the application.",
			},
			"project_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Project ID of the Project Line Item in the application.",
				MarkdownDescription: "Project ID of the Project Line Item in the application.",
			},
		},
		Description: "Manages a Kion Project Line Item.",
	}
}

type ProjectLineItemModel struct {
	Amount          types.Float64 `tfsdk:"amount"`
	CategoryId      types.Int64   `tfsdk:"category_id"`
	Datecode        types.Int64   `tfsdk:"datecode"`
	Description     types.String  `tfsdk:"description"`
	FundingSourceId types.Int64   `tfsdk:"funding_source_id"`
	Id              types.String  `tfsdk:"id"`
	PayerId         types.Int64   `tfsdk:"payer_id"`
	ProjectId       types.Int64   `tfsdk:"project_id"`
}
