// Code generated by kgen crud. DO NOT EDIT.

// Package ou implements the Terraform resource and data source for ou.
package ou

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameOu = "Ou"

var (
	_ resource.Resource                = &ouResource{}
	_ resource.ResourceWithConfigure   = &ouResource{}
	_ resource.ResourceWithImportState = &ouResource{}
)

// NewOuResource returns a new instance of the resource.
func NewOuResource() resource.Resource {
	return &ouResource{}
}

type ouResource struct {
	framework.ResourceWithConfigure
}

func (r *ouResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ou"
}

func (r *ouResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Schema is generated from the OpenAPI spec (ou_schema_gen.go); the
	// bits the spec can't express come from codegen/schema_overrides.yaml.
	resp.Schema = OuResourceSchema(ctx)
	resp.Schema.Version = 1
}

func (r *ouResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan OuModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ownerUserGroupIds, ownerUserGroupIdsDiags := flex.Uint64SliceFromFrameworkSet(ctx, plan.OwnerUserGroupIds)
	resp.Diagnostics.Append(ownerUserGroupIdsDiags...)
	ownerUserIds, ownerUserIdsDiags := flex.Uint64SliceFromFrameworkSet(ctx, plan.OwnerUserIds)
	resp.Diagnostics.Append(ownerUserIdsDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.OUCreate{
		Description:        flex.OptStringFromFramework(plan.Description),
		Name:               flex.StringValueFromFramework(plan.Name),
		ParentOuID:         flex.NilUint64FromFramework(plan.ParentOuId),
		PermissionSchemeID: flex.NilUint64FromFramework(plan.PermissionSchemeId),
		OwnerUserGroupIds:  generated.OptNilUint64Array{Value: ownerUserGroupIds, Set: true},
		OwnerUserIds:       generated.OptNilUint64Array{Value: ownerUserIds, Set: true},
	}

	out, err := conn.PostOU(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameOu), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back the resource to populate computed fields.
	readOut, readErr := conn.GetOU(ctx, generated.GetOUParams{ID: id})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameOu, id), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenOu(ctx, readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ouResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	conn := r.Meta().Client

	var state OuModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.GetOU(ctx, generated.GetOUParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameOu, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenOu(ctx, out, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ouResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan OuModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state OuModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.OUUpdatable{
		Description:        flex.OptStringFromFramework(plan.Description),
		Name:               flex.OptStringFromFramework(plan.Name),
		PermissionSchemeID: flex.NilUint64FromFramework(plan.PermissionSchemeId),
	}

	idInt, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.PatchOU(ctx, input, generated.PatchOUParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameOu, idInt), err.Error())
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameOu), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Sync owners: the update body does not carry them, so diff prior state vs
	// plan and add/remove via the dedicated owner endpoints.
	addOwnerUsers, removeOwnerUsers := flex.Uint64SetDiff(ctx, state.OwnerUserIds, plan.OwnerUserIds, &resp.Diagnostics)
	addOwnerGroups, removeOwnerGroups := flex.Uint64SetDiff(ctx, state.OwnerUserGroupIds, plan.OwnerUserGroupIds, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	if len(addOwnerUsers) > 0 || len(addOwnerGroups) > 0 {
		if _, err := conn.PostOUAddOwners(ctx, &generated.OUOwners{
			OwnerUserIds:      generated.OptNilUint64Array{Value: addOwnerUsers, Set: true},
			OwnerUserGroupIds: generated.OptNilUint64Array{Value: addOwnerGroups, Set: true},
		}, generated.PostOUAddOwnersParams{ID: idInt}); err != nil {
			resp.Diagnostics.AddError(fmt.Sprintf("adding owners to %s (ID: %d)", ResNameOu, idInt), err.Error())
			return
		}
	}
	if len(removeOwnerUsers) > 0 || len(removeOwnerGroups) > 0 {
		if _, err := conn.DeleteOURemoveOwners(ctx, &generated.OUOwners{
			OwnerUserIds:      generated.OptNilUint64Array{Value: removeOwnerUsers, Set: true},
			OwnerUserGroupIds: generated.OptNilUint64Array{Value: removeOwnerGroups, Set: true},
		}, generated.DeleteOURemoveOwnersParams{ID: idInt}); err != nil {
			resp.Diagnostics.AddError(fmt.Sprintf("removing owners from %s (ID: %d)", ResNameOu, idInt), err.Error())
			return
		}
	}

	// Read back the resource to get the latest state.
	readOut, readErr := conn.GetOU(ctx, generated.GetOUParams{ID: idInt})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameOu, idInt), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenOu(ctx, readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ouResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state OuModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteOU(ctx, generated.DeleteOUParams{ID: uint64(idInt)})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameOu, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameOu), out)
	resp.Diagnostics.Append(diags...)
}

func (r *ouResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

func flattenOu(ctx context.Context, apiObject any, model *OuModel) diag.Diagnostics {
	var diags diag.Diagnostics
	switch v := apiObject.(type) {
	case *generated.OUResponse:
		if v.Data.Set {
			model.CreatedAt = flex.OptStringToFramework(v.Data.Value.Ou.Value.CreatedAt)
			model.Description = flex.OptStringToFramework(v.Data.Value.Ou.Value.Description)
			if v.Data.Value.Ou.Value.ID.Set {
				model.Id = types.StringValue(strconv.FormatUint(v.Data.Value.Ou.Value.ID.Value, 10))
			}
			model.Name = flex.OptStringToFramework(v.Data.Value.Ou.Value.Name)
			model.ParentOuId = flex.OptNilUint64ToFramework(v.Data.Value.Ou.Value.ParentOuID)
			model.PermissionSchemeId = flex.OptNilUint64ToFramework(v.Data.Value.Ou.Value.PermissionSchemeID)
			var ownerUserGroupsIDs []int64
			for _, elem := range v.Data.Value.OwnerUserGroups.Value {
				if elem.ID.Set {
					ownerUserGroupsIDs = append(ownerUserGroupsIDs, int64(elem.ID.Value))
				}
			}
			// A Set rejects duplicate elements, and the API does return an owner
			// twice on some records; three imports failed outright on this.
			ownerUserGroupsIDs = flex.DedupeInt64(ownerUserGroupsIDs)
			ownerUserGroupsIDsColl, ownerUserGroupsIDsCD := types.SetValueFrom(ctx, types.Int64Type, ownerUserGroupsIDs)
			diags.Append(ownerUserGroupsIDsCD...)
			model.OwnerUserGroupIds = ownerUserGroupsIDsColl
			var ownerUsersIDs []int64
			for _, elem := range v.Data.Value.OwnerUsers.Value {
				if elem.ID.Set {
					ownerUsersIDs = append(ownerUsersIDs, int64(elem.ID.Value))
				}
			}
			// A Set rejects duplicate elements, and the API does return an owner
			// twice on some records; three imports failed outright on this.
			ownerUsersIDs = flex.DedupeInt64(ownerUsersIDs)
			ownerUsersIDsColl, ownerUsersIDsCD := types.SetValueFrom(ctx, types.Int64Type, ownerUsersIDs)
			diags.Append(ownerUsersIDsCD...)
			model.OwnerUserIds = ownerUsersIDsColl
		}
		return diags
	default:
		return errs.ResponseDiagnostics("reading "+ResNameOu, apiObject)
	}
}
