// Package config derives the tfplugingen generator config (codegen/generator_config.yaml)
// from what's already in the repo: each service package's resource/data-source
// code (the SDK ops its CRUD methods call) mapped to spec paths. Implemented
// resources are authoritative; stubs fall back to the spec naming convention and
// are flagged for review.
//
//	kgen config gen    # print the derived config (or --write it)
//	kgen config check  # report drift between the config and the code (CI gate)
package config

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Options configures a run.
type Options struct {
	Spec        string // OpenAPI 3 spec (default spec/openapi3.json)
	ConfigPath  string // generator config to write/compare (default codegen/generator_config.yaml)
	ServiceRoot string // default internal/service
	Overrides   string // hand-tuned entries merged over the derivation (default codegen/config_overrides.yaml)
}

const defaultOverrides = "codegen/config_overrides.yaml"

// CRUD holds the four resolved operations (nil when absent/unresolved).
type CRUD struct {
	Create, Read, Update, Delete *Op
}

func (c *CRUD) empty() bool {
	return c == nil || (c.Create == nil && c.Read == nil && c.Update == nil && c.Delete == nil)
}

// ServiceConfig is the derived config for one service package.
type ServiceConfig struct {
	Name                   string
	Resource               *CRUD
	ResourceHeuristic      bool     // derived from spec naming, not code
	Overridden             bool     // paths supplied by codegen/config_overrides.yaml (config-verified, not code-implemented)
	ExtraIgnores           []string // extra OAS attributes to drop, from config_overrides (appended to baked-in ignores)
	DataSourceRead         *Op
	DataSourceExtraIgnores []string // as ExtraIgnores, for the data-source schema
}

var acronyms = map[string]string{
	"ou": "OU", "gcp": "GCP", "aws": "AWS", "iam": "IAM", "saml": "SAML",
	"idms": "IDMS", "cft": "CFT", "ami": "AMI", "arm": "ARM", "oci": "OCI",
	"api": "API", "scp": "SCP", "id": "ID",
}

func toPascal(snake string) string {
	parts := strings.Split(snake, "_")
	for i, p := range parts {
		switch {
		case p == "":
		case acronyms[p] != "":
			parts[i] = acronyms[p]
		default:
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

// pickVerb returns the first candidate op present in the index whose method is
// one of the wanted methods.
func pickVerb(candidates []string, ops map[string]Op, methods ...string) *Op {
	for _, c := range candidates {
		op, ok := ops[c]
		if !ok {
			continue
		}
		if slices.Contains(methods, op.Method) {
			o := op
			return &o
		}
	}
	return nil
}

func heuristic(name string, ops map[string]Op) *CRUD {
	p := toPascal(name)
	c := &CRUD{}
	if op, ok := ops["Post"+p]; ok {
		c.Create = &op
	}
	if op, ok := ops["Get"+p]; ok {
		c.Read = &op
	}
	if op, ok := ops["Patch"+p]; ok {
		c.Update = &op
	}
	if op, ok := ops["Delete"+p]; ok {
		c.Delete = &op
	}
	return c
}

// Derive builds the config for every service package, preferring the ops the
// code actually calls and falling back to the spec naming convention for stubs.
func Derive(src Source, opts Options) ([]ServiceConfig, error) {
	ops, err := src.Operations(orDefault(opts.Spec, "spec/openapi3.json"))
	if err != nil {
		return nil, fmt.Errorf("reading spec operations: %w", err)
	}
	svcs, err := src.ServiceOps(orDefault(opts.ServiceRoot, "internal/service"))
	if err != nil {
		return nil, fmt.Errorf("reading service ops: %w", err)
	}

	var out []ServiceConfig
	for _, so := range svcs {
		sc := ServiceConfig{Name: so.Name}
		r := &CRUD{
			Create: pickVerb(so.Create, ops, "POST"),
			Read:   pickVerb(so.Read, ops, "GET"),
			Update: pickVerb(so.Update, ops, "PATCH", "PUT"),
			Delete: pickVerb(so.Delete, ops, "DELETE"),
		}
		if r.empty() {
			if h := heuristic(so.Name, ops); !h.empty() {
				r = h
				sc.ResourceHeuristic = true
			}
		}
		if !r.empty() {
			sc.Resource = r
		}
		sc.DataSourceRead = pickVerb(so.DataSourceRead, ops, "GET")
		if sc.Resource != nil || sc.DataSourceRead != nil {
			out = append(out, sc)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// Gen renders the derived config (with overrides merged in) to w.
func Gen(src Source, opts Options, w io.Writer) error {
	configs, err := Derive(src, opts)
	if err != nil {
		return err
	}
	if configs, err = withOverrides(configs, opts); err != nil {
		return err
	}
	_, err = io.WriteString(w, render(configs))
	return err
}

func render(configs []ServiceConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by `kgen config gen` from the service packages + spec/openapi3.json.\n")
	b.WriteString("# Entries flagged `# heuristic` were derived from the spec naming convention\n")
	b.WriteString("# (the resource is a stub with no SDK calls yet); verify their paths.\n")
	b.WriteString("# `# WARN: no read` means tfplugingen will reject the resource until a read is set.\n\n")
	b.WriteString("provider:\n  name: kion\n\n")

	b.WriteString("resources:\n")
	for _, c := range configs {
		if c.Resource == nil {
			continue
		}
		// tfplugingen requires both create and read. List incomplete resources
		// as a comment (kept inactive) so generation still works on the rest;
		// supply the missing op(s) via codegen/config_overrides.yaml to enable.
		var missing []string
		if c.Resource.Create == nil {
			missing = append(missing, "create")
		}
		if c.Resource.Read == nil {
			missing = append(missing, "read")
		}
		if len(missing) > 0 {
			fmt.Fprintf(&b, "  # %s: INCOMPLETE, missing %s (supply via codegen/config_overrides.yaml)\n",
				c.Name, strings.Join(missing, "+"))
			continue
		}
		flag := ""
		if c.ResourceHeuristic {
			flag = "  # heuristic, verify"
		}
		fmt.Fprintf(&b, "  %s:%s\n", c.Name, flag)
		writeOp(&b, "create", c.Resource.Create)
		writeOp(&b, "read", c.Resource.Read)
		writeOp(&b, "update", c.Resource.Update)
		writeOp(&b, "delete", c.Resource.Delete)
		ignores := dedupe(append([]string{"status", "record_id", "data"}, c.ExtraIgnores...))
		fmt.Fprintf(&b, "    schema:\n      ignores: [%s]\n", strings.Join(ignores, ", "))
	}

	b.WriteString("\ndata_sources:\n")
	for _, c := range configs {
		if c.DataSourceRead == nil {
			continue
		}
		fmt.Fprintf(&b, "  %s:\n", c.Name)
		writeOp(&b, "read", c.DataSourceRead)
		dsIgnores := dedupe(append([]string{"status", "record_id"}, c.DataSourceExtraIgnores...))
		fmt.Fprintf(&b, "    schema:\n      ignores: [%s]\n", strings.Join(dsIgnores, ", "))
	}

	var impl, stub, incomplete, ds int
	for _, c := range configs {
		if c.Resource != nil {
			switch {
			case c.Resource.Create == nil || c.Resource.Read == nil:
				incomplete++ // missing create/read -> commented out, not generated
			case c.ResourceHeuristic || c.Overridden:
				stub++ // no SDK code yet (heuristic guess or override-supplied paths)
			default:
				impl++ // CRUD actually calls the SDK
			}
		}
		if c.DataSourceRead != nil {
			ds++
		}
	}
	fmt.Fprintf(&b, "\n# summary: %d generatable (%d implemented, %d stub), %d incomplete; %d data sources\n",
		impl+stub, impl, stub, incomplete, ds)
	return b.String()
}

// dedupe removes repeats while preserving first-seen order. Overrides commonly
// restate the baked-in status/record_id/data alongside their own additions, and
// emitting each twice makes the rendered config noisy and its diffs misleading.
func dedupe(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := in[:0:0]
	for _, v := range in {
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}

func writeOp(b *strings.Builder, verb string, op *Op) {
	if op == nil {
		return
	}
	fmt.Fprintf(b, "    %s:\n      path: %s\n      method: %s\n", verb, op.Path, op.Method)
}

// --- check (drift) ---

type yOp struct {
	Path   string `yaml:"path"`
	Method string `yaml:"method"`
}
type yEntry struct {
	Create yOp `yaml:"create"`
	Read   yOp `yaml:"read"`
}
type yCfg struct {
	Resources   map[string]yEntry `yaml:"resources"`
	DataSources map[string]yEntry `yaml:"data_sources"`
}

// Check compares the committed config against what the code implies and reports
// drift to w, returning the number of drifts found (0 == in sync).
func Check(src Source, opts Options, w io.Writer) (int, error) {
	configs, err := Derive(src, opts)
	if err != nil {
		return 0, err
	}
	if configs, err = withOverrides(configs, opts); err != nil {
		return 0, err
	}
	cfgPath := orDefault(opts.ConfigPath, "codegen/generator_config.yaml")
	raw, err := os.ReadFile(cfgPath)
	if err != nil {
		return 0, fmt.Errorf("reading %s: %w", cfgPath, err)
	}
	var cur yCfg
	if err := yaml.Unmarshal(raw, &cur); err != nil {
		return 0, fmt.Errorf("parsing %s: %w", cfgPath, err)
	}

	derived := make(map[string]ServiceConfig, len(configs))
	for _, c := range configs {
		derived[c.Name] = c
	}

	// emit writes a report line, remembering the first write error so the caller
	// can surface it once rather than after every line.
	var werr error
	emit := func(format string, a ...any) {
		if werr != nil {
			return
		}
		_, werr = fmt.Fprintf(w, format, a...)
	}

	problems := 0
	// Implemented (non-heuristic) resources missing from, or stale in, the config.
	for _, c := range configs {
		if c.Resource == nil || c.ResourceHeuristic {
			continue
		}
		ce, ok := cur.Resources[c.Name]
		if !ok {
			emit("missing: resource %q is implemented but not in the config\n", c.Name)
			problems++
			continue
		}
		if c.Resource.Create != nil && ce.Create.Path != "" && ce.Create.Path != c.Resource.Create.Path {
			emit("stale: resource %q create path config=%s code=%s\n", c.Name, ce.Create.Path, c.Resource.Create.Path)
			problems++
		}
	}
	// Config resources that no longer map to a service package. Derive only sees
	// packages whose CRUD calls the SDK, so a resource served entirely over raw
	// HTTP (internal/conns, declared in codegen/private_endpoints.yaml) resolves
	// no ops and is absent from derived even though its package is right there.
	// funding_source_note is one, and it was reported extra for exactly that
	// reason. Check the claim being made: does the directory exist?
	serviceRoot := orDefault(opts.ServiceRoot, "internal/service")
	for name := range cur.Resources {
		if _, ok := derived[name]; ok {
			continue
		}
		if fi, err := os.Stat(filepath.Join(serviceRoot, name)); err == nil && fi.IsDir() {
			continue
		}
		emit("extra: config resource %q has no matching service package\n", name)
		problems++
	}
	if problems == 0 {
		emit("config in sync with code\n")
	}
	return problems, werr
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// --- overrides: hand-tuned entries the derivation can't reproduce ---

type ovEntry struct {
	Create  *yOp     `yaml:"create"`
	Read    *yOp     `yaml:"read"`
	Update  *yOp     `yaml:"update"`
	Delete  *yOp     `yaml:"delete"`
	Ignores []string `yaml:"ignores"` // extra OAS attributes to drop (appended to the baked-in ignores)

	// Schema accepts the same `schema: { ignores: [...] }` shape that the rendered
	// generator_config.yaml uses. Authors reasonably mirror the output format when
	// writing an override, and before this field existed those entries parsed
	// cleanly and were then discarded, the ignores never reached the generator and
	// the dropped attributes silently reappeared in the schema. Both spellings are
	// honored and merged; see allIgnores.
	Schema *ovSchema `yaml:"schema"`
}

type ovSchema struct {
	Ignores []string `yaml:"ignores"`
}

// allIgnores returns the entry's extra ignores from either spelling.
func (e ovEntry) allIgnores() []string {
	out := append([]string(nil), e.Ignores...)
	if e.Schema != nil {
		out = append(out, e.Schema.Ignores...)
	}
	return out
}

type overridesFile struct {
	Resources   map[string]ovEntry `yaml:"resources"`
	DataSources map[string]ovEntry `yaml:"data_sources"`
}

func (o *yOp) toOp() *Op {
	if o == nil || o.Path == "" {
		return nil
	}
	return &Op{Method: o.Method, Path: o.Path}
}

// withOverrides reads the (optional) overrides file and overlays it onto the
// derived configs so hand-tuned entries survive regeneration.
func withOverrides(configs []ServiceConfig, opts Options) ([]ServiceConfig, error) {
	path := orDefault(opts.Overrides, defaultOverrides)
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return configs, nil
		}
		return nil, fmt.Errorf("reading overrides %s: %w", path, err)
	}
	var ov overridesFile
	// KnownFields: a misspelled or misplaced key in this file used to be dropped
	// in silence, which is how `schema: { ignores: ... }` entries went unapplied
	// for four resources without any signal. Fail the generate instead.
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&ov); err != nil && !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("parsing overrides %s: %w", path, err)
	}
	return applyOverrides(configs, ov), nil
}

// applyOverrides overlays overrides onto the derived configs: overridden verbs
// win, an overridden resource is no longer treated as heuristic, and entries
// present only in the overrides are added.
func applyOverrides(configs []ServiceConfig, ov overridesFile) []ServiceConfig {
	m := make(map[string]ServiceConfig, len(configs))
	for _, c := range configs {
		m[c.Name] = c
	}
	for name, e := range ov.Resources {
		sc := m[name]
		sc.Name = name
		if sc.Resource == nil {
			sc.Resource = &CRUD{}
		}
		if op := e.Create.toOp(); op != nil {
			sc.Resource.Create = op
		}
		if op := e.Read.toOp(); op != nil {
			sc.Resource.Read = op
		}
		if op := e.Update.toOp(); op != nil {
			sc.Resource.Update = op
		}
		if op := e.Delete.toOp(); op != nil {
			sc.Resource.Delete = op
		}
		sc.ResourceHeuristic = false // human-verified via override (no "# heuristic" annotation)
		sc.Overridden = true         // but its CRUD is not code-implemented
		sc.ExtraIgnores = append(sc.ExtraIgnores, e.allIgnores()...)
		m[name] = sc
	}
	for name, e := range ov.DataSources {
		sc := m[name]
		sc.Name = name
		if op := e.Read.toOp(); op != nil {
			sc.DataSourceRead = op
		}
		sc.DataSourceExtraIgnores = append(sc.DataSourceExtraIgnores, e.allIgnores()...)
		m[name] = sc
	}
	out := make([]ServiceConfig, 0, len(m))
	for _, c := range m {
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
