// Code generated by `kgen versions`; DO NOT EDIT.
package ou_cloud_access_role

import (
	"context"

	"terraform-provider-kion/internal/conns"
	"terraform-provider-kion/internal/framework"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

var (
	minKionVersion = conns.KionVersion{}
	maxKionVersion = conns.KionVersion{} // unbounded
)

// attrKionVersions is the Kion version window accepting each attribute. An
// attribute absent here is accepted for as long as the operation exists.
var attrKionVersions = map[string]framework.AttrVersions{
	"aws_create_instance_profile": {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
	"aws_iam_role_trust_policy":   {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
	"aws_partition":               {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
	"aws_trusted_account_numbers": {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
	"aws_trusted_services":        {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
	"cloud_access_role_type_id":   {{Min: conns.MustParseKionVersion("3.15.13"), Before: conns.MustParseKionVersion("3.16.0")}, {Min: conns.MustParseKionVersion("3.16.5"), Before: conns.MustParseKionVersion("3.17.0")}, {Min: conns.MustParseKionVersion("3.17.1")}},
}

var _ resource.ResourceWithModifyPlan = &ou_cloud_access_roleResource{}

// ModifyPlan reports an unsupported Kion version during plan. The CRUD methods
// gate too, but they run at apply, by which point the practitioner has already
// been told the change is going ahead.
//
// A destroy plan is exempt: refusing it would strand the resource in state with
// no way out but terraform state rm.
func (r *ou_cloud_access_roleResource) ModifyPlan(_ context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		return
	}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "kion_ou_cloud_access_role")...)
	resp.Diagnostics.Append(framework.RequireAttrKionVersions(r.Meta(), req.Plan, attrKionVersions, "kion_ou_cloud_access_role")...)
}
