// Code generated by kgen crud. DO NOT EDIT.

package ou_cloud_access_role

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_ou_cloud_access_role", &resource.Sweeper{
		Name: "kion_ou_cloud_access_role",
		F:    sweepOuCloudAccessRole,
	})
}

func sweepOuCloudAccessRole(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_ou_cloud_access_role resources with the "test-acc" prefix and
	// delete each via conn.Client.DeleteOUCloudAccessRole.
	// A real list+delete sweeper needs paginated-list-envelope resolution — see
	// the CRUD generator follow-up plan.
	return nil
}
