// Code generated by kgen crud. DO NOT EDIT.

package idms

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const (
	DSNameIdms = "Idms Data Source"
)

var (
	_ datasource.DataSource              = &idmsDataSource{}
	_ datasource.DataSourceWithConfigure = &idmsDataSource{}
)

// listObjectAttrTypes is the schema of an entry inside the `list` attribute.
var listObjectAttrTypes = map[string]attr.Type{
	"id":                  types.Int64Type,
	"idms_type_id":        types.Int64Type,
	"name":                types.StringType,
	"password_expiration": types.Int64Type,
}

// NewIdmsDataSource returns a new instance of the data source.
func NewIdmsDataSource() datasource.DataSource {
	return &idmsDataSource{}
}

type idmsDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *idmsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_idms"
}

// Schema is dual-mode: `id` fetches one by primary key; omitting `id` and
// supplying `filter` blocks paginates the index and returns every match in
// `list`. `id` and `filter` are mutually exclusive.
func (d *idmsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion Idmss. Supports lookup by id (recommended) or by filter blocks (legacy).",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of a single idms to fetch. Mutually exclusive with `filter` blocks.",
				Optional:    true,
				Computed:    true,
			},
			"idms_type_id": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"password_expiration": schema.Int64Attribute{
				Computed: true,
			},
			"list": schema.ListNestedAttribute{
				Description: "All idmss matching the supplied id or filter blocks.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"idms_type_id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"password_expiration": schema.Int64Attribute{
							Computed: true,
						},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *idmsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data idmsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idSet := !data.Id.IsNull() && !data.Id.IsUnknown()
	filterSet := len(data.Filter) > 0

	if idSet && filterSet {
		resp.Diagnostics.AddError(
			fmt.Sprintf("invalid %s configuration", DSNameIdms),
			"`id` and `filter` blocks are mutually exclusive.",
		)
		return
	}

	if idSet {
		d.readByID(ctx, conn, &data, &resp.Diagnostics)
	} else {
		d.readByFilter(ctx, conn, &data, &resp.Diagnostics)
	}

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *idmsDataSource) readByID(ctx context.Context, conn *generated.Client, data *idmsDataSourceModel, diags *diag.Diagnostics) {
	out, err := conn.GetIDMS(ctx, generated.GetIDMSParams{ID: data.Id.ValueInt64()})
	if err != nil {
		diags.AddError(fmt.Sprintf("reading %s", DSNameIdms), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		diags.AddError(fmt.Sprintf("reading %s", DSNameIdms), "idms not found")
		return
	}
	api, ok := out.(*generated.IDMSResponse)
	if !ok || !api.Data.Set {
		diags.Append(errs.ResponseDiagnostics("reading "+DSNameIdms, out)...)
		return
	}

	lbl := api.Data.Value
	data.Id = flex.OptUint64ToFramework(lbl.ID)
	data.IdmsTypeId = flex.OptNilUint64ToFramework(lbl.IdmsTypeID)
	data.Name = flex.OptStringToFramework(lbl.Name)
	data.PasswordExpiration = flex.OptInt64ToFramework(lbl.PasswordExpiration)

	listVal, listDiags := buildIdmsList(ctx, []generated.IDMS{lbl})
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal
}

func (d *idmsDataSource) readByFilter(ctx context.Context, conn *generated.Client, data *idmsDataSourceModel, diags *diag.Diagnostics) {
	all, fetchDiags := fetchAllIdms(ctx, conn)
	diags.Append(fetchDiags...)
	if diags.HasError() {
		return
	}

	matched := make([]generated.IDMS, 0, len(all))
	for _, lbl := range all {
		ok, matchDiags := filter.Match(ctx, data.Filter, idmsToRow(lbl))
		diags.Append(matchDiags...)
		if diags.HasError() {
			return
		}
		if ok {
			matched = append(matched, lbl)
		}
	}

	listVal, listDiags := buildIdmsList(ctx, matched)
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal

	// Scalar fields stay null in filter mode.
	data.Id = types.Int64Null()
	data.IdmsTypeId = types.Int64Null()
	data.Name = types.StringNull()
	data.PasswordExpiration = types.Int64Null()
}

// fetchAllIdms returns the full set from GetIDMSIndex, which is not
// paginated: one call yields the whole collection.
func fetchAllIdms(ctx context.Context, conn *generated.Client) ([]generated.IDMS, diag.Diagnostics) {
	var diags diag.Diagnostics
	var all []generated.IDMS

	out, err := conn.GetIDMSIndex(ctx)
	if err != nil {
		diags.AddError(fmt.Sprintf("listing %s", DSNameIdms), err.Error())
		return nil, diags
	}
	resp, ok := out.(*generated.IDMSListResponse)
	if !ok {
		diags.Append(errs.ResponseDiagnostics("listing "+DSNameIdms, out)...)
		return nil, diags
	}
	items := resp.Data
	all = append(all, items...)

	return all, diags
}

// idmsToRow converts an element into the map filter.Match expects.
func idmsToRow(lbl generated.IDMS) map[string]any {
	row := map[string]any{
		"idms_type_id":        int64(lbl.IdmsTypeID.Or(0)),
		"name":                lbl.Name.Or(""),
		"password_expiration": lbl.PasswordExpiration.Or(0),
	}
	if lbl.ID.Set {
		row["id"] = int64(lbl.ID.Value)
	}
	return row
}

// buildIdmsList converts elements into a types.List of objects.
func buildIdmsList(ctx context.Context, items []generated.IDMS) (types.List, diag.Diagnostics) {
	objs := make([]attr.Value, 0, len(items))
	for _, lbl := range items {
		idVal := types.Int64Null()
		if lbl.ID.Set {
			idVal = types.Int64Value(int64(lbl.ID.Value))
		}
		obj, objDiags := types.ObjectValue(listObjectAttrTypes, map[string]attr.Value{
			"id":                  idVal,
			"idms_type_id":        types.Int64Value(int64(lbl.IdmsTypeID.Or(0))),
			"name":                types.StringValue(lbl.Name.Or("")),
			"password_expiration": types.Int64Value(lbl.PasswordExpiration.Or(0)),
		})
		if objDiags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listObjectAttrTypes}), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, types.ObjectType{AttrTypes: listObjectAttrTypes}, objs)
}

type idmsDataSourceModel struct {
	Id                 types.Int64    `tfsdk:"id"`
	IdmsTypeId         types.Int64    `tfsdk:"idms_type_id"`
	Name               types.String   `tfsdk:"name"`
	PasswordExpiration types.Int64    `tfsdk:"password_expiration"`
	Filter             []filter.Model `tfsdk:"filter"`
	List               types.List     `tfsdk:"list"`
}
