# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_billing_source_oci" "this" {
  account_type_id         = var.account_type_id
  billing_start_date      = var.billing_start_date
  fingerprint             = var.fingerprint
  is_parent_tenancy       = var.is_parent_tenancy
  name                    = var.name
  private_key             = var.private_key
  region                  = var.region
  skip_validation         = var.skip_validation
  tenancy_ocid            = var.tenancy_ocid
  use_focus_reports       = var.use_focus_reports
  use_proprietary_reports = var.use_proprietary_reports
  user_ocid               = var.user_ocid
}
