# Generated by `kgen module` from the provider schema. Do not edit.

variable "account_type_id" {
  description = "The Account Type ID is the corresponding billing source account's type. 26 - OCI Commercial 27 - OCI Government 28 - OCI Federal"
  type        = number
  default     = null
}

variable "billing_start_date" {
  description = "Start date of billing source (YYYY-MM)."
  type        = string
}

variable "fingerprint" {
  description = "The api access fingerprint"
  type        = string
  default     = null
}

variable "is_parent_tenancy" {
  description = "Indicates whether the billing source is a parent OCI tenancy."
  type        = bool
  default     = null
}

variable "name" {
  description = "Name of the billing source."
  type        = string
  default     = null
}

variable "private_key" {
  description = "The private key used for API Access"
  type        = string
  sensitive   = true
  default     = null
}

variable "region" {
  description = "The OCI default api region"
  type        = string
  default     = null
}

variable "skip_validation" {
  description = "When true, will skip validating the connection to the billing source"
  type        = bool
  default     = null
}

variable "tenancy_ocid" {
  description = "The OCID of the tenancy"
  type        = string
  default     = null
}

variable "use_focus_reports" {
  description = "Use FOCUS Reports - If true, Kion will use FOCUS reports for this billing source"
  type        = bool
  default     = null
}

variable "use_proprietary_reports" {
  description = "Use Proprietary Reports - If true, Kion will use proprietary reports for this billing source"
  type        = bool
  default     = null
}

variable "user_ocid" {
  description = "The OCID of the api user"
  type        = string
  default     = null
}
