// Code generated by kgen crud. DO NOT EDIT.

package account_linkage

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const DSNameAccountLinkage = "AccountLinkage Data Source"

var (
	_ datasource.DataSource              = &account_linkageDataSource{}
	_ datasource.DataSourceWithConfigure = &account_linkageDataSource{}
)

// NewAccountLinkageDataSource returns a new instance of the data source.
func NewAccountLinkageDataSource() datasource.DataSource {
	return &account_linkageDataSource{}
}

type account_linkageDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *account_linkageDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account_linkage"
}

func (d *account_linkageDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to look up a Kion AccountLinkage by id.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of the AccountLinkage to fetch.",
				Required:    true,
			},
			"azure_object_id": schema.StringAttribute{
				Computed: true,
			},
			"payer_id": schema.Int64Attribute{
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (d *account_linkageDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data account_linkageDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := conn.GetSpecificAccountLinkage(ctx, generated.GetSpecificAccountLinkageParams{ID: uint64(data.Id.ValueInt64())})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameAccountLinkage), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameAccountLinkage), "account_linkage not found")
		return
	}

	api, ok := out.(*generated.AzureLinkageResponse)
	if !ok || !api.Data.Set {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("reading "+DSNameAccountLinkage, out)...)
		return
	}

	v := api.Data.Value
	data.Id = flex.OptUint64ToFramework(v.ID)
	data.AzureObjectId = flex.OptStringToFramework(v.AzureObjectID)
	data.PayerId = flex.OptNilUint64ToFramework(v.PayerID)
	data.UserId = flex.OptNilUint64ToFramework(v.UserID)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type account_linkageDataSourceModel struct {
	Id            types.Int64  `tfsdk:"id"`
	AzureObjectId types.String `tfsdk:"azure_object_id"`
	PayerId       types.Int64  `tfsdk:"payer_id"`
	UserId        types.Int64  `tfsdk:"user_id"`
}
