// Code generated by kgen crud. DO NOT EDIT.

package account_linkage

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_account_linkage", &resource.Sweeper{
		Name: "kion_account_linkage",
		F:    sweepAccountLinkage,
	})
}

func sweepAccountLinkage(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_account_linkage resources with the "test-acc" prefix and
	// delete each via conn.Client.RemoveAccountLinkage.
	// A real list+delete sweeper needs paginated-list-envelope resolution — see
	// the CRUD generator follow-up plan.
	return nil
}
