// Code generated by kgen crud. DO NOT EDIT.

package dashboard_test

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/conns"
)

func TestAccKionDashboard_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_dashboard.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckDashboardDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccDashboardConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckDashboardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "config"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc dashboard"),
					resource.TestCheckResourceAttr(resourceName, "is_default", "false"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionDashboard_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_dashboard.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckDashboardDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccDashboardConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckDashboardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "config"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc dashboard"),
					resource.TestCheckResourceAttr(resourceName, "is_default", "false"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
				),
			},
			{
				Config: testAccDashboardConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckDashboardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "config"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc dashboard, updated"),
					resource.TestCheckResourceAttr(resourceName, "is_default", "false"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

// dashboardReadPath is the private route this resource reads through; a blended
// resource has no typed by-id GET.
func dashboardReadPath(id int64) string {
	return strings.Replace("/v1/dashboard/{id}", "{id}", strconv.FormatInt(id, 10), 1)
}

func testAccCheckDashboardExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		if _, err := conn.RawGet(ctx, dashboardReadPath(id)); err != nil {
			if conns.IsRawNotFound(err) {
				return fmt.Errorf("kion_dashboard (%d) not found", id)
			}
			return fmt.Errorf("reading kion_dashboard (%d): %w", id, err)
		}

		return nil
	}
}

func testAccCheckDashboardDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_dashboard" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			_, err = conn.RawGet(ctx, dashboardReadPath(id))
			if conns.IsRawNotFound(err) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_dashboard (%d): %w", id, err)
			}

			return fmt.Errorf("kion_dashboard (%d) still exists", id)
		}

		return nil
	}
}

func testAccDashboardConfig_basic(rName string) string {
	return fmt.Sprintf(`
resource "kion_dashboard" "test" {
  config = jsonencode({})
  description = "test-acc dashboard"
  is_default = false
  name = "%[1]s"
}
`, rName)
}

func testAccDashboardConfig_update(rName string) string {
	return fmt.Sprintf(`
resource "kion_dashboard" "test" {
  config = jsonencode({})
  description = "test-acc dashboard, updated"
  is_default = false
  name = "%[1]s"
}
`, rName)
}
