// Code generated by kgen crud. DO NOT EDIT.

package billing_source_govcloud_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionBillingSourceGovcloud_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	payerID := acctest.RequireEnv(t, "KION_ACC_PAYER_ID", "the payer id")
	awsAccountNumber := acctest.RequireEnv(t, "KION_ACC_AWS_ACCOUNT_NUMBER", "the aws account number")
	resourceName := "kion_billing_source_govcloud.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckBillingSourceGovcloudDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccBillingSourceGovcloudConfig_basic(rName, payerID, awsAccountNumber),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckBillingSourceGovcloudExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "aws_account_number", fmt.Sprintf("%[3]s", rName, payerID, awsAccountNumber)),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("test-acc-%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "payer_id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionBillingSourceGovcloud_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	payerID := acctest.RequireEnv(t, "KION_ACC_PAYER_ID", "the payer id")
	awsAccountNumber := acctest.RequireEnv(t, "KION_ACC_AWS_ACCOUNT_NUMBER", "the aws account number")
	resourceName := "kion_billing_source_govcloud.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckBillingSourceGovcloudDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccBillingSourceGovcloudConfig_basic(rName, payerID, awsAccountNumber),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckBillingSourceGovcloudExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "aws_account_number", fmt.Sprintf("%[3]s", rName, payerID, awsAccountNumber)),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("test-acc-%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "payer_id"),
				),
			},
			{
				Config: testAccBillingSourceGovcloudConfig_update(rName, payerID, awsAccountNumber),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckBillingSourceGovcloudExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "aws_account_number", fmt.Sprintf("%[3]s", rName, payerID, awsAccountNumber)),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("test-acc-%[1]s-upd", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "payer_id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckBillingSourceGovcloudExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseUint(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		out, err := conn.Client.GetBillingSourceGetGovcloudInfo(ctx, generated.GetBillingSourceGetGovcloudInfoParams{ID: id})
		if err != nil {
			return fmt.Errorf("reading kion_billing_source_govcloud (%d): %w", id, err)
		}
		if errs.IsNotFound(out) {
			return fmt.Errorf("kion_billing_source_govcloud (%d) not found", id)
		}

		return nil
	}
}

func testAccCheckBillingSourceGovcloudDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_billing_source_govcloud" {
				continue
			}

			id, err := strconv.ParseUint(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			out, err := conn.Client.GetBillingSourceGetGovcloudInfo(ctx, generated.GetBillingSourceGetGovcloudInfoParams{ID: id})
			if errs.IsNotFound(out) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_billing_source_govcloud (%d): %w", id, err)
			}

			return fmt.Errorf("kion_billing_source_govcloud (%d) still exists", id)
		}

		return nil
	}
}

func testAccBillingSourceGovcloudConfig_basic(rName string, payerID string, awsAccountNumber string) string {
	return fmt.Sprintf(`
resource "kion_billing_source_govcloud" "test" {
  aws_account_number = "%[3]s"
  name = "test-acc-%[1]s"
  payer_id = %[2]s
}
`, rName, payerID, awsAccountNumber)
}

func testAccBillingSourceGovcloudConfig_update(rName string, payerID string, awsAccountNumber string) string {
	return fmt.Sprintf(`
resource "kion_billing_source_govcloud" "test" {
  aws_account_number = "%[3]s"
  name = "test-acc-%[1]s-upd"
  payer_id = %[2]s
}
`, rName, payerID, awsAccountNumber)
}
