// Code generated by kgen crud. DO NOT EDIT.

package billing_source_govcloud

// No acceptance-test sweeper is registered for kion_billing_source_govcloud:
// no resolvable collection endpoint: list envelope BillingSourceGovcloud holds no []BillingSourceGovcloud items field (read payload).
//
// A registered sweeper that returned nil would report success to `make sweep`
// while orphaned test-acc records accumulated, so none is registered at all.
// Clean these up by hand, or fix the generator input that blocks enumeration.
