// Code generated by kgen crud. DO NOT EDIT.

package webhook

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_webhook", &resource.Sweeper{
		Name: "kion_webhook",
		F:    sweepWebhook,
	})
}

func sweepWebhook(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_webhook resources with the "test-acc" prefix and
	// delete each.
	// A real sweeper needs both a resolvable collection endpoint and a delete op;
	// this resource is missing at least one (see the kgen crud run output).
	return nil
}
