# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_project_enforcement" "this" {
  amount_type            = var.amount_type
  cloud_rule_id          = var.cloud_rule_id
  description            = var.description
  enabled                = var.enabled
  notification_emails    = var.notification_emails
  notification_frequency = var.notification_frequency
  overburn               = var.overburn
  project_id             = var.project_id
  service_id             = var.service_id
  spend_option           = var.spend_option
  threshold              = var.threshold
  threshold_type         = var.threshold_type
  timeframe              = var.timeframe
  user_group_ids         = var.user_group_ids
  user_ids               = var.user_ids
}
