// Code generated by kgen crud. DO NOT EDIT.

package user

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_user", &resource.Sweeper{
		Name: "kion_user",
		F:    sweepUser,
	})
}

func sweepUser(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_user resources with the "test-acc" prefix and
	// delete each.
	// A real list+delete sweeper needs paginated-list-envelope resolution — see
	// the CRUD generator follow-up plan.
	return nil
}
