# Generated by `kgen module` from the provider schema. Do not edit.

output "create_user_id" {
  description = "create_user_id of the kion_project_note."
  value       = kion_project_note.this.create_user_id
}

output "create_user_name" {
  description = "create_user_name of the kion_project_note."
  value       = kion_project_note.this.create_user_name
}

output "created_at" {
  description = "created_at of the kion_project_note."
  value       = kion_project_note.this.created_at
}

output "id" {
  description = "id of the kion_project_note."
  value       = kion_project_note.this.id
}

output "last_update_user_id" {
  description = "last_update_user_id of the kion_project_note."
  value       = kion_project_note.this.last_update_user_id
}

output "last_update_user_name" {
  description = "last_update_user_name of the kion_project_note."
  value       = kion_project_note.this.last_update_user_name
}

output "updated_at" {
  description = "updated_at of the kion_project_note."
  value       = kion_project_note.this.updated_at
}
