# Generated by `kgen module` from the provider schema. Do not edit.

variable "create_user_id" {
  description = "ID of the user who created the note."
  type        = number
}

variable "name" {
  description = "Name of the note."
  type        = string
  default     = null
}

variable "project_id" {
  description = "ID of the project."
  type        = number
  default     = null
}

variable "text" {
  description = "Body text of the note."
  type        = string
  default     = null
}
