// Code generated by kgen crud. DO NOT EDIT.

// Package aws_account implements the Terraform resource and data source for aws_account.
package aws_account

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
	"terraform-provider-kion/internal/service/accounthelper"
)

// Resource name constant.
const (
	ResNameAwsAccount = "Aws Account"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &awsAccountResource{}
	_ resource.ResourceWithConfigure   = &awsAccountResource{}
	_ resource.ResourceWithImportState = &awsAccountResource{}
)

// NewAwsAccountResource returns a new instance of the resource.
func NewAwsAccountResource() resource.Resource {
	return &awsAccountResource{}
}

type awsAccountResource struct {
	framework.ResourceWithConfigure
}

func (r *awsAccountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_account"
}

// Schema is declared here rather than delegating to AwsAccountResourceSchema in
// aws_account_schema_gen.go, unlike every other resource. The generated schema is
// now accurate, it agrees with this one on all 28 attribute names and on their
// optional/computed/required flags, but three shapes cannot be expressed by the
// code generator, and each difference would break existing configurations:
//
//   - aws_organizational_unit and move_project_settings are nested *blocks* here
//     (`aws_organizational_unit { ... }`); tfplugingen-framework emits only nested
//     *attributes* (`aws_organizational_unit = { ... }`). That is a change to the
//     HCL a user writes, not just to the schema.
//   - id is Int64 here and String in the generated schema, so delegating would
//     change the type of a value already in every state file.
//
// Until the generator can emit blocks, this stays hand-written. The generated
// file is still produced and kept correct so docs and any future switchover have
// a faithful source; see codegen/schema_overrides.yaml, where account aliases
// aws_account's attributes because both resources render this one template.
func (r *awsAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Creates or imports an AWS Account and adds it to a Kion project or the Kion account cache.\n\n" +
			"If `account_number` is provided, an existing account will be imported into Kion, otherwise " +
			"a new AWS account will be created.  If `project_id` is provided the account will be added " +
			"to the corresponding project, otherwise the account will be added to the account cache.\n\n" +
			"Once added, an account can be moved between projects or in and out of the account cache by " +
			"changing the `project_id`.  When moving accounts between projects, use `move_project_settings` " +
			"to control how financials will be treated between the old and new project.\n\n" +
			"**NOTE:** This resource requires Kion v3.8.4 or greater.",
		Attributes: map[string]schema.Attribute{
			"account_alias": schema.StringAttribute{
				Description: "Account alias is an optional short unique name that helps identify the account within Kion.",
				Optional:    true,
			},
			"account_number": schema.StringAttribute{
				Description: "The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"account_type_id": schema.Int64Attribute{
				Description: "An ID representing the account type within Kion.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"car_external_id": schema.StringAttribute{
				Description: "The external ID used when assuming cloud access roles.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"commercial_account_name": schema.StringAttribute{
				Description: "The name used when creating new commercial account.",
				Optional:    true,
			},
			"create_govcloud": schema.BoolAttribute{
				Description: "True to create an AWS GovCloud account.",
				Optional:    true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"email": schema.StringAttribute{
				Description: "The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"gov_account_name": schema.StringAttribute{
				Description: "The name used when creating new GovCloud account.",
				Optional:    true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"include_linked_account_spend": schema.BoolAttribute{
				Description: "True to associate spend from a linked GovCloud account with this account.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.MapAttribute{
				Description: "A map of labels to assign to the account. The labels must already exist in Kion.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"last_updated": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"linked_account_number": schema.StringAttribute{
				Description: "For AWS GovCloud accounts, this is the linked commercial account.  Otherwise this is empty.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"linked_role": schema.StringAttribute{
				Description: "The AWS organization service role.",
				Optional:    true,
			},
			"location": schema.StringAttribute{
				Description: "Where the account is attached. Either \"project\" or \"cache\".",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "The name of the AWS account within Kion.",
				Required:    true,
			},
			"payer_id": schema.Int64Attribute{
				Description: "The ID of the billing source containing billing data for this account.",
				Required:    true,
			},
			"project_id": schema.Int64Attribute{
				Description: "The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.",
				Optional:    true,
			},
			"service_external_id": schema.StringAttribute{
				Description: "The external ID used for automated internal actions using the service role for this account.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"skip_access_checking": schema.BoolAttribute{
				Description: "True to skip periodic access checking on the account.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"start_datecode": schema.StringAttribute{
				Description: "Date when the AWS account will starting submitting payments against a funding source (YYYY-MM). Required if placing an account within a project.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"use_org_account_info": schema.BoolAttribute{
				Description: "True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"aws_organizational_unit": schema.SingleNestedBlock{
				Description: "Where to place this account within AWS Organization when creating an account.",
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Description: "Name of the organizational unit in AWS.",
						Optional:    true,
					},
					"org_unit_id": schema.StringAttribute{
						Description: "OUID of the AWS Organization unit.",
						Optional:    true,
					},
				},
			},
			"move_project_settings": schema.SingleNestedBlock{
				Description: "Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.",
				Attributes: map[string]schema.Attribute{
					"financials": schema.StringAttribute{
						Description: "One of \"move\" or \"preserve\".  If \"move\", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If \"preserve\", financial history will be preserved on the current project.",
						Optional:    true,
					},
					"move_datecode": schema.Int64Attribute{
						Description: "The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.",
						Optional:    true,
					},
				},
			},
		},
	}
	resp.Schema.Version = 1
}

func (r *awsAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan awsAccountResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hasProjectID := !plan.ProjectID.IsNull() && !plan.ProjectID.IsUnknown()
	hasAccountNumber := !plan.AccountNumber.IsNull() && !plan.AccountNumber.IsUnknown()

	if hasAccountNumber {
		// Import existing AWS account. The SDK doesn't have a dedicated
		// "import existing to cache" endpoint separate from "create new".
		// For now this path is not supported; users should use the create-new
		// path or terraform import.
		resp.Diagnostics.AddError(
			fmt.Sprintf("creating %s", ResNameAwsAccount),
			"Importing existing AWS accounts by account_number is not yet supported. "+
				"Use `terraform import` to bring an existing account under management.",
		)
		return
	}

	// Create a new AWS account in the cache.
	input := &generated.AWSAccountCacheNewAWSAccount{
		AccountName:               flex.StringValueFromFramework(plan.Name),
		AccountEmail:              flex.OptStringFromFramework(plan.Email),
		AccountAlias:              flex.OptStringFromFramework(plan.AccountAlias),
		AccountTypeID:             flex.OptNilUint64FromFramework(plan.AccountTypeID),
		CommercialAccountName:     flex.OptStringFromFramework(plan.CommercialAccountName),
		CreateGovcloud:            flex.OptNilBoolFromFramework(plan.CreateGovcloud),
		GovAccountName:            flex.OptStringFromFramework(plan.GovAccountName),
		IncludeLinkedAccountSpend: flex.OptNilBoolFromFramework(plan.IncludeLinkedAccountSpend),
		LinkedRole:                flex.OptStringFromFramework(plan.LinkedRole),
		PayerID:                   flex.NilUint64FromFramework(plan.PayerID),
	}

	if plan.AwsOrganizationalUnit != nil {
		input.OrganizationalUnit = generated.OptPayerOrganizationalUnit{
			Value: generated.PayerOrganizationalUnit{
				Name:      flex.OptStringFromFramework(plan.AwsOrganizationalUnit.Name),
				OrgUnitID: flex.OptStringFromFramework(plan.AwsOrganizationalUnit.OrgUnitID),
			},
			Set: true,
		}
	}

	out, err := conn.PostAccountCacheCreateNewAWS(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(
			fmt.Sprintf("creating %s", ResNameAwsAccount),
			err.Error(),
		)
		return
	}

	cacheID, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Wait for provisioning.
	resp.Diagnostics.Append(accounthelper.WaitForProvisioning(ctx, conn, cacheID)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if hasProjectID {
		// Convert cache → project.
		startDatecode := flex.StringValueFromFramework(plan.StartDatecode)
		result, diags := accounthelper.ConvertCacheToProject(
			ctx, conn, cacheID,
			flex.Int64ValueFromFramework(plan.ProjectID),
			startDatecode,
		)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}

		plan.ID = types.Int64Value(result.NewID)
		plan.Location = types.StringValue(result.Location)
	} else {
		plan.ID = types.Int64Value(cacheID)
		plan.Location = types.StringValue(accounthelper.LocationCache)
	}

	// Read back to populate computed fields.
	resp.Diagnostics.Append(r.readIntoModel(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *awsAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state awsAccountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, diags := accounthelper.ReadAccount(
		ctx,
		r.Meta().Client,
		state.ID.ValueInt64(),
		state.Location.ValueString(),
	)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if errs.IsNotFound(result.Response) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenAwsAccount(result.Response, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	state.Location = types.StringValue(result.Location)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *awsAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan awsAccountResourceModel
	var state awsAccountResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	currentID := state.ID.ValueInt64()
	currentLocation := state.Location.ValueString()

	// Detect project_id changes for conversion/move.
	oldProjectID := int64(0)
	if !state.ProjectID.IsNull() && !state.ProjectID.IsUnknown() {
		oldProjectID = state.ProjectID.ValueInt64()
	}
	newProjectID := int64(0)
	if !plan.ProjectID.IsNull() && !plan.ProjectID.IsUnknown() {
		newProjectID = plan.ProjectID.ValueInt64()
	}

	if oldProjectID != newProjectID {
		switch {
		case oldProjectID == 0 && newProjectID != 0:
			// Cache → Project
			result, diags := accounthelper.ConvertCacheToProject(
				ctx, conn, currentID, newProjectID,
				flex.StringValueFromFramework(plan.StartDatecode),
			)
			resp.Diagnostics.Append(diags...)
			if resp.Diagnostics.HasError() {
				return
			}
			currentID = result.NewID
			currentLocation = result.Location

		case oldProjectID != 0 && newProjectID == 0:
			// Project → Cache
			result, diags := accounthelper.ConvertProjectToCache(ctx, conn, currentID)
			resp.Diagnostics.Append(diags...)
			if resp.Diagnostics.HasError() {
				return
			}
			currentID = result.NewID
			currentLocation = result.Location

		case oldProjectID != 0 && newProjectID != 0:
			// Project → Different Project
			financials := ""
			moveDatecode := int64(0)
			if plan.MoveProjectSettings != nil {
				financials = flex.StringValueFromFramework(plan.MoveProjectSettings.Financials)
				moveDatecode = flex.Int64ValueFromFramework(plan.MoveProjectSettings.MoveDatecode)
			}
			result, diags := accounthelper.MoveAccountBetweenProjects(
				ctx, conn, currentID, uint64(newProjectID),
				financials, moveDatecode,
			)
			resp.Diagnostics.Append(diags...)
			if resp.Diagnostics.HasError() {
				return
			}
			currentID = result.NewID
			currentLocation = result.Location
		}
	}

	// Update mutable fields.
	switch currentLocation {
	case accounthelper.LocationProject:
		input := &generated.AccountUpdatable{
			AccountName:               flex.OptStringFromFramework(plan.Name),
			AccountAlias:              flex.OptStringFromFramework(plan.AccountAlias),
			AccountEmail:              flex.OptStringFromFramework(plan.Email),
			IncludeLinkedAccountSpend: flex.OptNilBoolFromFramework(plan.IncludeLinkedAccountSpend),
			LinkedRole:                flex.OptStringFromFramework(plan.LinkedRole),
			SkipAccessChecking:        flex.OptNilBoolFromFramework(plan.SkipAccessChecking),
			StartDatecode:             flex.OptStringFromFramework(plan.StartDatecode),
			UseOrgAccountInfo:         flex.OptNilBoolFromFramework(plan.UseOrgAccountInfo),
		}
		out, err := conn.PatchAccount(ctx, input, generated.PatchAccountParams{ID: currentID})
		if err != nil {
			resp.Diagnostics.AddError(
				fmt.Sprintf("updating %s (ID: %d)", ResNameAwsAccount, currentID),
				err.Error(),
			)
			return
		}
		resp.Diagnostics.Append(errs.ResponseDiagnostics(
			fmt.Sprintf("updating %s", ResNameAwsAccount), out,
		)...)
		if resp.Diagnostics.HasError() {
			return
		}

	case accounthelper.LocationCache:
		input := &generated.AccountCacheUpdatable{
			AccountName:               flex.OptStringFromFramework(plan.Name),
			AccountAlias:              flex.OptStringFromFramework(plan.AccountAlias),
			AccountEmail:              flex.OptStringFromFramework(plan.Email),
			IncludeLinkedAccountSpend: flex.OptNilBoolFromFramework(plan.IncludeLinkedAccountSpend),
			LinkedRole:                flex.OptStringFromFramework(plan.LinkedRole),
			SkipAccessChecking:        flex.OptNilBoolFromFramework(plan.SkipAccessChecking),
		}
		out, err := conn.PatchAccountCache(ctx, input, generated.PatchAccountCacheParams{ID: currentID})
		if err != nil {
			resp.Diagnostics.AddError(
				fmt.Sprintf("updating %s cache (ID: %d)", ResNameAwsAccount, currentID),
				err.Error(),
			)
			return
		}
		resp.Diagnostics.Append(errs.ResponseDiagnostics(
			fmt.Sprintf("updating %s cache", ResNameAwsAccount), out,
		)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}

	// Update plan with new ID/location and read back.
	plan.ID = types.Int64Value(currentID)
	plan.Location = types.StringValue(currentLocation)

	resp.Diagnostics.Append(r.readIntoModel(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *awsAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state awsAccountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(accounthelper.DeleteAccount(
		ctx,
		r.Meta().Client,
		state.ID.ValueInt64(),
		state.Location.ValueString(),
	)...)
}

func (r *awsAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importID := req.ID

	// Support prefixed import: "account_id=123" or "account_cache_id=123"
	var id int64
	var location string

	switch {
	case strings.HasPrefix(importID, "account_id="):
		raw := strings.TrimPrefix(importID, "account_id=")
		parsed, diags := framework.StringToInt64(raw)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		id = parsed
		location = accounthelper.LocationProject

	case strings.HasPrefix(importID, "account_cache_id="):
		raw := strings.TrimPrefix(importID, "account_cache_id=")
		parsed, diags := framework.StringToInt64(raw)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		id = parsed
		location = accounthelper.LocationCache

	default:
		// No prefix, auto-detect by trying both endpoints.
		parsed, diags := framework.StringToInt64(importID)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}

		result, diags := accounthelper.ReadAccountForImport(ctx, r.Meta().Client, parsed)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		id = parsed
		location = result.Location
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("location"), location)...)
}

// readIntoModel reads the account back from the API and updates computed fields
// in the model. The model's ID and Location must already be set.
func (r *awsAccountResource) readIntoModel(ctx context.Context, model *awsAccountResourceModel) diag.Diagnostics {
	result, diags := accounthelper.ReadAccount(
		ctx,
		r.Meta().Client,
		model.ID.ValueInt64(),
		model.Location.ValueString(),
	)
	if diags.HasError() {
		return diags
	}

	diags.Append(flattenAwsAccount(result.Response, model)...)
	return diags
}

func flattenAwsAccount(apiObject any, model *awsAccountResourceModel) diag.Diagnostics {
	switch v := apiObject.(type) {
	case *generated.AccountResponse:
		if v.Data.Set {
			a := v.Data.Value
			model.ID = flex.OptUint64ToFramework(a.ID)
			model.AccountAlias = flex.OptStringToFrameworkNullIfEmpty(a.AccountAlias)
			model.AccountNumber = flex.OptStringToFrameworkNullIfEmpty(a.AccountNumber)
			model.AccountTypeID = flex.OptNilUint64ToFramework(a.AccountTypeID)
			model.CarExternalID = flex.OptStringToFrameworkNullIfEmpty(a.CarExternalID)
			model.CreatedAt = flex.OptStringToFrameworkNullIfEmpty(a.CreatedAt)
			model.Email = flex.OptStringToFrameworkNullIfEmpty(a.AccountEmail)
			model.IncludeLinkedAccountSpend = flex.OptNilBoolToFramework(a.IncludeLinkedAccountSpend)
			model.LinkedAccountNumber = flex.OptStringToFrameworkNullIfEmpty(a.LinkedAccountNumber)
			model.LinkedRole = flex.OptStringToFrameworkNullIfEmpty(a.LinkedRole)
			model.Name = flex.OptStringToFrameworkNullIfEmpty(a.AccountName)
			model.PayerID = flex.OptNilUint64ToFramework(a.PayerID)
			model.ProjectID = flex.OptNilUint64ToFramework(a.ProjectID)
			model.ServiceExternalID = flex.OptStringToFrameworkNullIfEmpty(a.ServiceExternalID)
			model.SkipAccessChecking = flex.OptNilBoolToFramework(a.SkipAccessChecking)
			model.StartDatecode = flex.OptStringToFrameworkNullIfEmpty(a.StartDatecode)
			model.UseOrgAccountInfo = flex.OptNilBoolToFramework(a.UseOrgAccountInfo)
			model.Location = types.StringValue(accounthelper.LocationProject)
		}
		return nil

	case *generated.AccountCacheResponse:
		if v.Data.Set {
			a := v.Data.Value
			model.ID = flex.OptUint64ToFramework(a.ID)
			model.AccountAlias = flex.OptStringToFrameworkNullIfEmpty(a.AccountAlias)
			model.AccountNumber = flex.OptStringToFrameworkNullIfEmpty(a.AccountNumber)
			model.AccountTypeID = flex.OptNilUint64ToFramework(a.AccountTypeID)
			model.CarExternalID = flex.OptStringToFrameworkNullIfEmpty(a.CarExternalID)
			model.CreatedAt = flex.OptStringToFrameworkNullIfEmpty(a.CreatedAt)
			model.Email = flex.OptStringToFrameworkNullIfEmpty(a.AccountEmail)
			model.IncludeLinkedAccountSpend = flex.OptNilBoolToFramework(a.IncludeLinkedAccountSpend)
			model.LinkedAccountNumber = flex.OptStringToFrameworkNullIfEmpty(a.LinkedAccountNumber)
			model.LinkedRole = flex.OptStringToFrameworkNullIfEmpty(a.LinkedRole)
			model.Name = flex.OptStringToFrameworkNullIfEmpty(a.AccountName)
			model.PayerID = flex.OptNilUint64ToFramework(a.PayerID)
			model.ServiceExternalID = flex.OptStringToFrameworkNullIfEmpty(a.ServiceExternalID)
			model.SkipAccessChecking = flex.OptNilBoolToFramework(a.SkipAccessChecking)
			model.Location = types.StringValue(accounthelper.LocationCache)
		}
		return nil

	default:
		return errs.ResponseDiagnostics("reading "+ResNameAwsAccount, apiObject)
	}
}

type awsAccountResourceModel struct {
	AccountAlias              types.String                `tfsdk:"account_alias"`
	AccountNumber             types.String                `tfsdk:"account_number"`
	AccountTypeID             types.Int64                 `tfsdk:"account_type_id"`
	AwsOrganizationalUnit     *awsOrganizationalUnitModel `tfsdk:"aws_organizational_unit"`
	CarExternalID             types.String                `tfsdk:"car_external_id"`
	CommercialAccountName     types.String                `tfsdk:"commercial_account_name"`
	CreateGovcloud            types.Bool                  `tfsdk:"create_govcloud"`
	CreatedAt                 types.String                `tfsdk:"created_at"`
	Email                     types.String                `tfsdk:"email"`
	GovAccountName            types.String                `tfsdk:"gov_account_name"`
	ID                        types.Int64                 `tfsdk:"id"`
	IncludeLinkedAccountSpend types.Bool                  `tfsdk:"include_linked_account_spend"`
	Labels                    types.Map                   `tfsdk:"labels"`
	LastUpdated               types.String                `tfsdk:"last_updated"`
	LinkedAccountNumber       types.String                `tfsdk:"linked_account_number"`
	LinkedRole                types.String                `tfsdk:"linked_role"`
	Location                  types.String                `tfsdk:"location"`
	MoveProjectSettings       *moveProjectSettingsModel   `tfsdk:"move_project_settings"`
	Name                      types.String                `tfsdk:"name"`
	PayerID                   types.Int64                 `tfsdk:"payer_id"`
	ProjectID                 types.Int64                 `tfsdk:"project_id"`
	ServiceExternalID         types.String                `tfsdk:"service_external_id"`
	SkipAccessChecking        types.Bool                  `tfsdk:"skip_access_checking"`
	StartDatecode             types.String                `tfsdk:"start_datecode"`
	UseOrgAccountInfo         types.Bool                  `tfsdk:"use_org_account_info"`
}

type awsOrganizationalUnitModel struct {
	Name      types.String `tfsdk:"name"`
	OrgUnitID types.String `tfsdk:"org_unit_id"`
}

type moveProjectSettingsModel struct {
	Financials   types.String `tfsdk:"financials"`
	MoveDatecode types.Int64  `tfsdk:"move_datecode"`
}
