// Code generated by kgen migrate. DO NOT EDIT.

package aws_account

import (
	"context"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

// TestUpgradeState_decodes feeds a representative old (SDKv2) state through the
// v0 upgrader and asserts it decodes cleanly against the current schema — the
// per-resource guarantee that the generated old→new mapping fits the real
// schema (no missing/extra/mistyped key). The fixture is synthesized from the
// old schema snapshot + codegen/state_upgrades.yaml. Transform value-correctness
// is covered by internal/migratehelper unit tests and the deep goldens.
func TestUpgradeState_decodes(t *testing.T) {
	ctx := context.Background()
	r := &awsAccountResource{}
	up, ok := r.UpgradeState(ctx)[0]
	if !ok {
		t.Fatal("no v0 upgrader")
	}

	oldState := `{
		"aws_organizational_unit": [],
		"id": "1234",
		"move_project_settings": []
	}`

	var sr resource.SchemaResponse
	r.Schema(ctx, resource.SchemaRequest{}, &sr)
	req := resource.UpgradeStateRequest{RawState: &tfprotov6.RawState{JSON: []byte(oldState)}}
	resp := &resource.UpgradeStateResponse{State: tfsdk.State{Schema: sr.Schema}}
	up.StateUpgrader(ctx, req, resp)
	if resp.Diagnostics.HasError() {
		t.Fatalf("upgrade diagnostics: %v", resp.Diagnostics)
	}
	if resp.State.Raw.IsNull() {
		t.Fatal("upgraded state decoded to null")
	}
}
