// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package idms_open_id

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func IdmsOpenIdResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_rules": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"assertion_name": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "AssertionName name of the assertion in OpenID.",
							MarkdownDescription: "AssertionName name of the assertion in OpenID.",
						},
						"assertion_regex": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "AssertionRegex is the regular expression used to determine a match.",
							MarkdownDescription: "AssertionRegex is the regular expression used to determine a match.",
						},
						"cloudtamer_access_level_id": schema.Int64Attribute{
							Optional:            true,
							Computed:            true,
							Description:         "CloudtamerAccessLevelID is the ID that represents access level. 1 represents full access, 2 represents no cloud account access and 3 represents no access.",
							MarkdownDescription: "CloudtamerAccessLevelID is the ID that represents access level. 1 represents full access, 2 represents no cloud account access and 3 represents no access.",
						},
					},
					CustomType: AccessRulesType{
						ObjectType: types.ObjectType{
							AttrTypes: AccessRulesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "AccessRules defines the console access defined for matching users in Kion",
				MarkdownDescription: "AccessRules defines the console access defined for matching users in Kion",
			},
			"authorization_endpoint": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "AuthorizationEndpoint is the endpoint the OpenID provider determines to kick off the authentication process",
				MarkdownDescription: "AuthorizationEndpoint is the endpoint the OpenID provider determines to kick off the authentication process",
			},
			"client_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ClientID that links Kion to the OpenID Provider, determined when configuring OpenID",
				MarkdownDescription: "ClientID that links Kion to the OpenID Provider, determined when configuring OpenID",
			},
			"email_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "EmailClaim defines an optional mapping of an OpenID claim value to a user's email attribute in Kion",
				MarkdownDescription: "EmailClaim defines an optional mapping of an OpenID claim value to a user's email attribute in Kion",
			},
			"first_name_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "FirstNameClaim defines an optional mapping of an OpenID claim value to a user's first name attribute in Kion",
				MarkdownDescription: "FirstNameClaim defines an optional mapping of an OpenID claim value to a user's first name attribute in Kion",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "OpenID IDMS ID.",
				MarkdownDescription: "OpenID IDMS ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"issuer": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Issuer is the URL for the OpenID Provider",
				MarkdownDescription: "Issuer is the URL for the OpenID Provider",
			},
			"jwks_uri": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "JwksURI describes the endpoint of an OpenID provider used to retrieve token security information for validation",
				MarkdownDescription: "JwksURI describes the endpoint of an OpenID provider used to retrieve token security information for validation",
			},
			"last_name_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "LastNameClaim defines an optional mapping of an OpenID claim value to a user's last name attribute in Kion",
				MarkdownDescription: "LastNameClaim defines an optional mapping of an OpenID claim value to a user's last name attribute in Kion",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the OpenID in the application.",
				MarkdownDescription: "Name of the OpenID in the application.",
			},
			"phone_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "PhoneClaim defines an optional mapping of an OpenID claim value to a user's phone attribute in Kion",
				MarkdownDescription: "PhoneClaim defines an optional mapping of an OpenID claim value to a user's phone attribute in Kion",
			},
			"scopes": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Scopes define the claim variables that an OpenID provider will include in an auth request. Specifics depend on the OpenID provider.",
				MarkdownDescription: "Scopes define the claim variables that an OpenID provider will include in an auth request. Specifics depend on the OpenID provider.",
			},
			"username_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "UsernameClaim defines an optional mapping of an OpenID claim value to a user's username attribute in Kion. Required to uniquely identify users",
				MarkdownDescription: "UsernameClaim defines an optional mapping of an OpenID claim value to a user's username attribute in Kion. Required to uniquely identify users",
			},
		},
		Description: "Manages a Kion OpenID Connect identity management system (IDMS).",
	}
}

type IdmsOpenIdModel struct {
	AccessRules           types.List   `tfsdk:"access_rules"`
	AuthorizationEndpoint types.String `tfsdk:"authorization_endpoint"`
	ClientId              types.String `tfsdk:"client_id"`
	EmailClaim            types.String `tfsdk:"email_claim"`
	FirstNameClaim        types.String `tfsdk:"first_name_claim"`
	Id                    types.String `tfsdk:"id"`
	Issuer                types.String `tfsdk:"issuer"`
	JwksUri               types.String `tfsdk:"jwks_uri"`
	LastNameClaim         types.String `tfsdk:"last_name_claim"`
	Name                  types.String `tfsdk:"name"`
	PhoneClaim            types.String `tfsdk:"phone_claim"`
	Scopes                types.List   `tfsdk:"scopes"`
	UsernameClaim         types.String `tfsdk:"username_claim"`
}

var _ basetypes.ObjectTypable = AccessRulesType{}

type AccessRulesType struct {
	basetypes.ObjectType
}

func (t AccessRulesType) Equal(o attr.Type) bool {
	other, ok := o.(AccessRulesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccessRulesType) String() string {
	return "AccessRulesType"
}

func (t AccessRulesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	assertionNameAttribute, ok := attributes["assertion_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assertion_name is missing from object`)

		return nil, diags
	}

	assertionNameVal, ok := assertionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assertion_name expected to be basetypes.StringValue, was: %T`, assertionNameAttribute))
	}

	assertionRegexAttribute, ok := attributes["assertion_regex"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assertion_regex is missing from object`)

		return nil, diags
	}

	assertionRegexVal, ok := assertionRegexAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assertion_regex expected to be basetypes.StringValue, was: %T`, assertionRegexAttribute))
	}

	cloudtamerAccessLevelIdAttribute, ok := attributes["cloudtamer_access_level_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloudtamer_access_level_id is missing from object`)

		return nil, diags
	}

	cloudtamerAccessLevelIdVal, ok := cloudtamerAccessLevelIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloudtamer_access_level_id expected to be basetypes.Int64Value, was: %T`, cloudtamerAccessLevelIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccessRulesValue{
		AssertionName:           assertionNameVal,
		AssertionRegex:          assertionRegexVal,
		CloudtamerAccessLevelId: cloudtamerAccessLevelIdVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewAccessRulesValueNull() AccessRulesValue {
	return AccessRulesValue{
		state: attr.ValueStateNull,
	}
}

func NewAccessRulesValueUnknown() AccessRulesValue {
	return AccessRulesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccessRulesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccessRulesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccessRulesValue Attribute Value",
				"While creating a AccessRulesValue value, a missing attribute value was detected. "+
					"A AccessRulesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccessRulesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccessRulesValue Attribute Type",
				"While creating a AccessRulesValue value, an invalid attribute value was detected. "+
					"A AccessRulesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccessRulesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccessRulesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccessRulesValue Attribute Value",
				"While creating a AccessRulesValue value, an extra attribute value was detected. "+
					"A AccessRulesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccessRulesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccessRulesValueUnknown(), diags
	}

	assertionNameAttribute, ok := attributes["assertion_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assertion_name is missing from object`)

		return NewAccessRulesValueUnknown(), diags
	}

	assertionNameVal, ok := assertionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assertion_name expected to be basetypes.StringValue, was: %T`, assertionNameAttribute))
	}

	assertionRegexAttribute, ok := attributes["assertion_regex"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assertion_regex is missing from object`)

		return NewAccessRulesValueUnknown(), diags
	}

	assertionRegexVal, ok := assertionRegexAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assertion_regex expected to be basetypes.StringValue, was: %T`, assertionRegexAttribute))
	}

	cloudtamerAccessLevelIdAttribute, ok := attributes["cloudtamer_access_level_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloudtamer_access_level_id is missing from object`)

		return NewAccessRulesValueUnknown(), diags
	}

	cloudtamerAccessLevelIdVal, ok := cloudtamerAccessLevelIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloudtamer_access_level_id expected to be basetypes.Int64Value, was: %T`, cloudtamerAccessLevelIdAttribute))
	}

	if diags.HasError() {
		return NewAccessRulesValueUnknown(), diags
	}

	return AccessRulesValue{
		AssertionName:           assertionNameVal,
		AssertionRegex:          assertionRegexVal,
		CloudtamerAccessLevelId: cloudtamerAccessLevelIdVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewAccessRulesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccessRulesValue {
	object, diags := NewAccessRulesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccessRulesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccessRulesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccessRulesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccessRulesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccessRulesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccessRulesValueMust(AccessRulesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccessRulesType) ValueType(ctx context.Context) attr.Value {
	return AccessRulesValue{}
}

var _ basetypes.ObjectValuable = AccessRulesValue{}

type AccessRulesValue struct {
	AssertionName           basetypes.StringValue `tfsdk:"assertion_name"`
	AssertionRegex          basetypes.StringValue `tfsdk:"assertion_regex"`
	CloudtamerAccessLevelId basetypes.Int64Value  `tfsdk:"cloudtamer_access_level_id"`
	state                   attr.ValueState
}

func (v AccessRulesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["assertion_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["assertion_regex"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cloudtamer_access_level_id"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.AssertionName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["assertion_name"] = val

		val, err = v.AssertionRegex.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["assertion_regex"] = val

		val, err = v.CloudtamerAccessLevelId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cloudtamer_access_level_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccessRulesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccessRulesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccessRulesValue) String() string {
	return "AccessRulesValue"
}

func (v AccessRulesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"assertion_name":             basetypes.StringType{},
		"assertion_regex":            basetypes.StringType{},
		"cloudtamer_access_level_id": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"assertion_name":             v.AssertionName,
			"assertion_regex":            v.AssertionRegex,
			"cloudtamer_access_level_id": v.CloudtamerAccessLevelId,
		})

	return objVal, diags
}

func (v AccessRulesValue) Equal(o attr.Value) bool {
	other, ok := o.(AccessRulesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AssertionName.Equal(other.AssertionName) {
		return false
	}

	if !v.AssertionRegex.Equal(other.AssertionRegex) {
		return false
	}

	if !v.CloudtamerAccessLevelId.Equal(other.CloudtamerAccessLevelId) {
		return false
	}

	return true
}

func (v AccessRulesValue) Type(ctx context.Context) attr.Type {
	return AccessRulesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccessRulesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"assertion_name":             basetypes.StringType{},
		"assertion_regex":            basetypes.StringType{},
		"cloudtamer_access_level_id": basetypes.Int64Type{},
	}
}
