// Code generated by kgen crud. DO NOT EDIT.

package idms_open_id

// No acceptance-test sweeper is registered for kion_idms_open_id:
// no resolvable collection endpoint: list envelope OpenID holds no []OpenID items field (read payload).
//
// A registered sweeper that returned nil would report success to `make sweep`
// while orphaned test-acc records accumulated, so none is registered at all.
// Clean these up by hand, or fix the generator input that blocks enumeration.
