# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_project_cloud_access_role" "this" {
  account_ids                  = var.account_ids
  apply_to_all_accounts        = var.apply_to_all_accounts
  aws_create_instance_profile  = var.aws_create_instance_profile
  aws_iam_path                 = var.aws_iam_path
  aws_iam_permissions_boundary = var.aws_iam_permissions_boundary
  aws_iam_policies             = var.aws_iam_policies
  aws_iam_role_name            = var.aws_iam_role_name
  aws_iam_role_trust_policy    = var.aws_iam_role_trust_policy
  aws_partition                = var.aws_partition
  aws_session_tags             = var.aws_session_tags
  aws_trusted_account_numbers  = var.aws_trusted_account_numbers
  aws_trusted_services         = var.aws_trusted_services
  azure_role_definitions       = var.azure_role_definitions
  cloud_access_role_type_id    = var.cloud_access_role_type_id
  cloud_provider_ids           = var.cloud_provider_ids
  future_accounts              = var.future_accounts
  gcp_iam_roles                = var.gcp_iam_roles
  long_term_access_keys        = var.long_term_access_keys
  name                         = var.name
  project_id                   = var.project_id
  short_term_access_keys       = var.short_term_access_keys
  user_group_ids               = var.user_group_ids
  user_ids                     = var.user_ids
  web_access                   = var.web_access
}
