// Code generated by kgen crud. DO NOT EDIT.

package project_cloud_access_role_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionProjectCloudAccessRole_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_project_cloud_access_role.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckProjectCloudAccessRoleDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccProjectCloudAccessRoleConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckProjectCloudAccessRoleExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "apply_to_all_accounts", "true"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "project_id"),
					resource.TestCheckResourceAttr(resourceName, "short_term_access_keys", "true"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
					resource.TestCheckResourceAttr(resourceName, "web_access", "true"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionProjectCloudAccessRole_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_project_cloud_access_role.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckProjectCloudAccessRoleDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccProjectCloudAccessRoleConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckProjectCloudAccessRoleExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "apply_to_all_accounts", "true"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "project_id"),
					resource.TestCheckResourceAttr(resourceName, "short_term_access_keys", "true"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
					resource.TestCheckResourceAttr(resourceName, "web_access", "true"),
				),
			},
			{
				Config: testAccProjectCloudAccessRoleConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckProjectCloudAccessRoleExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "apply_to_all_accounts", "true"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "project_id"),
					resource.TestCheckResourceAttr(resourceName, "short_term_access_keys", "false"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
					resource.TestCheckResourceAttr(resourceName, "web_access", "true"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckProjectCloudAccessRoleExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		out, err := conn.Client.GetProjectCloudAccessRole(ctx, generated.GetProjectCloudAccessRoleParams{ID: id})
		if err != nil {
			return fmt.Errorf("reading kion_project_cloud_access_role (%d): %w", id, err)
		}
		if errs.IsNotFound(out) {
			return fmt.Errorf("kion_project_cloud_access_role (%d) not found", id)
		}

		return nil
	}
}

func testAccCheckProjectCloudAccessRoleDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_project_cloud_access_role" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			out, err := conn.Client.GetProjectCloudAccessRole(ctx, generated.GetProjectCloudAccessRoleParams{ID: id})
			if errs.IsNotFound(out) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_project_cloud_access_role (%d): %w", id, err)
			}

			return fmt.Errorf("kion_project_cloud_access_role (%d) still exists", id)
		}

		return nil
	}
}

func testAccProjectCloudAccessRoleConfig_basic(rName string) string {
	return fmt.Sprintf(`
resource "kion_permission_scheme" "test_perm" {
  name = "%[1]s-perm"
  type = "ou"
}
resource "kion_ou" "test_ou" {
  name                 = "%[1]s-ou"
  parent_ou_id         = 0
  permission_scheme_id = kion_permission_scheme.test_perm.id
  owner_user_ids       = [1]
}
resource "kion_permission_scheme" "test_perm_project" {
  name = "%[1]s-perm-project"
  type = "project"
}
resource "kion_project" "test_project" {
  name                 = "%[1]s-project"
  ou_id                = kion_ou.test_ou.id
  permission_scheme_id = kion_permission_scheme.test_perm_project.id
  owner_user_ids       = [1]
}

resource "kion_project_cloud_access_role" "test" {
  apply_to_all_accounts = true
  name = "%[1]s"
  project_id = kion_project.test_project.id
  short_term_access_keys = true
  user_ids = [1]
  web_access = true
}
`, rName)
}

func testAccProjectCloudAccessRoleConfig_update(rName string) string {
	return fmt.Sprintf(`
resource "kion_permission_scheme" "test_perm" {
  name = "%[1]s-perm"
  type = "ou"
}
resource "kion_ou" "test_ou" {
  name                 = "%[1]s-ou"
  parent_ou_id         = 0
  permission_scheme_id = kion_permission_scheme.test_perm.id
  owner_user_ids       = [1]
}
resource "kion_permission_scheme" "test_perm_project" {
  name = "%[1]s-perm-project"
  type = "project"
}
resource "kion_project" "test_project" {
  name                 = "%[1]s-project"
  ou_id                = kion_ou.test_ou.id
  permission_scheme_id = kion_permission_scheme.test_perm_project.id
  owner_user_ids       = [1]
}

resource "kion_project_cloud_access_role" "test" {
  apply_to_all_accounts = true
  name = "%[1]s"
  project_id = kion_project.test_project.id
  short_term_access_keys = false
  user_ids = [1]
  web_access = true
}
`, rName)
}
