# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_custom_variable_override" "this" {
  custom_variable_id = var.custom_variable_id
  entity_id          = var.entity_id
  entity_type        = var.entity_type
  value_list         = var.value_list
  value_map          = var.value_map
  value_string       = var.value_string
}
