// Code generated by kgen crud. DO NOT EDIT.

package account

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/framework"
)

// Data source name constant.
const (
	DSNameAccount = "Account Data Source"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &accountDataSource{}
	_ datasource.DataSourceWithConfigure = &accountDataSource{}
)

// accountListObjectAttrTypes is the schema of an entry inside the `list` attribute.
var accountListObjectAttrTypes = map[string]attr.Type{
	"account_alias":                types.StringType,
	"account_number":               types.StringType,
	"account_type_id":              types.Int64Type,
	"car_external_id":              types.StringType,
	"created_at":                   types.StringType,
	"email":                        types.StringType,
	"id":                           types.Int64Type,
	"include_linked_account_spend": types.BoolType,
	"linked_account_number":        types.StringType,
	"linked_role":                  types.StringType,
	"name":                         types.StringType,
	"payer_id":                     types.Int64Type,
	"project_id":                   types.Int64Type,
	"service_external_id":          types.StringType,
	"skip_access_checking":         types.BoolType,
	"start_datecode":               types.StringType,
	"use_org_account_info":         types.BoolType,
}

// NewAccountDataSource returns a new instance of the data source.
func NewAccountDataSource() datasource.DataSource {
	return &accountDataSource{}
}

type accountDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *accountDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account"
}

func (d *accountDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion Accounts. Returns every account matching the supplied filter blocks (all accounts when no filter is given).",
		Attributes: map[string]schema.Attribute{
			"list": schema.ListNestedAttribute{
				Description: "This is where Kion makes the discovered data available as a list of resources.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"account_alias":                schema.StringAttribute{Computed: true},
						"account_number":               schema.StringAttribute{Computed: true},
						"account_type_id":              schema.Int64Attribute{Computed: true},
						"car_external_id":              schema.StringAttribute{Computed: true},
						"created_at":                   schema.StringAttribute{Computed: true},
						"email":                        schema.StringAttribute{Computed: true},
						"id":                           schema.Int64Attribute{Computed: true},
						"include_linked_account_spend": schema.BoolAttribute{Computed: true},
						"linked_account_number":        schema.StringAttribute{Computed: true},
						"linked_role":                  schema.StringAttribute{Computed: true},
						"name":                         schema.StringAttribute{Computed: true},
						"payer_id":                     schema.Int64Attribute{Computed: true},
						"project_id":                   schema.Int64Attribute{Computed: true},
						"service_external_id":          schema.StringAttribute{Computed: true},
						"skip_access_checking":         schema.BoolAttribute{Computed: true},
						"start_datecode":               schema.StringAttribute{Computed: true},
						"use_org_account_info":         schema.BoolAttribute{Computed: true},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *accountDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data accountDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := conn.GetAccountIndex(ctx, generated.GetAccountIndexParams{})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("listing %s", DSNameAccount), err.Error())
		return
	}
	api, ok := out.(*generated.AccountListResponse)
	if !ok {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("listing "+DSNameAccount, out)...)
		return
	}

	matched := make([]generated.Account, 0, len(api.Data))
	for _, a := range api.Data {
		keep, matchDiags := filter.Match(ctx, data.Filter, accountToRow(a))
		resp.Diagnostics.Append(matchDiags...)
		if resp.Diagnostics.HasError() {
			return
		}
		if keep {
			matched = append(matched, a)
		}
	}

	listVal, listDiags := buildAccountList(ctx, matched)
	resp.Diagnostics.Append(listDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.List = listVal

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// accountToRow converts an account into the map filter.Match expects.
func accountToRow(a generated.Account) map[string]any {
	row := map[string]any{
		"account_alias":         a.AccountAlias.Value,
		"account_number":        a.AccountNumber.Value,
		"car_external_id":       a.CarExternalID.Value,
		"created_at":            a.CreatedAt.Value,
		"email":                 a.AccountEmail.Value,
		"linked_account_number": a.LinkedAccountNumber.Value,
		"linked_role":           a.LinkedRole.Value,
		"name":                  a.AccountName.Value,
		"service_external_id":   a.ServiceExternalID.Value,
		"start_datecode":        a.StartDatecode.Value,
	}
	if a.ID.Set {
		row["id"] = int64(a.ID.Value)
	}
	if a.AccountTypeID.Set {
		row["account_type_id"] = int64(a.AccountTypeID.Value)
	}
	if a.PayerID.Set {
		row["payer_id"] = int64(a.PayerID.Value)
	}
	if a.ProjectID.Set {
		row["project_id"] = int64(a.ProjectID.Value)
	}
	return row
}

// buildAccountList converts accounts into a types.List of objects.
func buildAccountList(ctx context.Context, items []generated.Account) (types.List, diag.Diagnostics) {
	objType := types.ObjectType{AttrTypes: accountListObjectAttrTypes}
	objs := make([]attr.Value, 0, len(items))
	for _, a := range items {
		obj, objDiags := types.ObjectValue(accountListObjectAttrTypes, map[string]attr.Value{
			"account_alias":                accountOptString(a.AccountAlias),
			"account_number":               accountOptString(a.AccountNumber),
			"account_type_id":              accountOptNilUint64(a.AccountTypeID),
			"car_external_id":              accountOptString(a.CarExternalID),
			"created_at":                   accountOptString(a.CreatedAt),
			"email":                        accountOptString(a.AccountEmail),
			"id":                           accountOptUint64(a.ID),
			"include_linked_account_spend": accountOptNilBool(a.IncludeLinkedAccountSpend),
			"linked_account_number":        accountOptString(a.LinkedAccountNumber),
			"linked_role":                  accountOptString(a.LinkedRole),
			"name":                         accountOptString(a.AccountName),
			"payer_id":                     accountOptNilUint64(a.PayerID),
			"project_id":                   accountOptNilUint64(a.ProjectID),
			"service_external_id":          accountOptString(a.ServiceExternalID),
			"skip_access_checking":         accountOptNilBool(a.SkipAccessChecking),
			"start_datecode":               accountOptString(a.StartDatecode),
			"use_org_account_info":         accountOptNilBool(a.UseOrgAccountInfo),
		})
		if objDiags.HasError() {
			return types.ListNull(objType), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, objType, objs)
}

func accountOptString(v generated.OptString) attr.Value {
	if !v.Set {
		return types.StringNull()
	}
	return types.StringValue(v.Value)
}

func accountOptUint64(v generated.OptUint64) attr.Value {
	if !v.Set {
		return types.Int64Null()
	}
	return types.Int64Value(int64(v.Value))
}

func accountOptNilUint64(v generated.OptNilUint64) attr.Value {
	if !v.Set || v.Null {
		return types.Int64Null()
	}
	return types.Int64Value(int64(v.Value))
}

func accountOptNilBool(v generated.OptNilBool) attr.Value {
	if !v.Set || v.Null {
		return types.BoolNull()
	}
	return types.BoolValue(v.Value)
}

type accountDataSourceModel struct {
	Filter []filter.Model `tfsdk:"filter"`
	List   types.List     `tfsdk:"list"`
}
