# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_scope_criteria" "this" {
  criteria    = var.criteria
  end_month   = var.end_month
  scope_id    = var.scope_id
  start_month = var.start_month
}
