# Generated by `kgen module` from the provider schema. Do not edit.

variable "config" {
  description = "JSON configuration (cards"
  type        = string
  default     = null
}

variable "description" {
  description = "Description of the dashboard."
  type        = string
  default     = null
}

variable "is_default" {
  description = "Whether this is the default dashboard."
  type        = bool
  default     = null
}

variable "name" {
  description = "Name of the dashboard."
  type        = string
  default     = null
}
