# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_idms_open_id" "this" {
  access_rules           = var.access_rules
  authorization_endpoint = var.authorization_endpoint
  client_id              = var.client_id
  email_claim            = var.email_claim
  first_name_claim       = var.first_name_claim
  issuer                 = var.issuer
  jwks_uri               = var.jwks_uri
  last_name_claim        = var.last_name_claim
  name                   = var.name
  phone_claim            = var.phone_claim
  scopes                 = var.scopes
  username_claim         = var.username_claim
}
