# Generated by `kgen module` from the provider schema. Do not edit.

output "id" {
  description = "id of the kion_ou_cloud_access_role_exemption."
  value       = kion_ou_cloud_access_role_exemption.this.id
}
