# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_gcp_account" "this" {
  account_alias           = var.account_alias
  account_name            = var.account_name
  account_type_id         = var.account_type_id
  google_cloud_project_id = var.google_cloud_project_id
  payer_id                = var.payer_id
  project_id              = var.project_id
  skip_access_checking    = var.skip_access_checking
  start_datecode          = var.start_datecode
}
