// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package billing_rule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BillingRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"billing_source_ids": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Required:            true,
				Description:         "List of Billing Source IDs attached to the billing rule.",
				MarkdownDescription: "List of Billing Source IDs attached to the billing rule.",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "Description of the billing rule. The description can be up to 1024 characters long.",
				MarkdownDescription: "Description of the billing rule. The description can be up to 1024 characters long.",
			},
			"end_month": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "End month of the billing rule. This must be in the format YYYYMM where 202501 represents January 2025.\nThe end month is exclusive, e.g. if you want the rule to end in January 2025, send a value of 202502.\nOmit if the end month should be \"Never Ends\". If included, the value must be after the start month.",
				MarkdownDescription: "End month of the billing rule. This must be in the format YYYYMM where 202501 represents January 2025.\nThe end month is exclusive, e.g. if you want the rule to end in January 2025, send a value of 202502.\nOmit if the end month should be \"Never Ends\". If included, the value must be after the start month.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Billing Rule ID.",
				MarkdownDescription: "Billing Rule ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the billing rule. The name can be up to 255 characters long.",
				MarkdownDescription: "Name of the billing rule. The name can be up to 255 characters long.",
			},
			"rule_type": schema.Int64Attribute{
				Required:            true,
				Description:         "Type of the billing rule. The allowed values are:\n\n1 - Rate Conversion\n2 - Markup\n3 - Discount",
				MarkdownDescription: "Type of the billing rule. The allowed values are:\n\n1 - Rate Conversion\n2 - Markup\n3 - Discount",
			},
			"rule_value": schema.Float64Attribute{
				Required:            true,
				Description:         "The Value of the Billing Rule.\n\nThis is handled differently based on the Type of Billing Rules. For instance:\n\nFor a 5% markup, the value would be 5.0\nFor a 10% discount, the value would be 10.0\nFor a 1.214 currency conversion, the value would be 1.214",
				MarkdownDescription: "The Value of the Billing Rule.\n\nThis is handled differently based on the Type of Billing Rules. For instance:\n\nFor a 5% markup, the value would be 5.0\nFor a 10% discount, the value would be 10.0\nFor a 1.214 currency conversion, the value would be 1.214",
			},
			"start_month": schema.Int64Attribute{
				Required:            true,
				Description:         "Start month of the billing rule. This must be in the format YYYYMM where 202501 represents January 2025.",
				MarkdownDescription: "Start month of the billing rule. This must be in the format YYYYMM where 202501 represents January 2025.",
			},
		},
		Description: "Manages a Kion Billing Rule.",
	}
}

type BillingRuleModel struct {
	BillingSourceIds types.Set     `tfsdk:"billing_source_ids"`
	Description      types.String  `tfsdk:"description"`
	EndMonth         types.Int64   `tfsdk:"end_month"`
	Id               types.String  `tfsdk:"id"`
	Name             types.String  `tfsdk:"name"`
	RuleType         types.Int64   `tfsdk:"rule_type"`
	RuleValue        types.Float64 `tfsdk:"rule_value"`
	StartMonth       types.Int64   `tfsdk:"start_month"`
}
