// Code generated by kgen crud. DO NOT EDIT.

package billing_rule

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_billing_rule", &resource.Sweeper{
		Name: "kion_billing_rule",
		F:    sweepBillingRule,
	})
}

func sweepBillingRule(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_billing_rule resources with the "test-acc" prefix and
	// delete each via conn.Client.DeleteBillingRule.
	// A real list+delete sweeper needs paginated-list-envelope resolution — see
	// the CRUD generator follow-up plan.
	return nil
}
