// Code generated by kgen crud. DO NOT EDIT.

package project_note_test

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/conns"
)

func TestAccKionProjectNote_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_project_note.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckProjectNoteDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccProjectNoteConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckProjectNoteExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "create_user_id", "1"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "project_id"),
					resource.TestCheckResourceAttr(resourceName, "text", "test-acc project note"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

// project_noteReadPath is the private route this resource reads through; a blended
// resource has no typed by-id GET.
func project_noteReadPath(id int64) string {
	return strings.Replace("/v2/project-note/{id}", "{id}", strconv.FormatInt(id, 10), 1)
}

func testAccCheckProjectNoteExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		if _, err := conn.RawGet(ctx, project_noteReadPath(id)); err != nil {
			if conns.IsRawNotFound(err) {
				return fmt.Errorf("kion_project_note (%d) not found", id)
			}
			return fmt.Errorf("reading kion_project_note (%d): %w", id, err)
		}

		return nil
	}
}

func testAccCheckProjectNoteDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_project_note" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			_, err = conn.RawGet(ctx, project_noteReadPath(id))
			if conns.IsRawNotFound(err) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_project_note (%d): %w", id, err)
			}

			return fmt.Errorf("kion_project_note (%d) still exists", id)
		}

		return nil
	}
}

func testAccProjectNoteConfig_basic(rName string) string {
	return acctest.FundingSourceConfig(rName) + fmt.Sprintf(`
resource "kion_permission_scheme" "test_pn_perm" {
  name = "%[1]s-pn-perm"
  type = "project"
}

resource "kion_project" "test" {
  name                 = "%[1]s-project"
  ou_id                = kion_ou.test_fs_ou.id
  permission_scheme_id = kion_permission_scheme.test_pn_perm.id
  owner_user_ids       = [1]

  budget = [{
    amount             = 500
    start_datecode     = "2026-01"
    end_datecode       = "2026-12"
    funding_source_ids = [kion_funding_source.test_fs.id]
  }]
}

resource "kion_project_note" "test" {
  create_user_id = 1
  name = "%[1]s"
  project_id = kion_project.test.id
  text = "test-acc project note"
}
`, rName)
}
