# Generated by `kgen module` from the provider schema. Do not edit.

variable "default_value_list" {
  description = "Default value when the custom variable type is list."
  type        = list(string)
  default     = null
}

variable "default_value_map" {
  description = "Default value when the custom variable type is map."
  type        = map(string)
  default     = null
}

variable "default_value_string" {
  description = "Default value when the custom variable type is string."
  type        = string
  default     = null
}

variable "description" {
  description = "Description is the description of the custom variable. The description can be up to 1024 characters."
  type        = string
  default     = null
}

variable "key_validation_message" {
  description = "KeyValidationMessage is the message displayed when the custom variable key(s) do not match the regular expression. The key validation message can be up to 255 characters."
  type        = string
  default     = null
}

variable "key_validation_regex" {
  description = "KeyValidationRegex is the regular expression used to validate the custom variable key(s) within the map custom variable type. The key validation regex can be up to 255 characters."
  type        = string
  default     = null
}

variable "name" {
  description = "Name is the name of the custom variable. The name can be up to 255 characters."
  type        = string
  default     = null
}

variable "owner_user_group_ids" {
  description = "OwnerUGroupIDs is the list of user group IDs who will own the custom variable."
  type        = list(number)
  default     = null
}

variable "owner_user_ids" {
  description = "OwnerUserIDs is the list of user IDs who will own the custom variable."
  type        = list(number)
  default     = null
}

variable "type" {
  description = "Type is the type of the custom variable. The supported types are string, list, and map."
  type        = string
  default     = null
}

variable "value_validation_message" {
  description = "ValueValidationMessage is the message displayed when the custom variable value(s) do not match the regular expression. The validation message can be up to 255 characters."
  type        = string
  default     = null
}

variable "value_validation_regex" {
  description = "ValueValidationRegex is the regular expression used to validate the custom variable value(s). The validation regex can be up to 255 characters."
  type        = string
  default     = null
}
