# Generated by `kgen module` from the provider schema. Do not edit.

module "this" {
  source = "../.."

  account_name   = "example"
  account_number = "example"
  payer_id       = 1
  project_id     = 1
  start_datecode = "2026-01"
}
