// Code generated by kgen crud. DO NOT EDIT.

package custom_account

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const DSNameCustomAccount = "CustomAccount Data Source"

var (
	_ datasource.DataSource              = &custom_accountDataSource{}
	_ datasource.DataSourceWithConfigure = &custom_accountDataSource{}
)

// NewCustomAccountDataSource returns a new instance of the data source.
func NewCustomAccountDataSource() datasource.DataSource {
	return &custom_accountDataSource{}
}

type custom_accountDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *custom_accountDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_account"
}

func (d *custom_accountDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to look up a Kion CustomAccount by id.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of the CustomAccount to fetch.",
				Required:    true,
			},
			"account_alias": schema.StringAttribute{
				Computed: true,
			},
			"account_name": schema.StringAttribute{
				Computed: true,
			},
			"account_number": schema.StringAttribute{
				Computed: true,
			},
			"payer_id": schema.Int64Attribute{
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Computed: true,
			},
			"start_datecode": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *custom_accountDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data custom_accountDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := conn.GetAccount(ctx, generated.GetAccountParams{ID: data.Id.ValueInt64()})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameCustomAccount), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameCustomAccount), "custom_account not found")
		return
	}

	api, ok := out.(*generated.AccountResponse)
	if !ok || !api.Data.Set {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("reading "+DSNameCustomAccount, out)...)
		return
	}

	v := api.Data.Value
	data.Id = flex.OptUint64ToFramework(v.ID)
	data.AccountAlias = flex.OptStringToFramework(v.AccountAlias)
	data.AccountName = flex.OptStringToFramework(v.AccountName)
	data.AccountNumber = flex.OptStringToFramework(v.AccountNumber)
	data.PayerId = flex.OptNilUint64ToFramework(v.PayerID)
	data.ProjectId = flex.OptNilUint64ToFramework(v.ProjectID)
	data.StartDatecode = flex.OptStringToFramework(v.StartDatecode)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type custom_accountDataSourceModel struct {
	Id            types.Int64  `tfsdk:"id"`
	AccountAlias  types.String `tfsdk:"account_alias"`
	AccountName   types.String `tfsdk:"account_name"`
	AccountNumber types.String `tfsdk:"account_number"`
	PayerId       types.Int64  `tfsdk:"payer_id"`
	ProjectId     types.Int64  `tfsdk:"project_id"`
	StartDatecode types.String `tfsdk:"start_datecode"`
}
