// Code generated by kgen crud. DO NOT EDIT.

package custom_account

import (
	"fmt"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func init() {
	resource.AddTestSweepers("kion_custom_account", &resource.Sweeper{
		Name: "kion_custom_account",
		F:    sweepCustomAccount,
	})
}

func sweepCustomAccount(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	_ = conn

	// TODO: list kion_custom_account resources with the "test-acc" prefix and
	// delete each via conn.Client.DeleteAccount.
	// A real list+delete sweeper needs paginated-list-envelope resolution — see
	// the CRUD generator follow-up plan.
	return nil
}
