// Code generated by kgen crud. DO NOT EDIT.

package account_cache

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const (
	DSNameAccountCache = "AccountCache Data Source"
)

var (
	_ datasource.DataSource              = &account_cacheDataSource{}
	_ datasource.DataSourceWithConfigure = &account_cacheDataSource{}
)

// listObjectAttrTypes is the schema of an entry inside the `list` attribute.
var listObjectAttrTypes = map[string]attr.Type{
	"id":                           types.Int64Type,
	"account_alias":                types.StringType,
	"account_email":                types.StringType,
	"account_name":                 types.StringType,
	"account_number":               types.StringType,
	"account_type_id":              types.Int64Type,
	"car_external_id":              types.StringType,
	"created_at":                   types.StringType,
	"include_linked_account_spend": types.BoolType,
	"linked_account_number":        types.StringType,
	"linked_role":                  types.StringType,
	"payer_id":                     types.Int64Type,
	"service_external_id":          types.StringType,
	"skip_access_checking":         types.BoolType,
}

// NewAccountCacheDataSource returns a new instance of the data source.
func NewAccountCacheDataSource() datasource.DataSource {
	return &account_cacheDataSource{}
}

type account_cacheDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *account_cacheDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account_cache"
}

// Schema is dual-mode: `id` fetches one by primary key; omitting `id` and
// supplying `filter` blocks paginates the index and returns every match in
// `list`. `id` and `filter` are mutually exclusive.
func (d *account_cacheDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion AccountCaches. Supports lookup by id (recommended) or by filter blocks (legacy).",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of a single account_cache to fetch. Mutually exclusive with `filter` blocks.",
				Optional:    true,
				Computed:    true,
			},
			"account_alias": schema.StringAttribute{
				Computed: true,
			},
			"account_email": schema.StringAttribute{
				Computed: true,
			},
			"account_name": schema.StringAttribute{
				Computed: true,
			},
			"account_number": schema.StringAttribute{
				Computed: true,
			},
			"account_type_id": schema.Int64Attribute{
				Computed: true,
			},
			"car_external_id": schema.StringAttribute{
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"include_linked_account_spend": schema.BoolAttribute{
				Computed: true,
			},
			"linked_account_number": schema.StringAttribute{
				Computed: true,
			},
			"linked_role": schema.StringAttribute{
				Computed: true,
			},
			"payer_id": schema.Int64Attribute{
				Computed: true,
			},
			"service_external_id": schema.StringAttribute{
				Computed: true,
			},
			"skip_access_checking": schema.BoolAttribute{
				Computed: true,
			},
			"list": schema.ListNestedAttribute{
				Description: "All account_caches matching the supplied id or filter blocks.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"account_alias": schema.StringAttribute{
							Computed: true,
						},
						"account_email": schema.StringAttribute{
							Computed: true,
						},
						"account_name": schema.StringAttribute{
							Computed: true,
						},
						"account_number": schema.StringAttribute{
							Computed: true,
						},
						"account_type_id": schema.Int64Attribute{
							Computed: true,
						},
						"car_external_id": schema.StringAttribute{
							Computed: true,
						},
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"include_linked_account_spend": schema.BoolAttribute{
							Computed: true,
						},
						"linked_account_number": schema.StringAttribute{
							Computed: true,
						},
						"linked_role": schema.StringAttribute{
							Computed: true,
						},
						"payer_id": schema.Int64Attribute{
							Computed: true,
						},
						"service_external_id": schema.StringAttribute{
							Computed: true,
						},
						"skip_access_checking": schema.BoolAttribute{
							Computed: true,
						},
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *account_cacheDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data account_cacheDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idSet := !data.Id.IsNull() && !data.Id.IsUnknown()
	filterSet := len(data.Filter) > 0

	if idSet && filterSet {
		resp.Diagnostics.AddError(
			fmt.Sprintf("invalid %s configuration", DSNameAccountCache),
			"`id` and `filter` blocks are mutually exclusive.",
		)
		return
	}

	if idSet {
		d.readByID(ctx, conn, &data, &resp.Diagnostics)
	} else {
		d.readByFilter(ctx, conn, &data, &resp.Diagnostics)
	}

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *account_cacheDataSource) readByID(ctx context.Context, conn *generated.Client, data *account_cacheDataSourceModel, diags *diag.Diagnostics) {
	out, err := conn.GetAccountCache(ctx, generated.GetAccountCacheParams{ID: data.Id.ValueInt64()})
	if err != nil {
		diags.AddError(fmt.Sprintf("reading %s", DSNameAccountCache), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		diags.AddError(fmt.Sprintf("reading %s", DSNameAccountCache), "account_cache not found")
		return
	}
	api, ok := out.(*generated.AccountCacheResponse)
	if !ok || !api.Data.Set {
		diags.Append(errs.ResponseDiagnostics("reading "+DSNameAccountCache, out)...)
		return
	}

	lbl := api.Data.Value
	data.Id = flex.OptUint64ToFramework(lbl.ID)
	data.AccountAlias = flex.OptStringToFramework(lbl.AccountAlias)
	data.AccountEmail = flex.OptStringToFramework(lbl.AccountEmail)
	data.AccountName = flex.OptStringToFramework(lbl.AccountName)
	data.AccountNumber = flex.OptStringToFramework(lbl.AccountNumber)
	data.AccountTypeId = flex.OptNilUint64ToFramework(lbl.AccountTypeID)
	data.CarExternalId = flex.OptStringToFramework(lbl.CarExternalID)
	data.CreatedAt = flex.OptStringToFramework(lbl.CreatedAt)
	data.IncludeLinkedAccountSpend = flex.OptNilBoolToFramework(lbl.IncludeLinkedAccountSpend)
	data.LinkedAccountNumber = flex.OptStringToFramework(lbl.LinkedAccountNumber)
	data.LinkedRole = flex.OptStringToFramework(lbl.LinkedRole)
	data.PayerId = flex.OptNilUint64ToFramework(lbl.PayerID)
	data.ServiceExternalId = flex.OptStringToFramework(lbl.ServiceExternalID)
	data.SkipAccessChecking = flex.OptNilBoolToFramework(lbl.SkipAccessChecking)

	listVal, listDiags := buildAccountCacheList(ctx, []generated.AccountCache{lbl})
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal
}

func (d *account_cacheDataSource) readByFilter(ctx context.Context, conn *generated.Client, data *account_cacheDataSourceModel, diags *diag.Diagnostics) {
	all, fetchDiags := fetchAllAccountCache(ctx, conn)
	diags.Append(fetchDiags...)
	if diags.HasError() {
		return
	}

	matched := make([]generated.AccountCache, 0, len(all))
	for _, lbl := range all {
		ok, matchDiags := filter.Match(ctx, data.Filter, account_cacheToRow(lbl))
		diags.Append(matchDiags...)
		if diags.HasError() {
			return
		}
		if ok {
			matched = append(matched, lbl)
		}
	}

	listVal, listDiags := buildAccountCacheList(ctx, matched)
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal

	// Scalar fields stay null in filter mode.
	data.Id = types.Int64Null()
	data.AccountAlias = types.StringNull()
	data.AccountEmail = types.StringNull()
	data.AccountName = types.StringNull()
	data.AccountNumber = types.StringNull()
	data.AccountTypeId = types.Int64Null()
	data.CarExternalId = types.StringNull()
	data.CreatedAt = types.StringNull()
	data.IncludeLinkedAccountSpend = types.BoolNull()
	data.LinkedAccountNumber = types.StringNull()
	data.LinkedRole = types.StringNull()
	data.PayerId = types.Int64Null()
	data.ServiceExternalId = types.StringNull()
	data.SkipAccessChecking = types.BoolNull()
}

// fetchAllAccountCache returns the full set from GetAccountCacheIndex, which is not
// paginated: one call yields the whole collection.
func fetchAllAccountCache(ctx context.Context, conn *generated.Client) ([]generated.AccountCache, diag.Diagnostics) {
	var diags diag.Diagnostics
	var all []generated.AccountCache

	out, err := conn.GetAccountCacheIndex(ctx)
	if err != nil {
		diags.AddError(fmt.Sprintf("listing %s", DSNameAccountCache), err.Error())
		return nil, diags
	}
	resp, ok := out.(*generated.AccountCacheListResponse)
	if !ok {
		diags.Append(errs.ResponseDiagnostics("listing "+DSNameAccountCache, out)...)
		return nil, diags
	}
	items := resp.Data
	all = append(all, items...)

	return all, diags
}

// account_cacheToRow converts an element into the map filter.Match expects.
func account_cacheToRow(lbl generated.AccountCache) map[string]any {
	row := map[string]any{
		"account_alias":                lbl.AccountAlias.Or(""),
		"account_email":                lbl.AccountEmail.Or(""),
		"account_name":                 lbl.AccountName.Or(""),
		"account_number":               lbl.AccountNumber.Or(""),
		"account_type_id":              int64(lbl.AccountTypeID.Or(0)),
		"car_external_id":              lbl.CarExternalID.Or(""),
		"created_at":                   lbl.CreatedAt.Or(""),
		"include_linked_account_spend": lbl.IncludeLinkedAccountSpend.Or(false),
		"linked_account_number":        lbl.LinkedAccountNumber.Or(""),
		"linked_role":                  lbl.LinkedRole.Or(""),
		"payer_id":                     int64(lbl.PayerID.Or(0)),
		"service_external_id":          lbl.ServiceExternalID.Or(""),
		"skip_access_checking":         lbl.SkipAccessChecking.Or(false),
	}
	if lbl.ID.Set {
		row["id"] = int64(lbl.ID.Value)
	}
	return row
}

// buildAccountCacheList converts elements into a types.List of objects.
func buildAccountCacheList(ctx context.Context, items []generated.AccountCache) (types.List, diag.Diagnostics) {
	objs := make([]attr.Value, 0, len(items))
	for _, lbl := range items {
		idVal := types.Int64Null()
		if lbl.ID.Set {
			idVal = types.Int64Value(int64(lbl.ID.Value))
		}
		obj, objDiags := types.ObjectValue(listObjectAttrTypes, map[string]attr.Value{
			"id":                           idVal,
			"account_alias":                types.StringValue(lbl.AccountAlias.Or("")),
			"account_email":                types.StringValue(lbl.AccountEmail.Or("")),
			"account_name":                 types.StringValue(lbl.AccountName.Or("")),
			"account_number":               types.StringValue(lbl.AccountNumber.Or("")),
			"account_type_id":              types.Int64Value(int64(lbl.AccountTypeID.Or(0))),
			"car_external_id":              types.StringValue(lbl.CarExternalID.Or("")),
			"created_at":                   types.StringValue(lbl.CreatedAt.Or("")),
			"include_linked_account_spend": types.BoolValue(lbl.IncludeLinkedAccountSpend.Or(false)),
			"linked_account_number":        types.StringValue(lbl.LinkedAccountNumber.Or("")),
			"linked_role":                  types.StringValue(lbl.LinkedRole.Or("")),
			"payer_id":                     types.Int64Value(int64(lbl.PayerID.Or(0))),
			"service_external_id":          types.StringValue(lbl.ServiceExternalID.Or("")),
			"skip_access_checking":         types.BoolValue(lbl.SkipAccessChecking.Or(false)),
		})
		if objDiags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listObjectAttrTypes}), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, types.ObjectType{AttrTypes: listObjectAttrTypes}, objs)
}

type account_cacheDataSourceModel struct {
	Id                        types.Int64    `tfsdk:"id"`
	AccountAlias              types.String   `tfsdk:"account_alias"`
	AccountEmail              types.String   `tfsdk:"account_email"`
	AccountName               types.String   `tfsdk:"account_name"`
	AccountNumber             types.String   `tfsdk:"account_number"`
	AccountTypeId             types.Int64    `tfsdk:"account_type_id"`
	CarExternalId             types.String   `tfsdk:"car_external_id"`
	CreatedAt                 types.String   `tfsdk:"created_at"`
	IncludeLinkedAccountSpend types.Bool     `tfsdk:"include_linked_account_spend"`
	LinkedAccountNumber       types.String   `tfsdk:"linked_account_number"`
	LinkedRole                types.String   `tfsdk:"linked_role"`
	PayerId                   types.Int64    `tfsdk:"payer_id"`
	ServiceExternalId         types.String   `tfsdk:"service_external_id"`
	SkipAccessChecking        types.Bool     `tfsdk:"skip_access_checking"`
	Filter                    []filter.Model `tfsdk:"filter"`
	List                      types.List     `tfsdk:"list"`
}
