// Code generated by kgen crud. DO NOT EDIT.

package account_cache_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"terraform-provider-kion/internal/acctest"
)

func TestAccKionAccountCacheDataSource_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	payerID := acctest.RequireEnv(t, "KION_ACC_PAYER_ID", "the payer id")
	awsAccountNumber := acctest.RequireEnv(t, "KION_ACC_AWS_ACCOUNT_NUMBER", "the aws account number")
	dataSourceName := "data.kion_account_cache.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccAccountCacheDataSourceConfig_basic(rName, payerID, awsAccountNumber),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(dataSourceName, "id"),
					resource.TestCheckResourceAttrSet(dataSourceName, "account_name"),
					resource.TestCheckResourceAttrSet(dataSourceName, "account_number"),
					resource.TestCheckResourceAttrSet(dataSourceName, "payer_id"),
				),
			},
		},
	})
}

func testAccAccountCacheDataSourceConfig_basic(rName string, payerID string, awsAccountNumber string) string {
	return fmt.Sprintf(`
resource "kion_account_cache" "test" {
  account_name = "%[1]s"
  account_number = "%[3]s"
  payer_id = %[2]s
}

data "kion_account_cache" "test" {
  id = kion_account_cache.test.id
}
`, rName, payerID, awsAccountNumber)
}
