// Code generated by kgen crud. DO NOT EDIT.

// Package account_cache implements the Terraform resource and data source for account_cache.
package account_cache

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameAccountCache = "AccountCache"

var (
	_ resource.Resource                = &account_cacheResource{}
	_ resource.ResourceWithConfigure   = &account_cacheResource{}
	_ resource.ResourceWithImportState = &account_cacheResource{}
)

// NewAccountCacheResource returns a new instance of the resource.
func NewAccountCacheResource() resource.Resource {
	return &account_cacheResource{}
}

type account_cacheResource struct {
	framework.ResourceWithConfigure
}

func (r *account_cacheResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_account_cache"
}

func (r *account_cacheResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Schema is generated from the OpenAPI spec (account_cache_schema_gen.go); the
	// bits the spec can't express come from codegen/schema_overrides.yaml.
	resp.Schema = AccountCacheResourceSchema(ctx)
}

func (r *account_cacheResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan AccountCacheModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	organizationalUnit := generated.PayerOrganizationalUnit{
		Name:      flex.OptStringFromFramework(plan.OrganizationalUnit.Name),
		OrgUnitID: flex.OptStringFromFramework(plan.OrganizationalUnit.OrgUnitId),
	}
	input := &generated.AWSAccountCacheNewAWSAccount{
		AccountAlias:              flex.OptStringFromFramework(plan.AccountAlias),
		AccountEmail:              flex.OptStringFromFramework(plan.AccountEmail),
		AccountName:               flex.StringValueFromFramework(plan.AccountName),
		AccountTypeID:             flex.OptNilUint64FromFramework(plan.AccountTypeId),
		CommercialAccountName:     flex.OptStringFromFramework(plan.CommercialAccountName),
		CreateGovcloud:            flex.OptNilBoolFromFramework(plan.CreateGovcloud),
		GovAccountName:            flex.OptStringFromFramework(plan.GovAccountName),
		IncludeLinkedAccountSpend: flex.OptNilBoolFromFramework(plan.IncludeLinkedAccountSpend),
		LinkedRole:                flex.OptStringFromFramework(plan.LinkedRole),
		PayerID:                   flex.NilUint64FromFramework(plan.PayerId),
		OrganizationalUnit:        generated.OptPayerOrganizationalUnit{Value: organizationalUnit, Set: true},
	}

	out, err := conn.PostAccountCacheCreateNewAWS(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameAccountCache), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back the resource to populate computed fields.
	readOut, readErr := conn.GetAccountCache(ctx, generated.GetAccountCacheParams{ID: id})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameAccountCache, id), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenAccountCache(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *account_cacheResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	conn := r.Meta().Client

	var state AccountCacheModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.GetAccountCache(ctx, generated.GetAccountCacheParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameAccountCache, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenAccountCache(out, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *account_cacheResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan AccountCacheModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.AccountCacheUpdatable{
		AccountAlias:              flex.OptStringFromFramework(plan.AccountAlias),
		AccountEmail:              flex.OptStringFromFramework(plan.AccountEmail),
		AccountName:               flex.OptStringFromFramework(plan.AccountName),
		IncludeLinkedAccountSpend: flex.OptNilBoolFromFramework(plan.IncludeLinkedAccountSpend),
		LinkedRole:                flex.OptStringFromFramework(plan.LinkedRole),
		SkipAccessChecking:        flex.OptNilBoolFromFramework(plan.SkipAccessChecking),
	}

	idInt, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.PatchAccountCache(ctx, input, generated.PatchAccountCacheParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameAccountCache, idInt), err.Error())
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameAccountCache), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read back the resource to get the latest state.
	readOut, readErr := conn.GetAccountCache(ctx, generated.GetAccountCacheParams{ID: idInt})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameAccountCache, idInt), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenAccountCache(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *account_cacheResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state AccountCacheModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteAccountCache(ctx, generated.DeleteAccountCacheParams{ID: uint64(idInt)})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameAccountCache, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameAccountCache), out)
	resp.Diagnostics.Append(diags...)
}

func (r *account_cacheResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

func flattenAccountCache(apiObject any, model *AccountCacheModel) diag.Diagnostics {
	switch v := apiObject.(type) {
	case *generated.AccountCacheResponse:
		if v.Data.Set {
			model.AccountAlias = flex.OptStringToFramework(v.Data.Value.AccountAlias)
			model.AccountEmail = flex.OptStringToFramework(v.Data.Value.AccountEmail)
			model.AccountName = flex.OptStringToFramework(v.Data.Value.AccountName)
			model.AccountNumber = flex.OptStringToFramework(v.Data.Value.AccountNumber)
			model.AccountTypeId = flex.OptNilUint64ToFramework(v.Data.Value.AccountTypeID)
			model.CarExternalId = flex.OptStringToFramework(v.Data.Value.CarExternalID)
			model.CreatedAt = flex.OptStringToFramework(v.Data.Value.CreatedAt)
			if v.Data.Value.ID.Set {
				model.Id = types.StringValue(strconv.FormatUint(v.Data.Value.ID.Value, 10))
			}
			model.IncludeLinkedAccountSpend = flex.OptNilBoolToFramework(v.Data.Value.IncludeLinkedAccountSpend)
			model.LinkedAccountNumber = flex.OptStringToFramework(v.Data.Value.LinkedAccountNumber)
			model.LinkedRole = flex.OptStringToFramework(v.Data.Value.LinkedRole)
			model.PayerId = flex.OptNilUint64ToFramework(v.Data.Value.PayerID)
			model.ServiceExternalId = flex.OptStringToFramework(v.Data.Value.ServiceExternalID)
			model.SkipAccessChecking = flex.OptNilBoolToFramework(v.Data.Value.SkipAccessChecking)
		}
		return nil
	default:
		return errs.ResponseDiagnostics("reading "+ResNameAccountCache, apiObject)
	}
}
