// Code generated by kgen crud. DO NOT EDIT.

package account_cache

import (
	"context"
	"fmt"
	"strings"

	"terraform-provider-kion/internal/conns"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func init() {
	resource.AddTestSweepers("kion_account_cache", &resource.Sweeper{
		Name: "kion_account_cache",
		F:    sweepAccountCache,
	})
}

// sweepAccountCache reads GetAccountCacheIndex (not paginated: one call yields the whole
// collection) collecting ids whose test resources carry the acceptance-test
// prefix, then deletes them via DeleteAccountCache.
func sweepAccountCache(_ string) error {
	conn, err := conns.SharedClient()
	if err != nil {
		return fmt.Errorf("getting shared client: %w", err)
	}
	ctx := context.Background()

	var ids []int64
	// GetAccountCacheIndex is not paginated: one call returns the whole collection.
	out, err := conn.Client.GetAccountCacheIndex(ctx)
	if err != nil {
		return fmt.Errorf("listing kion_account_cache: %w", err)
	}
	if resp, ok := out.(*generated.AccountCacheListResponse); ok {
		items := resp.Data
		for _, item := range items {
			if item.ID.Set && sweepAccountCacheMatch(item) {
				ids = append(ids, int64(item.ID.Value))
			}
		}
	}

	for _, id := range ids {
		if _, err := conn.Client.DeleteAccountCache(ctx, generated.DeleteAccountCacheParams{ID: uint64(id)}); err != nil {
			return fmt.Errorf("deleting kion_account_cache (%d): %w", id, err)
		}
	}
	return nil
}

func sweepAccountCacheMatch(item generated.AccountCache) bool {
	for _, s := range []string{
		item.AccountAlias.Or(""),
		item.AccountEmail.Or(""),
		item.AccountName.Or(""),
		item.AccountNumber.Or(""),
		item.CarExternalID.Or(""),
		item.CreatedAt.Or(""),
		item.LinkedAccountNumber.Or(""),
		item.LinkedRole.Or(""),
		item.ServiceExternalID.Or(""),
	} {
		if strings.HasPrefix(s, "test-acc") {
			return true
		}
	}
	return false
}
