// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ou_cloud_access_role_exemption

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OuCloudAccessRoleExemptionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the record in the application.",
				MarkdownDescription: "ID of the record in the application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"ou_cloud_access_role_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the ou cloud access role in the application being exempted from.",
				MarkdownDescription: "ID of the ou cloud access role in the application being exempted from.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"ou_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the ou in the application.",
				MarkdownDescription: "ID of the ou in the application.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"reason": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reason the Cloud Access Role is being exempted.",
				MarkdownDescription: "Reason the Cloud Access Role is being exempted.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Description: "Manages a Kion OU Cloud Access Role Exemption.",
	}
}

type OuCloudAccessRoleExemptionModel struct {
	Id                  types.String `tfsdk:"id"`
	OuCloudAccessRoleId types.Int64  `tfsdk:"ou_cloud_access_role_id"`
	OuId                types.Int64  `tfsdk:"ou_id"`
	Reason              types.String `tfsdk:"reason"`
}
