// Code generated by kgen crud. DO NOT EDIT.

// Package ou_cloud_access_role_exemption implements the Terraform resource for ou_cloud_access_role_exemption.
package ou_cloud_access_role_exemption

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameOuCloudAccessRoleExemption = "OuCloudAccessRoleExemption"

var (
	_ resource.Resource                = &ou_cloud_access_role_exemptionResource{}
	_ resource.ResourceWithConfigure   = &ou_cloud_access_role_exemptionResource{}
	_ resource.ResourceWithImportState = &ou_cloud_access_role_exemptionResource{}
)

// NewOuCloudAccessRoleExemptionResource returns a new instance of the resource.
func NewOuCloudAccessRoleExemptionResource() resource.Resource {
	return &ou_cloud_access_role_exemptionResource{}
}

type ou_cloud_access_role_exemptionResource struct {
	framework.ResourceWithConfigure
}

func (r *ou_cloud_access_role_exemptionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ou_cloud_access_role_exemption"
}

func (r *ou_cloud_access_role_exemptionResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = OuCloudAccessRoleExemptionResourceSchema(ctx)
}

func (r *ou_cloud_access_role_exemptionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan OuCloudAccessRoleExemptionModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.OUCloudAccessRoleExemption{
		OuCloudAccessRoleID: flex.OptNilUint64FromFramework(plan.OuCloudAccessRoleId),
		OuID:                flex.OptNilUint64FromFramework(plan.OuId),
		Reason:              flex.OptStringFromFramework(plan.Reason),
	}

	out, err := conn.PostOUCloudAccessRoleExemption(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameOuCloudAccessRoleExemption), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// No read endpoint exists; the plan holds every writable field, so it is the
	// full post-create state.
	plan.Id = types.StringValue(strconv.FormatInt(id, 10))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ou_cloud_access_role_exemptionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// kion_ou_cloud_access_role_exemption has no read endpoint; there is nothing to refresh, so the
	// existing state is preserved as-is (no drift detection is possible).
	var state OuCloudAccessRoleExemptionModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ou_cloud_access_role_exemptionResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not supported", "kion_ou_cloud_access_role_exemption cannot be updated in place; changes force replacement.")
}

func (r *ou_cloud_access_role_exemptionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state OuCloudAccessRoleExemptionModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteOUCloudAccessRoleExemption(ctx, generated.DeleteOUCloudAccessRoleExemptionParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameOuCloudAccessRoleExemption, idInt), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		return
	}
	resp.Diagnostics.Append(errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameOuCloudAccessRoleExemption), out)...)
}

func (r *ou_cloud_access_role_exemptionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
