// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package compliance_program

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ComplianceProgramResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description for the Compliance Program in the application.",
				MarkdownDescription: "Description for the Compliance Program in the application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"grouping_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "GroupType of the Compliance Program in the application.",
				MarkdownDescription: "GroupType of the Compliance Program in the application.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "compliance program ID.",
				MarkdownDescription: "compliance program ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the Compliance Program in the application.\nThis is the proper name of the program meant for formal page/card/document titles in the UI.",
				MarkdownDescription: "Name of the Compliance Program in the application.\nThis is the proper name of the program meant for formal page/card/document titles in the UI.",
			},
			"terse_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "TerseName of the Compliance Program in the application.\nThis is a concise name meant for easy identification and small UI spaces like program icons.",
				MarkdownDescription: "TerseName of the Compliance Program in the application.\nThis is a concise name meant for easy identification and small UI spaces like program icons.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"verbose_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VerboseName of the Compliance Program in the application.\nThis is a more detailed program name meant to suppliment the Name or TerseName in specific contexts.",
				MarkdownDescription: "VerboseName of the Compliance Program in the application.\nThis is a more detailed program name meant to suppliment the Name or TerseName in specific contexts.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"version": schema.StringAttribute{
				Required:            true,
				Description:         "Version of the Compliance Program in the application.",
				MarkdownDescription: "Version of the Compliance Program in the application.",
			},
		},
		Description: "Manages a Kion Compliance Program.",
	}
}

type ComplianceProgramModel struct {
	Description  types.String `tfsdk:"description"`
	GroupingType types.String `tfsdk:"grouping_type"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	TerseName    types.String `tfsdk:"terse_name"`
	VerboseName  types.String `tfsdk:"verbose_name"`
	Version      types.String `tfsdk:"version"`
}
