# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_account_cache" "this" {
  account_alias                = var.account_alias
  account_email                = var.account_email
  account_name                 = var.account_name
  account_number               = var.account_number
  account_type_id              = var.account_type_id
  commercial_account_name      = var.commercial_account_name
  create_govcloud              = var.create_govcloud
  gov_account_name             = var.gov_account_name
  include_linked_account_spend = var.include_linked_account_spend
  linked_role                  = var.linked_role
  organizational_unit          = var.organizational_unit
  payer_id                     = var.payer_id
  skip_access_checking         = var.skip_access_checking
}
