// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_kion

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func KionProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type KionModel struct {
}
