# Generated by `kgen module` from the provider schema. Do not edit.

variable "email" {
  description = "Email address of the user."
  type        = string
}

variable "first_name" {
  description = "First name of the user."
  type        = string
}

variable "idms_id" {
  description = "ID of the IDMS where the user exists."
  type        = number
}

variable "last_name" {
  description = "Last name of the user."
  type        = string
}

variable "mfa" {
  description = "The ID of the MFA type. Options: 1 is Webauthn (Yubikey), 2 is TOTP (Google Auth)."
  type        = number
  default     = null
}

variable "phone" {
  description = "Phone number of the user."
  type        = string
  default     = null
}

variable "user_group_ids" {
  description = "List of IDs of groups the user is in."
  type        = list(number)
  default     = null
}

variable "username" {
  description = "Username of the user."
  type        = string
}
