// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package app_config

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AppConfigResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"all_users_see_ou_names": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether all users can see the names of OU's in the organization chart.",
				MarkdownDescription: "Indicates whether all users can see the names of OU's in the organization chart.",
			},
			"allocation_mode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if allocation mode is enabled in the application.",
				MarkdownDescription: "Indicates if allocation mode is enabled in the application.",
			},
			"allow_custom_permission_schemes": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether custom permission schemes are allowed or not.",
				MarkdownDescription: "Indicates whether custom permission schemes are allowed or not.",
			},
			"app_api_key_creation_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if App API Key creation is enabled.",
				MarkdownDescription: "Indicates if App API Key creation is enabled.",
			},
			"app_api_key_lifespan": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates the lifespan of App API Keys in days.",
				MarkdownDescription: "Indicates the lifespan of App API Keys in days.",
			},
			"app_api_key_limit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates the max amount of App API Keys per user.",
				MarkdownDescription: "Indicates the max amount of App API Keys per user.",
			},
			"aws_access_key_creation_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether AWS access keys creation is enabled.",
				MarkdownDescription: "Indicates whether AWS access keys creation is enabled.",
			},
			"budget_mode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if budget mode is enabled in the application",
				MarkdownDescription: "Indicates if budget mode is enabled in the application",
			},
			"cloud_rule_group_ownership_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if cloud rules are restricted to User Group ownership only.\nSetting this to true will remove all users from cloud rules.\nThis cannot be undone.",
				MarkdownDescription: "Indicates if cloud rules are restricted to User Group ownership only.\nSetting this to true will remove all users from cloud rules.\nThis cannot be undone.",
			},
			"cost_savings_allow_terminate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether resource termination is allowed in-app.",
				MarkdownDescription: "Indicates whether resource termination is allowed in-app.",
			},
			"cost_savings_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether Cost Savings is enabled or not.",
				MarkdownDescription: "Indicates whether Cost Savings is enabled or not.",
			},
			"cost_savings_post_token_life_hours": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Post token life (hours) for Cloud Custodian webhook actions to execute.",
				MarkdownDescription: "Post token life (hours) for Cloud Custodian webhook actions to execute.",
			},
			"default_org_chart_view": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Defines the default organization chart view.\n\noneOf: list, policy, compliance, financial, spend",
				MarkdownDescription: "Defines the default organization chart view.\n\noneOf: list, policy, compliance, financial, spend",
			},
			"enforce_funding": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether spend plans or budgets must be created on all projects.\n\nexamples: true",
				MarkdownDescription: "Indicates whether spend plans or budgets must be created on all projects.\n\nexamples: true",
			},
			"enforce_funding_sources": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether every project should have a funding source.",
				MarkdownDescription: "Indicates whether every project should have a funding source.",
			},
			"event_driven_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether event driven is enabled or not.",
				MarkdownDescription: "Indicates whether event driven is enabled or not.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Static identifier for the single app-config record.",
				MarkdownDescription: "Static identifier for the single app-config record.",
			},
			"reserved_instances_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether reserved instances are enabled or not.",
				MarkdownDescription: "Indicates whether reserved instances are enabled or not.",
			},
			"resource_inventory_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether resource inventory is enabled or not.",
				MarkdownDescription: "Indicates whether resource inventory is enabled or not.",
			},
			"smtp_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates whether SMTP is enabled or not.",
				MarkdownDescription: "Indicates whether SMTP is enabled or not.",
			},
			"smtp_from": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The SMTP from address.",
				MarkdownDescription: "The SMTP from address.",
			},
			"smtp_host": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The SMTP host.",
				MarkdownDescription: "The SMTP host.",
			},
			"smtp_password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "The SMTP password.",
				MarkdownDescription: "The SMTP password.",
			},
			"smtp_port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The SMTP port.",
				MarkdownDescription: "The SMTP port.",
			},
			"smtp_skip_verify": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if the app should skip SMTP verification.",
				MarkdownDescription: "Indicates if the app should skip SMTP verification.",
			},
			"smtp_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The SMTP username.",
				MarkdownDescription: "The SMTP username.",
			},
			"supported_aws_regions": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The list of supported AWS regions",
				MarkdownDescription: "The list of supported AWS regions",
			},
		},
		Description: "Manages the Kion App Config (workspace-wide application settings singleton).",
	}
}

type AppConfigModel struct {
	AllUsersSeeOuNames            types.Bool   `tfsdk:"all_users_see_ou_names"`
	AllocationMode                types.Bool   `tfsdk:"allocation_mode"`
	AllowCustomPermissionSchemes  types.Bool   `tfsdk:"allow_custom_permission_schemes"`
	AppApiKeyCreationEnabled      types.Bool   `tfsdk:"app_api_key_creation_enabled"`
	AppApiKeyLifespan             types.Int64  `tfsdk:"app_api_key_lifespan"`
	AppApiKeyLimit                types.Int64  `tfsdk:"app_api_key_limit"`
	AwsAccessKeyCreationEnabled   types.Bool   `tfsdk:"aws_access_key_creation_enabled"`
	BudgetMode                    types.Bool   `tfsdk:"budget_mode"`
	CloudRuleGroupOwnershipOnly   types.Bool   `tfsdk:"cloud_rule_group_ownership_only"`
	CostSavingsAllowTerminate     types.Bool   `tfsdk:"cost_savings_allow_terminate"`
	CostSavingsEnabled            types.Bool   `tfsdk:"cost_savings_enabled"`
	CostSavingsPostTokenLifeHours types.Int64  `tfsdk:"cost_savings_post_token_life_hours"`
	DefaultOrgChartView           types.String `tfsdk:"default_org_chart_view"`
	EnforceFunding                types.Bool   `tfsdk:"enforce_funding"`
	EnforceFundingSources         types.Bool   `tfsdk:"enforce_funding_sources"`
	EventDrivenEnabled            types.Bool   `tfsdk:"event_driven_enabled"`
	Id                            types.String `tfsdk:"id"`
	ReservedInstancesEnabled      types.Bool   `tfsdk:"reserved_instances_enabled"`
	ResourceInventoryEnabled      types.Bool   `tfsdk:"resource_inventory_enabled"`
	SmtpEnabled                   types.Bool   `tfsdk:"smtp_enabled"`
	SmtpFrom                      types.String `tfsdk:"smtp_from"`
	SmtpHost                      types.String `tfsdk:"smtp_host"`
	SmtpPassword                  types.String `tfsdk:"smtp_password"`
	SmtpPort                      types.Int64  `tfsdk:"smtp_port"`
	SmtpSkipVerify                types.Bool   `tfsdk:"smtp_skip_verify"`
	SmtpUsername                  types.String `tfsdk:"smtp_username"`
	SupportedAwsRegions           types.Set    `tfsdk:"supported_aws_regions"`
}
