// Code generated by kgen crud. DO NOT EDIT.

package funding_source_enforcement_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionFundingSourceEnforcement_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_funding_source_enforcement.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckFundingSourceEnforcementDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccFundingSourceEnforcementConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckFundingSourceEnforcementExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "funding_source_id"),
					resource.TestCheckResourceAttr(resourceName, "threshold", "100"),
					resource.TestCheckResourceAttr(resourceName, "timeframe", "month"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
				),
			},
		},
	})
}

func TestAccKionFundingSourceEnforcement_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_funding_source_enforcement.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckFundingSourceEnforcementDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccFundingSourceEnforcementConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckFundingSourceEnforcementExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "funding_source_id"),
					resource.TestCheckResourceAttr(resourceName, "threshold", "100"),
					resource.TestCheckResourceAttr(resourceName, "timeframe", "month"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
				),
			},
			{
				Config: testAccFundingSourceEnforcementConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckFundingSourceEnforcementExists(ctx, resourceName),
					resource.TestCheckResourceAttr(resourceName, "cloud_rule_id", "2"),
					resource.TestCheckResourceAttrSet(resourceName, "funding_source_id"),
					resource.TestCheckResourceAttr(resourceName, "threshold", "200"),
					resource.TestCheckResourceAttr(resourceName, "timeframe", "month"),
					resource.TestCheckResourceAttrSet(resourceName, "user_ids"),
				),
			},
		},
	})
}

// findFundingSourceEnforcement reports whether the parent still lists a record with this id.
// The archetype has no by-id GET, so presence is decided from the collection.
func findFundingSourceEnforcement(ctx context.Context, parentID, id int64) (bool, error) {
	conn, err := acctest.SharedClient()
	if err != nil {
		return false, fmt.Errorf("getting shared client: %w", err)
	}

	out, err := conn.Client.GetFundingSourceEnforcements(ctx, generated.GetFundingSourceEnforcementsParams{ID: parentID})
	if err != nil {
		return false, fmt.Errorf("listing kion_funding_source_enforcement under parent %d: %w", parentID, err)
	}
	resp, ok := out.(*generated.FundingSourceEnforcementResponse)
	if !ok {
		return false, fmt.Errorf("unexpected response type %T", out)
	}
	for _, rec := range resp.Data {
		if rec.ID.Set && int64(rec.ID.Value) == id {
			return true, nil
		}
	}
	return false, nil
}

// ids reads the record id and its parent id out of Terraform state.
func funding_source_enforcementIDs(rs *terraform.ResourceState) (parentID, id int64, err error) {
	id, err = strconv.ParseInt(rs.Primary.ID, 10, 64)
	if err != nil {
		return 0, 0, fmt.Errorf("parsing ID: %w", err)
	}
	parentID, err = strconv.ParseInt(rs.Primary.Attributes["funding_source_id"], 10, 64)
	if err != nil {
		return 0, 0, fmt.Errorf("parsing funding_source_id: %w", err)
	}
	return parentID, id, nil
}

func testAccCheckFundingSourceEnforcementExists(ctx context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		parentID, id, err := funding_source_enforcementIDs(rs)
		if err != nil {
			return err
		}
		found, err := findFundingSourceEnforcement(ctx, parentID, id)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("kion_funding_source_enforcement (%d) not found under parent %d", id, parentID)
		}
		return nil
	}
}

func testAccCheckFundingSourceEnforcementDestroy(ctx context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_funding_source_enforcement" {
				continue
			}

			parentID, id, err := funding_source_enforcementIDs(rs)
			if err != nil {
				return err
			}
			// A deleted parent takes its children with it, so a list that fails
			// is not proof the child survived.
			found, err := findFundingSourceEnforcement(ctx, parentID, id)
			if err != nil {
				continue
			}
			if found {
				return fmt.Errorf("kion_funding_source_enforcement (%d) still exists under parent %d", id, parentID)
			}
		}
		return nil
	}
}

func testAccFundingSourceEnforcementConfig_basic(rName string) string {
	return acctest.FundingSourceConfig(rName) + `
resource "kion_funding_source_enforcement" "test" {
  funding_source_id = kion_funding_source.test_fs.id
  threshold = 100
  timeframe = "month"
  user_ids = [1]
}
`
}

func testAccFundingSourceEnforcementConfig_update(rName string) string {
	return acctest.FundingSourceConfig(rName) + `
resource "kion_funding_source_enforcement" "test" {
  cloud_rule_id = 2
  funding_source_id = kion_funding_source.test_fs.id
  threshold = 200
  timeframe = "month"
  user_ids = [1]
}
`
}
