# Generated by `kgen module` from the provider schema. Do not edit.

variable "create_user_id" {
  description = "ID of the user creating the note."
  type        = number
}

variable "name" {
  description = "Name of the OU note."
  type        = string
}

variable "ou_id" {
  description = "ID of the OU this note belongs to."
  type        = number
}

variable "text" {
  description = "Text content of the OU note."
  type        = string
}
