// Code generated by kgen crud. DO NOT EDIT.

package {{.Pkg}}_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	{{.SDKAlias}} "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKion{{.Pascal}}_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
{{- range .EnvArgs}}
	{{.Param}} := acctest.RequireEnv(t, "{{.Env}}", "{{.Describes}}")
{{- end}}
	resourceName := "{{.TypeName}}.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheck{{.Pascal}}Destroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAcc{{.Pascal}}Config_basic(rName{{range .EnvArgs}}, {{.Param}}{{end}}),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheck{{.Pascal}}Exists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					{{- range .CreateAttrs}}
					{{if .IsHCL}}resource.TestCheckResourceAttrSet(resourceName, "{{.Name}}"){{else}}resource.TestCheckResourceAttr(resourceName, "{{.Name}}", {{.CheckExpr}}){{end}},
					{{- end}}
				),
			},
		},
	})
}
{{if .HasUpdate}}
func TestAccKion{{.Pascal}}_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
{{- range .EnvArgs}}
	{{.Param}} := acctest.RequireEnv(t, "{{.Env}}", "{{.Describes}}")
{{- end}}
	resourceName := "{{.TypeName}}.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheck{{.Pascal}}Destroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAcc{{.Pascal}}Config_basic(rName{{range .EnvArgs}}, {{.Param}}{{end}}),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheck{{.Pascal}}Exists(ctx, resourceName),
					{{- range .CreateAttrs}}
					{{if .IsHCL}}resource.TestCheckResourceAttrSet(resourceName, "{{.Name}}"){{else}}resource.TestCheckResourceAttr(resourceName, "{{.Name}}", {{.CheckExpr}}){{end}},
					{{- end}}
				),
			},
			{
				Config: testAcc{{.Pascal}}Config_update(rName{{range .EnvArgs}}, {{.Param}}{{end}}),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheck{{.Pascal}}Exists(ctx, resourceName),
					{{- range .UpdateAttrs}}
					{{if .IsHCL}}resource.TestCheckResourceAttrSet(resourceName, "{{.Name}}"){{else}}resource.TestCheckResourceAttr(resourceName, "{{.Name}}", {{.CheckExpr}}){{end}},
					{{- end}}
				),
			},
		},
	})
}
{{end}}
// find{{.Pascal}} reports whether the collection still carries the row this
// resource keys on. An association has no record of its own: it is a row in the
// parent's membership list, so presence is decided by the key.
func find{{.Pascal}}(ctx context.Context, {{if .HasParent}}parentID, {{end}}key int64) (bool, error) {
	conn, err := acctest.SharedClient()
	if err != nil {
		return false, fmt.Errorf("getting shared client: %w", err)
	}

	out, err := conn.Client.{{.ReadMethod}}(ctx{{if .ReadParams}}, {{.SDKAlias}}.{{.ReadParams}}{ {{if .HasParent}}{{.ParentArg}}: parentID{{end}}}{{end}})
	if err != nil {
		return false, fmt.Errorf("listing {{.TypeName}}: %w", err)
	}
	if errs.IsNotFound(out) {
		return false, nil
	}
	resp, ok := out.(*{{.SDKAlias}}.{{.RespType}})
	if !ok {
		return false, fmt.Errorf("unexpected response type %T", out)
	}
	for _, rec := range resp.{{.DataGo}} {
		if !rec.{{.RecordKeyGo}}.Null && int64(rec.{{.RecordKeyGo}}.Value) == key {
			return true, nil
		}
	}
	return false, nil
}

// {{.Pkg}}Keys reads the row key{{if .HasParent}} and its parent id{{end}} out of state. The id is
// composite, so the attributes are the reliable source.
func {{.Pkg}}Keys(rs *terraform.ResourceState) ({{if .HasParent}}parentID, {{end}}key int64, err error) {
	key, err = strconv.ParseInt(rs.Primary.Attributes["{{.KeyTF}}"], 10, 64)
	if err != nil {
		return {{if .HasParent}}0, {{end}}0, fmt.Errorf("parsing {{.KeyTF}}: %w", err)
	}
{{- if .HasParent}}
	parentID, err = strconv.ParseInt(rs.Primary.Attributes["{{.ParentTF}}"], 10, 64)
	if err != nil {
		return 0, 0, fmt.Errorf("parsing {{.ParentTF}}: %w", err)
	}
{{- end}}
	return {{if .HasParent}}parentID, {{end}}key, nil
}

func testAccCheck{{.Pascal}}Exists(ctx context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		{{if .HasParent}}parentID, {{end}}key, err := {{.Pkg}}Keys(rs)
		if err != nil {
			return err
		}
		found, err := find{{.Pascal}}(ctx, {{if .HasParent}}parentID, {{end}}key)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("{{.TypeName}} row {{.KeyTF}}=%d not found", key)
		}
		return nil
	}
}

func testAccCheck{{.Pascal}}Destroy(ctx context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		for _, rs := range s.RootModule().Resources {
			if rs.Type != "{{.TypeName}}" {
				continue
			}

			{{if .HasParent}}parentID, {{end}}key, err := {{.Pkg}}Keys(rs)
			if err != nil {
				return err
			}
			// A deleted parent takes its rows with it, so a list that fails is
			// not proof the row survived.
			found, err := find{{.Pascal}}(ctx, {{if .HasParent}}parentID, {{end}}key)
			if err != nil {
				continue
			}
			if found {
				return fmt.Errorf("{{.TypeName}} row {{.KeyTF}}=%d still exists", key)
			}
		}
		return nil
	}
}

func testAcc{{.Pascal}}Config_basic({{if .BasicNeedsRName}}rName{{else}}_{{end}} string{{range .EnvArgs}}, {{.Param}} string{{end}}) string {
	return {{range .Fixtures}}acctest.{{.}}(rName) + {{end}}{{if .BasicUsesRName}}fmt.Sprintf(`
{{- if .Prereqs}}
{{.Prereqs}}
{{end}}
resource "{{.TypeName}}" "test" {
{{- range .CreateAttrs}}
  {{.Name}} = {{if .Quoted}}"{{.Value}}"{{else}}{{.Value}}{{end}}
{{- end}}
}
`, rName{{range .EnvArgs}}, {{.Param}}{{end}}{{range .ExtraArgs}}, {{.}}{{end}}){{else}}`
{{- if .Prereqs}}
{{.Prereqs}}
{{end}}
resource "{{.TypeName}}" "test" {
{{- range .CreateAttrs}}
  {{.Name}} = {{if .Quoted}}"{{.Value}}"{{else}}{{.Value}}{{end}}
{{- end}}
}
`{{end}}
}
{{if .HasUpdate}}
func testAcc{{.Pascal}}Config_update({{if .UpdateNeedsRName}}rName{{else}}_{{end}} string{{range .EnvArgs}}, {{.Param}} string{{end}}) string {
	return {{range .Fixtures}}acctest.{{.}}(rName) + {{end}}{{if .UpdateUsesRName}}fmt.Sprintf(`
{{- if .Prereqs}}
{{.Prereqs}}
{{end}}
resource "{{.TypeName}}" "test" {
{{- range .UpdateAttrs}}
  {{.Name}} = {{if .Quoted}}"{{.Value}}"{{else}}{{.Value}}{{end}}
{{- end}}
}
`, rName{{range .EnvArgs}}, {{.Param}}{{end}}{{range .ExtraArgs}}, {{.}}{{end}}){{else}}`
{{- if .Prereqs}}
{{.Prereqs}}
{{end}}
resource "{{.TypeName}}" "test" {
{{- range .UpdateAttrs}}
  {{.Name}} = {{if .Quoted}}"{{.Value}}"{{else}}{{.Value}}{{end}}
{{- end}}
}
`{{end}}
}
{{end}}
