// Code generated by kgen crud. DO NOT EDIT.

// Package {{.Pkg}} implements the Terraform resource for {{.Pkg}}: public ops go
// through the typed Kion SDK; private ops (the by-id read{{if .RawUpdate}}, update{{end}}{{if .RawDelete}}, delete{{end}})
// are absent from the SDK and are served over raw HTTP.
package {{.Pkg}}

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	{{if .RawRead.UsesAttr}}"github.com/hashicorp/terraform-plugin-framework/attr"
	{{end}}{{if .RawRead.Nested}}"github.com/hashicorp/terraform-plugin-framework/diag"
	{{end}}"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	{{.SDKAlias}} "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/conns"
	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const {{.ResConst}} = "{{.ResName}}"

var (
	_ resource.Resource                = &{{.Pkg}}Resource{}
	_ resource.ResourceWithConfigure   = &{{.Pkg}}Resource{}
	_ resource.ResourceWithImportState = &{{.Pkg}}Resource{}
)

// New{{.Pascal}}Resource returns a new instance of the resource.
func New{{.Pascal}}Resource() resource.Resource {
	return &{{.Pkg}}Resource{}
}

type {{.Pkg}}Resource struct {
	framework.ResourceWithConfigure
}

func (r *{{.Pkg}}Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{.Pkg}}"
}

func (r *{{.Pkg}}Resource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = {{.Pascal}}ResourceSchema(ctx)
}

{{if .RawRead.Nested}}
// {{.Pkg}}Wire is the private by-id read JSON shape (declared read_shape). Kion
// wraps the payload in {"data": …}.
{{.RawRead.WireStructGo}}

// read fetches the record over the private API; found is false on a 404.
func (r *{{.Pkg}}Resource) read(ctx context.Context, id int64) ({{.Pkg}}Wire, bool, error) {
	body, err := r.Meta().{{.RawRead.Method}}(ctx, strings.Replace("{{.RawRead.Path}}", "{id}", strconv.FormatInt(id, 10), 1))
	if err != nil {
		if conns.IsRawNotFound(err) {
			return {{.Pkg}}Wire{}, false, nil
		}
		return {{.Pkg}}Wire{}, false, err
	}
	var w {{.Pkg}}Wire
	if err := json.Unmarshal(body, &w); err != nil {
		return {{.Pkg}}Wire{}, false, fmt.Errorf("decoding response: %w", err)
	}
	return w, true, nil
}

func (r *{{.Pkg}}Resource) flatten(ctx context.Context, w {{.Pkg}}Wire, m *{{.Model}}) diag.Diagnostics {
	var diags diag.Diagnostics
	{{.RawRead.FlattenGo}}
	return diags
}
{{else}}{{with .RawRead}}
// {{$.Pkg}}Wire is the private read (and raw write) JSON shape; keys are the
// schema attribute names. Kion wraps the by-id read in {"data": …}.
type {{$.Pkg}}Wire struct {
	ID int64 `json:"id,omitempty"`
	{{- range .Fields}}
	{{.ModelGo}} {{.WireType}} `json:"{{.JSON}},omitempty"`
	{{- end}}
}

type {{$.Pkg}}ReadEnvelope struct {
	Data {{$.Pkg}}Wire `json:"data"`
}

func (r *{{$.Pkg}}Resource) wireFromModel(plan *{{$.Model}}) {{$.Pkg}}Wire {
	return {{$.Pkg}}Wire{
		{{- range .Fields}}
		{{.ModelGo}}: {{.FromExpr}},
		{{- end}}
	}
}

func (r *{{$.Pkg}}Resource) flatten(w {{$.Pkg}}Wire, m *{{$.Model}}) {
	m.{{.IDGo}} = types.StringValue(strconv.FormatInt(w.ID, 10))
	{{- range .Fields}}
	m.{{.ModelGo}} = {{.ToExpr}}
	{{- end}}
}

// read fetches the record over the private API; found is false on a 404.
func (r *{{$.Pkg}}Resource) read(ctx context.Context, id int64) ({{$.Pkg}}Wire, bool, error) {
	body, err := r.Meta().{{.Method}}(ctx, strings.Replace("{{.Path}}", "{id}", strconv.FormatInt(id, 10), 1))
	if err != nil {
		if conns.IsRawNotFound(err) {
			return {{$.Pkg}}Wire{}, false, nil
		}
		return {{$.Pkg}}Wire{}, false, err
	}
	var env {{$.Pkg}}ReadEnvelope
	if err := json.Unmarshal(body, &env); err != nil {
		return {{$.Pkg}}Wire{}, false, fmt.Errorf("decoding response: %w", err)
	}
	return env.Data, true, nil
}
{{end}}{{end}}
func (r *{{.Pkg}}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	conn := r.Meta().Client

	var plan {{.Model}}
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	{{range .CreateObjBinds}}{{.Var}} := {{$.SDKAlias}}.{{.SDKType}}{
		{{- range .Subs}}
		{{.SDKField}}: {{.Expr}},
		{{- end}}
	}
	{{if .Guard}}// Alternatives, not companions: send only the configured one.
	{{.Var}}Opt := {{$.SDKAlias}}.{{.OptType}}{}
	if !plan.{{.ModelGo}}.IsNull() {
		{{.Var}}Opt = {{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}
	}
	{{end}}{{end}}{{range .CreateArrBinds}}var {{.Var}} []{{$.SDKAlias}}.{{.ElemType}}
	var {{.Var}}Src []{{.ValueType}}
	resp.Diagnostics.Append(plan.{{.ModelGo}}.ElementsAs(ctx, &{{.Var}}Src, false)...)
	for _, elem := range {{.Var}}Src {
		{{.Var}} = append({{.Var}}, {{$.SDKAlias}}.{{.ElemType}}{
			{{- range .Subs}}
			{{.SDKField}}: {{.Expr}},
			{{- end}}
		})
	}
	{{end}}{{if or .CreateSliceBinds .CreateArrBinds}}{{range .CreateSliceBinds}}{{.Var}}, {{.Var}}Diags := {{.Func}}(ctx, plan.{{.ModelGo}})
	resp.Diagnostics.Append({{.Var}}Diags...)
	{{end}}if resp.Diagnostics.HasError() {
		return
	}

	{{end}}input := {{if .CreateBodyPtr}}&{{.SDKAlias}}.{{.CreateBody}}{
		{{- range .CreateBinds}}
		{{.SDKField}}: {{.Converter}}(plan.{{.ModelGo}}),
		{{- end}}
		{{- range .CreateSliceBinds}}
		{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
		{{- end}}
		{{- range .CreateObjBinds}}
		{{.SDKField}}: {{if .Guard}}{{.Var}}Opt{{else if .OptType}}{{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}{{else if .Ptr}}&{{.Var}}{{else}}{{.Var}}{{end}},
		{{- end}}
		{{- range .CreateArrBinds}}
		{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
		{{- end}}
		{{- range .CreateFlatSubs}}
		{{.SDKField}}: {{.Expr}},
		{{- end}}
	}{{else}}{{.SDKAlias}}.{{.CreateBodyOpt}}{
		Value: {{.SDKAlias}}.{{.CreateBody}}{
			{{- range .CreateBinds}}
			{{.SDKField}}: {{.Converter}}(plan.{{.ModelGo}}),
			{{- end}}
			{{- range .CreateSliceBinds}}
			{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
			{{- end}}
			{{- range .CreateObjBinds}}
			{{.SDKField}}: {{if .Guard}}{{.Var}}Opt{{else if .OptType}}{{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}{{else if .Ptr}}&{{.Var}}{{else}}{{.Var}}{{end}},
			{{- end}}
			{{- range .CreateArrBinds}}
			{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
			{{- end}}
			{{- range .CreateFlatSubs}}
			{{.SDKField}}: {{.Expr}},
			{{- end}}
		},
		Set: true,
	}{{end}}

	{{if .CreateParams}}out, err := conn.{{.CreateMethod}}(ctx, input, {{.SDKAlias}}.{{.CreateParams}}{{if .CreateParamField}}{ {{.CreateParamField}}: "{{.CreateParamLiteral}}" }{{else}}{}{{end}}){{else}}out, err := conn.{{.CreateMethod}}(ctx, input){{end}}
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", {{.ResConst}}), err.Error())
		return
	}

	{{if eq .CreateIDMode "envelope"}}created, ok := out.(*{{.SDKAlias}}.{{.CreateRespType}})
	if !ok || {{if .CreateDataPtr}}created.Data == nil{{else}}!created.Data.Set{{end}} {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("creating "+{{.ResConst}}, out)...)
		return
	}
	{{if .CreateIDOpt}}if !created.Data{{if not .CreateDataPtr}}.Value{{end}}.{{.CreateIDSDKName}}.Set {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", {{.ResConst}}), "the create response did not include an id")
		return
	}
	id := int64(created.Data{{if not .CreateDataPtr}}.Value{{end}}.{{.CreateIDSDKName}}.Value){{else}}id := int64(created.Data{{if not .CreateDataPtr}}.Value{{end}}.{{.CreateIDSDKName}}){{end}}{{else}}id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}{{end}}

	plan.{{.IDGo}} = types.StringValue(strconv.FormatInt(id, 10))

	// Read back over the private API to populate computed fields.
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", {{.ResConst}}, id), err.Error())
		return
	}
	if found {
		{{if .RawRead.Nested}}resp.Diagnostics.Append(r.flatten(ctx, w, &plan)...){{else}}r.flatten(w, &plan){{end}}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *{{.Pkg}}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	var state {{.Model}}
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.{{.IDGo}}.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", {{.ResConst}}, id), err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	{{if .RawRead.Nested}}resp.Diagnostics.Append(r.flatten(ctx, w, &state)...){{else}}r.flatten(w, &state){{end}}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
{{if .RawUpdate}}
func (r *{{.Pkg}}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	var plan {{.Model}}
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(plan.{{.IDGo}}.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	wire := r.wireFromModel(&plan)
	wire.ID = id
	body, err := json.Marshal(wire)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s", {{.ResConst}}), err.Error())
		return
	}
	if _, err := r.Meta().{{.RawUpdate.Method}}(ctx, strings.Replace("{{.RawUpdate.Path}}", "{id}", strconv.FormatInt(id, 10), 1), body); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", {{.ResConst}}, id), err.Error())
		return
	}
	w, found, err := r.read(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", {{.ResConst}}, id), err.Error())
		return
	}
	if found {
		{{if .RawRead.Nested}}resp.Diagnostics.Append(r.flatten(ctx, w, &plan)...){{else}}r.flatten(w, &plan){{end}}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
{{else if .HasUpdate}}
func (r *{{.Pkg}}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	conn := r.Meta().Client

	var plan {{.Model}}
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	{{range .UpdateObjBinds}}{{.Var}} := {{$.SDKAlias}}.{{.SDKType}}{
		{{- range .Subs}}
		{{.SDKField}}: {{.Expr}},
		{{- end}}
	}
	{{if .Guard}}// Alternatives, not companions: send only the configured one.
	{{.Var}}Opt := {{$.SDKAlias}}.{{.OptType}}{}
	if !plan.{{.ModelGo}}.IsNull() {
		{{.Var}}Opt = {{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}
	}
	{{end}}{{end}}{{range .UpdateArrBinds}}var {{.Var}} []{{$.SDKAlias}}.{{.ElemType}}
	var {{.Var}}Src []{{.ValueType}}
	resp.Diagnostics.Append(plan.{{.ModelGo}}.ElementsAs(ctx, &{{.Var}}Src, false)...)
	for _, elem := range {{.Var}}Src {
		{{.Var}} = append({{.Var}}, {{$.SDKAlias}}.{{.ElemType}}{
			{{- range .Subs}}
			{{.SDKField}}: {{.Expr}},
			{{- end}}
		})
	}
	{{end}}{{if or .UpdateSliceBinds .UpdateArrBinds}}{{range .UpdateSliceBinds}}{{.Var}}, {{.Var}}Diags := {{.Func}}(ctx, plan.{{.ModelGo}})
	resp.Diagnostics.Append({{.Var}}Diags...)
	{{end}}if resp.Diagnostics.HasError() {
		return
	}

	{{end}}input := {{if .UpdateBodyPtr}}&{{.SDKAlias}}.{{.UpdateBody}}{
		{{- range .UpdateBinds}}
		{{.SDKField}}: {{.Converter}}(plan.{{.ModelGo}}),
		{{- end}}
		{{- range .UpdateSliceBinds}}
		{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
		{{- end}}
		{{- range .UpdateObjBinds}}
		{{.SDKField}}: {{if .Guard}}{{.Var}}Opt{{else if .OptType}}{{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}{{else if .Ptr}}&{{.Var}}{{else}}{{.Var}}{{end}},
		{{- end}}
		{{- range .UpdateArrBinds}}
		{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
		{{- end}}
	}{{else}}{{.SDKAlias}}.{{.UpdateBodyOpt}}{
		Value: {{.SDKAlias}}.{{.UpdateBody}}{
			{{- range .UpdateBinds}}
			{{.SDKField}}: {{.Converter}}(plan.{{.ModelGo}}),
			{{- end}}
			{{- range .UpdateSliceBinds}}
			{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
			{{- end}}
			{{- range .UpdateObjBinds}}
			{{.SDKField}}: {{if .Guard}}{{.Var}}Opt{{else if .OptType}}{{$.SDKAlias}}.{{.OptType}}{Value: {{.Var}}, Set: true}{{else if .Ptr}}&{{.Var}}{{else}}{{.Var}}{{end}},
			{{- end}}
			{{- range .UpdateArrBinds}}
			{{.SDKField}}: {{if .Wrap}}{{$.SDKAlias}}.{{.Wrap}}{Value: {{.Var}}, Set: true}{{else}}{{.Var}}{{end}},
			{{- end}}
		},
		Set: true,
	}{{end}}

	idInt, err := strconv.{{if eq .IDParamType "uint64"}}ParseUint{{else}}ParseInt{{end}}(plan.{{.IDGo}}.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.{{.UpdateMethod}}(ctx, input, {{.SDKAlias}}.{{.UpdateParams}}{ {{.UpdateIDParam}}: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", {{.ResConst}}, idInt), err.Error())
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", {{.ResConst}}), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read back over the private API to get the latest state.
	w, found, err := r.read(ctx, {{if eq .IDParamType "uint64"}}int64(idInt){{else}}idInt{{end}})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", {{.ResConst}}, idInt), err.Error())
		return
	}
	if found {
		{{if .RawRead.Nested}}resp.Diagnostics.Append(r.flatten(ctx, w, &plan)...){{else}}r.flatten(w, &plan){{end}}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
{{else}}
func (r *{{.Pkg}}Resource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not supported", "{{.TypeName}} cannot be updated in place; changes force replacement.")
}
{{end}}
{{if .RawDelete}}
func (r *{{.Pkg}}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	var state {{.Model}}
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.{{.IDGo}}.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	if err := r.Meta().RawDelete(ctx, strings.Replace("{{.RawDelete.Path}}", "{id}", strconv.FormatInt(id, 10), 1)); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", {{.ResConst}}, id), err.Error())
		return
	}
}
{{else if .HasDelete}}
func (r *{{.Pkg}}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	{{- if .Gated}}
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "{{.TypeName}}")...)
	if resp.Diagnostics.HasError() {
		return
	}
	{{end}}
	conn := r.Meta().Client

	var state {{.Model}}
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.{{if eq .IDParamType "uint64"}}ParseUint{{else}}ParseInt{{end}}(state.{{.IDGo}}.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.{{.DeleteMethod}}(ctx, {{.SDKAlias}}.{{.DeleteParams}}{ {{.DeleteIDParam}}: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", {{.ResConst}}, idInt), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", {{.ResConst}}), out)
	resp.Diagnostics.Append(diags...)
}
{{else}}
func (r *{{.Pkg}}Resource) Delete(_ context.Context, _ resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning(
		"No delete API",
		"{{.TypeName}} has no delete endpoint, so it is removed from Terraform state only and may still exist in Kion.",
	)
}
{{end}}
func (r *{{.Pkg}}Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
