// Code generated by kgen crud. DO NOT EDIT.

package {{.Pkg}}

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	{{.SDKAlias}} "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/filter"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const (
	{{.DSConst}} = "{{.DSName}}"
	{{- if .Paginated}}

	// indexPageSize is the per-page count used when paginating {{.ListMethod}}.
	indexPageSize = 100
	{{- end}}
)

var (
	_ datasource.DataSource              = &{{.Pkg}}DataSource{}
	_ datasource.DataSourceWithConfigure = &{{.Pkg}}DataSource{}
)

// listObjectAttrTypes is the schema of an entry inside the `list` attribute.
var listObjectAttrTypes = map[string]attr.Type{
	{{- range .ObjFields}}
	"{{.TFName}}": {{.AttrType}},
	{{- end}}
}

// New{{.Pascal}}DataSource returns a new instance of the data source.
func New{{.Pascal}}DataSource() datasource.DataSource {
	return &{{.Pkg}}DataSource{}
}

type {{.Pkg}}DataSource struct {
	framework.DataSourceWithConfigure
}

func (d *{{.Pkg}}DataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{.Pkg}}"
}

// Schema is dual-mode: `id` fetches one by primary key; omitting `id` and
// supplying `filter` blocks paginates the index and returns every match in
// `list`. `id` and `filter` are mutually exclusive.
func (d *{{.Pkg}}DataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to access information about Kion {{.Pascal}}s. Supports lookup by id (recommended) or by filter blocks (legacy).",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of a single {{.Pkg}} to fetch. Mutually exclusive with `filter` blocks.",
				Optional:    true,
				Computed:    true,
			},
			{{- range .Attrs}}
			"{{.TFName}}": schema.{{.SchemaType}}{
				Computed: true,
			},
			{{- end}}
			{{- range .OuterAttrs}}
			"{{.TFName}}": schema.{{.SchemaType}}{
				Description: "Only populated when looking up by `id`; null in filter mode (the collection endpoint does not return it).",
				Computed:    true,
			},
			{{- end}}
			"list": schema.ListNestedAttribute{
				Description: "All {{.Pkg}}s matching the supplied id or filter blocks.",
				Computed:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						{{- range .ObjFields}}
						"{{.TFName}}": schema.{{.SchemaType}}{
							Computed: true,
						},
						{{- end}}
					},
				},
			},
		},
		Blocks: map[string]schema.Block{
			"filter": filter.Schema(),
		},
	}
}

func (d *{{.Pkg}}DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data {{.Pkg}}DataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idSet := !data.{{.IDGo}}.IsNull() && !data.{{.IDGo}}.IsUnknown()
	filterSet := len(data.Filter) > 0

	if idSet && filterSet {
		resp.Diagnostics.AddError(
			fmt.Sprintf("invalid %s configuration", {{.DSConst}}),
			"`id` and `filter` blocks are mutually exclusive.",
		)
		return
	}

	if idSet {
		d.readByID(ctx, conn, &data, &resp.Diagnostics)
	} else {
		d.readByFilter(ctx, conn, &data, &resp.Diagnostics)
	}

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *{{.Pkg}}DataSource) readByID(ctx context.Context, conn *{{.SDKAlias}}.Client, data *{{.Pkg}}DataSourceModel, diags *diag.Diagnostics) {
	out, err := conn.{{.ReadMethod}}(ctx, {{.SDKAlias}}.{{.ReadParams}}{ {{.ReadIDParam}}: {{if eq .IDParamType "uint64"}}uint64(data.{{.IDGo}}.ValueInt64()){{else}}data.{{.IDGo}}.ValueInt64(){{end}}})
	if err != nil {
		diags.AddError(fmt.Sprintf("reading %s", {{.DSConst}}), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		diags.AddError(fmt.Sprintf("reading %s", {{.DSConst}}), "{{.Pkg}} not found")
		return
	}
	api, ok := out.(*{{.SDKAlias}}.{{.RespType}})
	if !ok || !api.Data.Set {
		diags.Append(errs.ResponseDiagnostics("reading "+{{.DSConst}}, out)...)
		return
	}

	lbl := api.Data.Value{{.PayloadPath}}
	{{- range .Assigns}}
	data.{{.ModelGo}} = {{.Flatten}}(lbl.{{.SDKGo}})
	{{- end}}
	{{- range .OuterAttrs}}
	data.{{.ModelGo}} = {{.Flatten}}({{$.PayloadExpr}}.{{.SDKGo}})
	{{- end}}

	listVal, listDiags := build{{.Pascal}}List(ctx, []{{.SDKAlias}}.{{.ElemType}}{lbl})
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal
}

func (d *{{.Pkg}}DataSource) readByFilter(ctx context.Context, conn *{{.SDKAlias}}.Client, data *{{.Pkg}}DataSourceModel, diags *diag.Diagnostics) {
	all, fetchDiags := fetchAll{{.Pascal}}(ctx, conn)
	diags.Append(fetchDiags...)
	if diags.HasError() {
		return
	}

	matched := make([]{{.SDKAlias}}.{{.ElemType}}, 0, len(all))
	for _, lbl := range all {
		ok, matchDiags := filter.Match(ctx, data.Filter, {{.Pkg}}ToRow(lbl))
		diags.Append(matchDiags...)
		if diags.HasError() {
			return
		}
		if ok {
			matched = append(matched, lbl)
		}
	}

	listVal, listDiags := build{{.Pascal}}List(ctx, matched)
	diags.Append(listDiags...)
	if diags.HasError() {
		return
	}
	data.List = listVal

	// Scalar fields stay null in filter mode.
	{{- range .Assigns}}
	data.{{.ModelGo}} = {{.NullExpr}}
	{{- end}}
	{{- range .OuterAttrs}}
	data.{{.ModelGo}} = {{.NullExpr}}
	{{- end}}
}

{{if .Paginated -}}
// fetchAll{{.Pascal}} paginates {{.ListMethod}} and returns the full set.
{{- else -}}
// fetchAll{{.Pascal}} returns the full set from {{.ListMethod}}, which is not
// paginated: one call yields the whole collection.
{{- end}}
func fetchAll{{.Pascal}}(ctx context.Context, conn *{{.SDKAlias}}.Client) ([]{{.SDKAlias}}.{{.ElemType}}, diag.Diagnostics) {
	var diags diag.Diagnostics
	var all []{{.SDKAlias}}.{{.ElemType}}

{{ if .Paginated -}}
	page := int64(1)
	for {
		out, err := conn.{{.ListMethod}}(ctx, {{.SDKAlias}}.{{.ListParams}}{
			{{.PageParam}}:  {{.SDKAlias}}.NewOptInt64(page),
			{{.CountParam}}: {{.SDKAlias}}.NewOptInt64(int64(indexPageSize)),
		})
		if err != nil {
			diags.AddError(fmt.Sprintf("listing %s", {{.DSConst}}), err.Error())
			return nil, diags
		}
		resp, ok := out.(*{{.SDKAlias}}.{{.ListRespType}})
		if !ok {
			diags.Append(errs.ResponseDiagnostics("listing "+{{.DSConst}}, out)...)
			return nil, diags
		}
		{{- if .EnvelopeGuard}}
		if !{{.EnvelopeGuard}} {
			break
		}
		{{- end}}
		items := {{.ItemsExpr}}
		{{- if .ItemsGuard}}
		if {{.ItemsGuard}} {
			all = append(all, {{.ItemsSlice}}...)
		}
		{{- else}}
		all = append(all, {{.ItemsSlice}}...)
		{{- end}}
		{{- if .TotalExpr}}
		total := int64(0)
		if {{.TotalExpr}}.Set {
			total = {{.TotalExpr}}.Value
		}
		if total > 0 && int64(len(all)) >= total {
			break
		}
		{{- end}}
		if {{.ItemsBreak}} {
			break
		}
		page++
	}
{{- else}}
	out, err := conn.{{.ListMethod}}(ctx{{if .HasParams}}, {{.SDKAlias}}.{{.ListParams}}{}{{end}})
	if err != nil {
		diags.AddError(fmt.Sprintf("listing %s", {{.DSConst}}), err.Error())
		return nil, diags
	}
	resp, ok := out.(*{{.SDKAlias}}.{{.ListRespType}})
	if !ok {
		diags.Append(errs.ResponseDiagnostics("listing "+{{.DSConst}}, out)...)
		return nil, diags
	}
	{{- if .EnvelopeGuard}}
	if !{{.EnvelopeGuard}} {
		return all, diags
	}
	{{- end}}
	items := {{.ItemsExpr}}
	{{- if .ItemsGuard}}
	if {{.ItemsGuard}} {
		all = append(all, {{.ItemsSlice}}...)
	}
	{{- else}}
	all = append(all, {{.ItemsSlice}}...)
	{{- end}}
{{- end}}

	return all, diags
}

// {{.Pkg}}ToRow converts an element into the map filter.Match expects.
func {{.Pkg}}ToRow(lbl {{.SDKAlias}}.{{.ElemType}}) map[string]any {
	row := map[string]any{
		{{- range .ObjFields}}
		{{- if not .IsID}}
		"{{.TFName}}": {{.RowExpr}},
		{{- end}}
		{{- end}}
	}
	{{- range .ObjFields}}
	{{- if .IsID}}
	if lbl.{{.SDKGo}}.Set {
		row["{{.TFName}}"] = int64(lbl.{{.SDKGo}}.Value)
	}
	{{- end}}
	{{- end}}
	return row
}

// build{{.Pascal}}List converts elements into a types.List of objects.
func build{{.Pascal}}List(ctx context.Context, items []{{.SDKAlias}}.{{.ElemType}}) (types.List, diag.Diagnostics) {
	objs := make([]attr.Value, 0, len(items))
	for _, lbl := range items {
		{{- range .ObjFields}}
		{{- if .IsID}}
		idVal := types.Int64Null()
		if lbl.{{.SDKGo}}.Set {
			idVal = types.Int64Value(int64(lbl.{{.SDKGo}}.Value))
		}
		{{- end}}
		{{- end}}
		obj, objDiags := types.ObjectValue(listObjectAttrTypes, map[string]attr.Value{
			{{- range .ObjFields}}
			{{- if .IsID}}
			"{{.TFName}}": idVal,
			{{- else}}
			"{{.TFName}}": {{.ObjExpr}},
			{{- end}}
			{{- end}}
		})
		if objDiags.HasError() {
			return types.ListNull(types.ObjectType{AttrTypes: listObjectAttrTypes}), objDiags
		}
		objs = append(objs, obj)
	}
	return types.ListValueFrom(ctx, types.ObjectType{AttrTypes: listObjectAttrTypes}, objs)
}

type {{.Pkg}}DataSourceModel struct {
	{{.IDGo}} types.Int64 `tfsdk:"id"`
	{{- range .Attrs}}
	{{.ModelGo}} {{.ModelType}} `tfsdk:"{{.TFName}}"`
	{{- end}}
	{{- range .OuterAttrs}}
	{{.ModelGo}} {{.ModelType}} `tfsdk:"{{.TFName}}"`
	{{- end}}
	Filter []filter.Model `tfsdk:"filter"`
	List   types.List     `tfsdk:"list"`
}
