package crud

import (
	"bytes"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

// labelResourceModel builds a ResourceModel for label from the testdata
// fixtures, so the entity render test exercises the real resolution path.
func labelResourceModel(t *testing.T) ResourceModel {
	t.Helper()
	idx := fixtureIndex(t)
	model, err := NewFileSource().ModelFields("testdata/label_schema_gen.go", "LabelModel")
	if err != nil {
		t.Fatal(err)
	}
	rm, err := resolveResource("label", labelOps(), labelDS(), idx, model)
	if err != nil {
		t.Fatalf("resolveResource: %v", err)
	}
	return rm
}

func TestRenderEntity_gatedAndNoUpdate(t *testing.T) {
	rm := labelResourceModel(t)
	rm.Gated = true
	rm.Update = nil
	got, err := renderEntity(rm)
	if err != nil {
		t.Fatalf("renderEntity: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "x.go", got, parser.ParseComments); err != nil {
		t.Fatalf("does not parse: %v\n%s", err, got)
	}
	for _, w := range []string{
		`framework.RequireKionVersionInRange(r.Meta(), minKionVersion, maxKionVersion, "kion_label")`,
		"cannot be updated in place; changes force replacement.",
	} {
		if !bytes.Contains(got, []byte(w)) {
			t.Errorf("missing %q", w)
		}
	}
}

func TestIDParamName_types(t *testing.T) {
	n, ty, err := idParamName(&Struct{Name: "P", Fields: []Field{{GoName: "ID", Type: "uint64"}}})
	if err != nil || n != "ID" || ty != "uint64" {
		t.Fatalf("uint64: got %q,%q,%v", n, ty, err)
	}
	n, ty, err = idParamName(&Struct{Name: "P", Fields: []Field{{GoName: "ID", Type: "int64"}}})
	if err != nil || n != "ID" || ty != "int64" {
		t.Fatalf("int64: got %q,%q,%v", n, ty, err)
	}
	if _, _, err := idParamName(&Struct{Name: "P", Fields: []Field{{GoName: "ID", Type: "string"}}}); err == nil {
		t.Fatal("want error for non-int id param")
	}
}

func TestRenderEntity_label(t *testing.T) {
	got, err := renderEntity(labelResourceModel(t))
	if err != nil {
		t.Fatalf("renderEntity: %v", err)
	}

	// Semantic fidelity: it must parse as Go and call the same SDK ops / map
	// the same fields as the golden hand-written label.go.
	if _, err := parser.ParseFile(token.NewFileSet(), "label.go", got, parser.ParseComments); err != nil {
		t.Fatalf("generated label.go does not parse: %v\n%s", err, got)
	}

	wants := []string{
		"// Code generated by kgen crud. DO NOT EDIT.",
		"package label",
		"func (r *labelResource) Create(",
		"func (r *labelResource) Read(",
		"func (r *labelResource) Update(",
		"func (r *labelResource) Delete(",
		"func (r *labelResource) ImportState(",
		"conn.PostLabel(ctx, input)",
		"errs.CreatedID(out)",
		"generated.GetLabelParams{ID: id}",
		"generated.GetLabelParams{ID: idInt}",
		"conn.PatchLabel(ctx, input, generated.PatchLabelParams{ID: idInt})",
		"conn.DeleteLabel(ctx, generated.DeleteLabelParams{ID: idInt})",
		"errs.IsNotFound(out)",
		"resp.State.RemoveResource(ctx)",
		"flex.StringValueFromFramework(plan.Key)",
		"flex.OptStringFromFramework(plan.Key)",
		"func flattenLabel(",
		"strconv.FormatUint(v.Data.Value.ID.Value, 10)",
		"flex.StringToFramework(v.Data.Value.Key)",
	}
	for _, w := range wants {
		if !bytes.Contains(got, []byte(w)) {
			t.Errorf("generated label.go missing %q", w)
		}
	}
}

// TestRenderEntity_deterministic guards byte-stable output. Refresh the golden
// with: UPDATE_GOLDEN=1 go test ./internal/kgen/crud/ -run TestRenderEntity_deterministic
func TestRenderEntity_deterministic(t *testing.T) {
	rm := labelResourceModel(t)
	got, err := renderEntity(rm)
	if err != nil {
		t.Fatalf("renderEntity: %v", err)
	}
	golden := filepath.Join("testdata", "golden", "label.go.golden")
	if os.Getenv("UPDATE_GOLDEN") != "" {
		if err := os.MkdirAll(filepath.Dir(golden), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, got, 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run with UPDATE_GOLDEN=1 to create): %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("render drifted from golden; re-run with UPDATE_GOLDEN=1 if intentional")
	}
}

func TestIDOptKind(t *testing.T) {
	cases := map[string]struct{ opt, ok bool }{
		"OptUint64": {true, true},
		"OptInt64":  {true, true},
		"uint64":    {false, true},
		"int64":     {false, true},
		"string":    {false, false},
		"OptString": {false, false},
	}
	for typ, want := range cases {
		opt, ok := idOptKind(typ)
		if opt != want.opt || ok != want.ok {
			t.Errorf("idOptKind(%q) = (%v,%v), want (%v,%v)", typ, opt, ok, want.opt, want.ok)
		}
	}
}
