// Code generated by kgen crud. DO NOT EDIT.

// Package service_catalog implements the Terraform resource and data source for service_catalog.
package service_catalog

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/resourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameServiceCatalog = "ServiceCatalog"

var (
	_ resource.Resource                     = &service_catalogResource{}
	_ resource.ResourceWithConfigure        = &service_catalogResource{}
	_ resource.ResourceWithImportState      = &service_catalogResource{}
	_ resource.ResourceWithConfigValidators = &service_catalogResource{}
)

// NewServiceCatalogResource returns a new instance of the resource.
func NewServiceCatalogResource() resource.Resource {
	return &service_catalogResource{}
}

type service_catalogResource struct {
	framework.ResourceWithConfigure
}

func (r *service_catalogResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_catalog"
}

// ConfigValidators expresses a constraint the API enforces across attributes,
// which the schema cannot: neither attribute is Required on its own, so without
// this the configuration reaches the API and comes back as a validation error
// naming the Go struct field rather than the Terraform attribute.
func (r *service_catalogResource) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		resourcevalidator.AtLeastOneOf(
			path.MatchRoot("owner_user_group_ids"),
			path.MatchRoot("owner_user_ids"),
		),
	}
}

func (r *service_catalogResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Schema is generated from the OpenAPI spec (service_catalog_schema_gen.go); the
	// bits the spec can't express come from codegen/schema_overrides.yaml.
	resp.Schema = ServiceCatalogResourceSchema(ctx)
}

func (r *service_catalogResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan ServiceCatalogModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ownerUserGroupIds, ownerUserGroupIdsDiags := flex.Uint64SliceFromFrameworkSet(ctx, plan.OwnerUserGroupIds)
	resp.Diagnostics.Append(ownerUserGroupIdsDiags...)
	ownerUserIds, ownerUserIdsDiags := flex.Uint64SliceFromFrameworkSet(ctx, plan.OwnerUserIds)
	resp.Diagnostics.Append(ownerUserIdsDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.ServiceCatalogPortfolioCreate{
		AccountID:         flex.NilUint64FromFramework(plan.AccountId),
		Description:       flex.OptStringFromFramework(plan.Description),
		Name:              flex.StringValueFromFramework(plan.Name),
		PortfolioID:       flex.StringValueFromFramework(plan.PortfolioId),
		Region:            flex.StringValueFromFramework(plan.Region),
		TagOption:         flex.OptNilBoolFromFramework(plan.TagOption),
		OwnerUserGroupIds: generated.OptNilUint64Array{Value: ownerUserGroupIds, Set: true},
		OwnerUserIds:      generated.OptNilUint64Array{Value: ownerUserIds, Set: true},
	}

	out, err := conn.PostServiceCatalogPortfolio(ctx, input)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameServiceCatalog), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back the resource to populate computed fields.
	readOut, readErr := conn.GetServiceCatalog(ctx, generated.GetServiceCatalogParams{ID: id})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameServiceCatalog, id), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenServiceCatalog(ctx, readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(flex.ResolveUnknowns(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *service_catalogResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	conn := r.Meta().Client

	var state ServiceCatalogModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.GetServiceCatalog(ctx, generated.GetServiceCatalogParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameServiceCatalog, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenServiceCatalog(ctx, out, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *service_catalogResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan ServiceCatalogModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	input := &generated.ServiceCatalogPortfolioUpdate{
		AccountID:   flex.OptNilUint64FromFramework(plan.AccountId),
		Description: flex.OptStringFromFramework(plan.Description),
		Name:        flex.OptStringFromFramework(plan.Name),
		PortfolioID: flex.OptStringFromFramework(plan.PortfolioId),
		Region:      flex.OptStringFromFramework(plan.Region),
		TagOption:   flex.OptNilBoolFromFramework(plan.TagOption),
	}

	out, err := conn.PatchServiceCatalogPortfolio(ctx, input, generated.PatchServiceCatalogPortfolioParams{ID: idInt})
	// A 2xx the spec does not declare arrives as a decode error even though the
	// write landed; the read-back below is the authority on state either way.
	// See errs.IsUndeclaredSuccess.
	if err != nil && !errs.IsUndeclaredSuccess(err) {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameServiceCatalog, idInt), err.Error())
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameServiceCatalog), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read back the resource to get the latest state.
	readOut, readErr := conn.GetServiceCatalog(ctx, generated.GetServiceCatalogParams{ID: idInt})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameServiceCatalog, idInt), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenServiceCatalog(ctx, readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(flex.ResolveUnknowns(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// The public spec publishes no delete; this is the private route, declared in
// codegen/private_endpoints.yaml. Reached over raw HTTP because the SDK is
// generated from the public spec and so has no method for it.
func (r *service_catalogResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ServiceCatalogModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}
	if err := r.Meta().RawDelete(ctx, strings.Replace("/v2/aws-service-catalog/portfolio/{id}", "{id}", strconv.FormatInt(id, 10), 1)); err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameServiceCatalog, id), err.Error())
		return
	}
}

func (r *service_catalogResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

func flattenServiceCatalog(ctx context.Context, apiObject any, model *ServiceCatalogModel) diag.Diagnostics {
	var diags diag.Diagnostics
	switch v := apiObject.(type) {
	case *generated.ServiceCatalogPortfolioResponse:
		if v.Data.Set {
			model.AccountId = flex.OptNilUint64ToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.AccountID)
			model.Description = flex.OptStringToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.Description)
			if v.Data.Value.ServiceCatalogPortfolio.Value.ID.Set {
				model.Id = types.StringValue(strconv.FormatUint(v.Data.Value.ServiceCatalogPortfolio.Value.ID.Value, 10))
			}
			model.Name = flex.OptStringToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.Name)
			model.PortfolioId = flex.OptStringToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.PortfolioID)
			model.Region = flex.OptStringToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.Region)
			model.TagOption = flex.OptNilBoolToFramework(v.Data.Value.ServiceCatalogPortfolio.Value.TagOption)
			var ownerUserGroupsIDs []int64
			for _, elem := range v.Data.Value.OwnerUserGroups.Value {
				if elem.ID.Set {
					ownerUserGroupsIDs = append(ownerUserGroupsIDs, int64(elem.ID.Value))
				}
			}
			// A Set rejects duplicate elements, and the API does return an owner
			// twice on some records; three imports failed outright on this.
			ownerUserGroupsIDs = flex.DedupeInt64(ownerUserGroupsIDs)
			ownerUserGroupsIDsColl, ownerUserGroupsIDsCD := types.SetValueFrom(ctx, types.Int64Type, ownerUserGroupsIDs)
			diags.Append(ownerUserGroupsIDsCD...)
			model.OwnerUserGroupIds = ownerUserGroupsIDsColl
			var ownerUsersIDs []int64
			for _, elem := range v.Data.Value.OwnerUsers.Value {
				if elem.ID.Set {
					ownerUsersIDs = append(ownerUsersIDs, int64(elem.ID.Value))
				}
			}
			// A Set rejects duplicate elements, and the API does return an owner
			// twice on some records; three imports failed outright on this.
			ownerUsersIDs = flex.DedupeInt64(ownerUsersIDs)
			ownerUsersIDsColl, ownerUsersIDsCD := types.SetValueFrom(ctx, types.Int64Type, ownerUsersIDs)
			diags.Append(ownerUsersIDsCD...)
			model.OwnerUserIds = ownerUsersIDsColl
		}
		return diags
	default:
		return errs.ResponseDiagnostics("reading "+ResNameServiceCatalog, apiObject)
	}
}
