// Code generated by kgen crud. DO NOT EDIT.

// Package gcp_account implements the Terraform resource and data source for gcp_account.
package gcp_account

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameGcpAccount = "GcpAccount"

var (
	_ resource.Resource                = &gcp_accountResource{}
	_ resource.ResourceWithConfigure   = &gcp_accountResource{}
	_ resource.ResourceWithImportState = &gcp_accountResource{}
)

// NewGcpAccountResource returns a new instance of the resource.
func NewGcpAccountResource() resource.Resource {
	return &gcp_accountResource{}
}

type gcp_accountResource struct {
	framework.ResourceWithConfigure
}

func (r *gcp_accountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gcp_account"
}

func (r *gcp_accountResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Schema is generated from the OpenAPI spec (gcp_account_schema_gen.go); the
	// bits the spec can't express come from codegen/schema_overrides.yaml.
	resp.Schema = GcpAccountResourceSchema(ctx)
	resp.Schema.Version = 1
}

func (r *gcp_accountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan GcpAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.GoogleCloudAccountCreate{
		AccountAlias:         flex.OptStringFromFramework(plan.AccountAlias),
		AccountName:          flex.StringValueFromFramework(plan.AccountName),
		AccountTypeID:        flex.OptNilUint64FromFramework(plan.AccountTypeId),
		GoogleCloudProjectID: flex.StringValueFromFramework(plan.GoogleCloudProjectId),
		PayerID:              flex.NilUint64FromFramework(plan.PayerId),
		ProjectID:            flex.NilUint64FromFramework(plan.ProjectId),
		SkipAccessChecking:   flex.OptNilBoolFromFramework(plan.SkipAccessChecking),
		StartDatecode:        flex.StringValueFromFramework(plan.StartDatecode),
	}

	out, err := conn.PostGoogleCloudAccount(ctx, input, generated.PostGoogleCloudAccountParams{AccountType: "google-cloud"})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameGcpAccount), err.Error())
		return
	}

	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	// Read back the resource to populate computed fields.
	readOut, readErr := conn.GetAccount(ctx, generated.GetAccountParams{ID: id})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameGcpAccount, id), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenGcpAccount(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gcp_accountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	conn := r.Meta().Client

	var state GcpAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.GetAccount(ctx, generated.GetAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameGcpAccount, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(flattenGcpAccount(out, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *gcp_accountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan GcpAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := &generated.AccountUpdatable{
		AccountAlias:       flex.OptStringFromFramework(plan.AccountAlias),
		AccountName:        flex.OptStringFromFramework(plan.AccountName),
		SkipAccessChecking: flex.OptNilBoolFromFramework(plan.SkipAccessChecking),
		StartDatecode:      flex.OptStringFromFramework(plan.StartDatecode),
	}

	idInt, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.PatchAccount(ctx, input, generated.PatchAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameGcpAccount, idInt), err.Error())
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameGcpAccount), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read back the resource to get the latest state.
	readOut, readErr := conn.GetAccount(ctx, generated.GetAccountParams{ID: idInt})
	if readErr != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameGcpAccount, idInt), readErr.Error())
		return
	}

	resp.Diagnostics.Append(flattenGcpAccount(readOut, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gcp_accountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state GcpAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	idInt, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteAccount(ctx, generated.DeleteAccountParams{ID: idInt})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameGcpAccount, idInt), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		return
	}

	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameGcpAccount), out)
	resp.Diagnostics.Append(diags...)
}

func (r *gcp_accountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}

func flattenGcpAccount(apiObject any, model *GcpAccountModel) diag.Diagnostics {
	switch v := apiObject.(type) {
	case *generated.AccountResponse:
		if v.Data.Set {
			model.AccountAlias = flex.OptStringToFramework(v.Data.Value.AccountAlias)
			model.AccountName = flex.OptStringToFramework(v.Data.Value.AccountName)
			model.AccountTypeId = flex.OptNilUint64ToFramework(v.Data.Value.AccountTypeID)
			if v.Data.Value.ID.Set {
				model.Id = types.StringValue(strconv.FormatUint(v.Data.Value.ID.Value, 10))
			}
			model.PayerId = flex.OptNilUint64ToFramework(v.Data.Value.PayerID)
			model.ProjectId = flex.OptNilUint64ToFramework(v.Data.Value.ProjectID)
			model.SkipAccessChecking = flex.OptNilBoolToFramework(v.Data.Value.SkipAccessChecking)
			model.StartDatecode = flex.OptStringToFramework(v.Data.Value.StartDatecode)
		}
		return nil
	default:
		return errs.ResponseDiagnostics("reading "+ResNameGcpAccount, apiObject)
	}
}
