// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package label

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LabelResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"color": schema.StringAttribute{
				Required:            true,
				Description:         "Hex value of the label color",
				MarkdownDescription: "Hex value of the label color",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the label.",
				MarkdownDescription: "The ID of the label.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"key": schema.StringAttribute{
				Required:            true,
				Description:         "Key of the label (first part of the label)",
				MarkdownDescription: "Key of the label (first part of the label)",
			},
			"value": schema.StringAttribute{
				Required:            true,
				Description:         "Value of the label (second part of the label following the key)",
				MarkdownDescription: "Value of the label (second part of the label following the key)",
			},
		},
		Description: "Manages a Kion Label.",
	}
}

type LabelModel struct {
	Color types.String `tfsdk:"color"`
	Id    types.String `tfsdk:"id"`
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}
