# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_billing_source_gcp" "this" {
  account_type_id            = var.account_type_id
  gcp_billing_account_create = var.gcp_billing_account_create
}
