# Generated by `kgen module` from the provider schema. Do not edit.

variable "idms_type_id" {
  description = "ID of the IDMS type in the application. 1 is Internal Directory, 2 is Active Directory, 3 is SAML."
  type        = number
}

variable "name" {
  description = "Name of the IDMS in the application."
  type        = string
}

variable "password_expiration" {
  description = "Number of days until a password reset dialog displays on login."
  type        = number
}
