// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package azure_account

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AzureAccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_alias": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Alias of the account in the application.",
				MarkdownDescription: "Alias of the account in the application.",
			},
			"account_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the account in the application.",
				MarkdownDescription: "Name of the account in the application.",
			},
			"account_type_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Account Type ID is the corresponding account's type.\n3 - Azure CSP Standard\n6 - Azure EA\n7 - Azure EA Government\n8 - Azure CSP Standard Resource Group\n9 - Azure EA Resource Group\n10 - Azure EA Government Resource Group\n11 - Azure CSP Government\n12 - Azure CSP Government Resource Group\nWill default to 3 if not given.",
				MarkdownDescription: "The Account Type ID is the corresponding account's type.\n3 - Azure CSP Standard\n6 - Azure EA\n7 - Azure EA Government\n8 - Azure CSP Standard Resource Group\n9 - Azure EA Resource Group\n10 - Azure EA Government Resource Group\n11 - Azure CSP Government\n12 - Azure CSP Government Resource Group\nWill default to 3 if not given.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Account ID.",
				MarkdownDescription: "Account ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"payer_id": schema.Int64Attribute{
				Required:            true,
				Description:         "ID of the payer (aka Azure Tenant) where this subscription can be found",
				MarkdownDescription: "ID of the payer (aka Azure Tenant) where this subscription can be found",
			},
			"project_id": schema.Int64Attribute{
				Required:            true,
				Description:         "ID of the project where the account is attached.",
				MarkdownDescription: "ID of the project where the account is attached.",
			},
			"skip_access_checking": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, the application does not perform periodic access validation. Default is false.",
				MarkdownDescription: "When true, the application does not perform periodic access validation. Default is false.",
			},
			"start_datecode": schema.StringAttribute{
				Required:            true,
				Description:         "Date when the Azure subscription will begin submitting payments against a funding source (YYYY-MM)",
				MarkdownDescription: "Date when the Azure subscription will begin submitting payments against a funding source (YYYY-MM)",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^\\d{4}-(?:0[1-9]|1[0-2])$"), ""),
				},
			},
			"subscription_uuid": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Azure Subscription UUID.",
				MarkdownDescription: "Azure Subscription UUID.",
			},
		},
		Description: "Manages a Kion Azure Account.",
	}
}

type AzureAccountModel struct {
	AccountAlias       types.String `tfsdk:"account_alias"`
	AccountName        types.String `tfsdk:"account_name"`
	AccountTypeId      types.Int64  `tfsdk:"account_type_id"`
	Id                 types.String `tfsdk:"id"`
	PayerId            types.Int64  `tfsdk:"payer_id"`
	ProjectId          types.Int64  `tfsdk:"project_id"`
	SkipAccessChecking types.Bool   `tfsdk:"skip_access_checking"`
	StartDatecode      types.String `tfsdk:"start_datecode"`
	SubscriptionUuid   types.String `tfsdk:"subscription_uuid"`
}
