# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_gcp_iam_role" "this" {
  car_restricted_user_group_ids = var.car_restricted_user_group_ids
  car_restricted_user_ids       = var.car_restricted_user_ids
  description                   = var.description
  gcp_role_launch_stage         = var.gcp_role_launch_stage
  name                          = var.name
  owner_user_group_ids          = var.owner_user_group_ids
  owner_user_ids                = var.owner_user_ids
  role_denials                  = var.role_denials
  role_permissions              = var.role_permissions
}
