// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package user_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UserGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"add_self_as_viewer": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "This option will add the user group as a viewer of itself after it is created.",
				MarkdownDescription: "This option will add the user group as a viewer of itself after it is created.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "When the user group was created.",
				MarkdownDescription: "When the user group was created.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the user group in the application.",
				MarkdownDescription: "Description of the user group in the application.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the user group is enabled.",
				MarkdownDescription: "Whether the user group is enabled.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "User group ID.",
				MarkdownDescription: "User group ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"idms_id": schema.Int64Attribute{
				Required:            true,
				Description:         "ID of the IDMS where the user group is located.",
				MarkdownDescription: "ID of the IDMS where the user group is located.",
			},
			"last_updated": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The last time this resource was updated.",
				MarkdownDescription: "The last time this resource was updated.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the user group in the application.",
				MarkdownDescription: "Name of the user group in the application.",
			},
			"owner_user_group_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of groups IDs who will own the group. Is required if no owner user IDs are listed.",
				MarkdownDescription: "List of groups IDs who will own the group. Is required if no owner user IDs are listed.",
			},
			"owner_user_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of user IDs who will own the group. Is required if no owner group IDs are listed.",
				MarkdownDescription: "List of user IDs who will own the group. Is required if no owner group IDs are listed.",
			},
			"user_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of the users in the user group.",
				MarkdownDescription: "IDs of the users in the user group.",
			},
			"viewer_user_group_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of groups IDs who will own the group. Is required if no owner user IDs are listed.",
				MarkdownDescription: "List of groups IDs who will own the group. Is required if no owner user IDs are listed.",
			},
			"viewer_user_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "List of user IDs who will own the group. Is required if no owner group IDs are listed.",
				MarkdownDescription: "List of user IDs who will own the group. Is required if no owner group IDs are listed.",
			},
		},
		Description: "Manages a Kion User Group.",
	}
}

type UserGroupModel struct {
	AddSelfAsViewer    types.Bool   `tfsdk:"add_self_as_viewer"`
	CreatedAt          types.String `tfsdk:"created_at"`
	Description        types.String `tfsdk:"description"`
	Enabled            types.Bool   `tfsdk:"enabled"`
	Id                 types.String `tfsdk:"id"`
	IdmsId             types.Int64  `tfsdk:"idms_id"`
	LastUpdated        types.String `tfsdk:"last_updated"`
	Name               types.String `tfsdk:"name"`
	OwnerUserGroupIds  types.List   `tfsdk:"owner_user_group_ids"`
	OwnerUserIds       types.List   `tfsdk:"owner_user_ids"`
	UserIds            types.List   `tfsdk:"user_ids"`
	ViewerUserGroupIds types.List   `tfsdk:"viewer_user_group_ids"`
	ViewerUserIds      types.List   `tfsdk:"viewer_user_ids"`
}
