// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package custom_variable_override

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CustomVariableOverrideResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_variable_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the custom variable.",
				MarkdownDescription: "The ID of the custom variable.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"entity_id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the entity.",
				MarkdownDescription: "The ID of the entity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"entity_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of the entity.",
				MarkdownDescription: "The type of the entity.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Custom Variable Override.",
				MarkdownDescription: "The ID of the Custom Variable Override.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_updated": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The last time this resource was updated.",
				MarkdownDescription: "The last time this resource was updated.",
			},
			"value_list": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The value of the custom variable override as a list.",
				MarkdownDescription: "The value of the custom variable override as a list.",
			},
			"value_map": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The value of the custom variable override as a map.",
				MarkdownDescription: "The value of the custom variable override as a map.",
			},
			"value_string": schema.StringAttribute{
				Optional:            true,
				Description:         "The value of the custom variable override as a string.",
				MarkdownDescription: "The value of the custom variable override as a string.",
			},
		},
		Description: "Manages a Kion Custom Variable Override.",
	}
}

type CustomVariableOverrideModel struct {
	CustomVariableId types.String `tfsdk:"custom_variable_id"`
	EntityId         types.String `tfsdk:"entity_id"`
	EntityType       types.String `tfsdk:"entity_type"`
	Id               types.String `tfsdk:"id"`
	LastUpdated      types.String `tfsdk:"last_updated"`
	ValueList        types.List   `tfsdk:"value_list"`
	ValueMap         types.Map    `tfsdk:"value_map"`
	ValueString      types.String `tfsdk:"value_string"`
}
