package provider

import (
	"terraform-provider-kion/internal/conns"
	"terraform-provider-kion/internal/service/account"
	"terraform-provider-kion/internal/service/account_cache"
	"terraform-provider-kion/internal/service/account_linkage"
	"terraform-provider-kion/internal/service/ami"
	"terraform-provider-kion/internal/service/app_api_key"
	"terraform-provider-kion/internal/service/app_config"
	"terraform-provider-kion/internal/service/app_role"
	"terraform-provider-kion/internal/service/aws_account"
	"terraform-provider-kion/internal/service/aws_resource_tag"
	"terraform-provider-kion/internal/service/azure_account"
	"terraform-provider-kion/internal/service/azure_arm_template"
	"terraform-provider-kion/internal/service/azure_policy"
	"terraform-provider-kion/internal/service/azure_role"
	"terraform-provider-kion/internal/service/billing_rule"
	"terraform-provider-kion/internal/service/billing_source"
	"terraform-provider-kion/internal/service/billing_source_aws"
	"terraform-provider-kion/internal/service/billing_source_gcp"
	"terraform-provider-kion/internal/service/billing_source_govcloud"
	"terraform-provider-kion/internal/service/billing_source_oci"
	"terraform-provider-kion/internal/service/budget"
	"terraform-provider-kion/internal/service/category"
	"terraform-provider-kion/internal/service/cft"
	"terraform-provider-kion/internal/service/cloud_rule"
	"terraform-provider-kion/internal/service/compliance_check"
	"terraform-provider-kion/internal/service/compliance_control"
	"terraform-provider-kion/internal/service/compliance_family"
	"terraform-provider-kion/internal/service/compliance_level"
	"terraform-provider-kion/internal/service/compliance_program"
	"terraform-provider-kion/internal/service/compliance_standard"
	"terraform-provider-kion/internal/service/custom_account"
	"terraform-provider-kion/internal/service/custom_variable"
	"terraform-provider-kion/internal/service/custom_variable_override"
	"terraform-provider-kion/internal/service/dashboard"
	"terraform-provider-kion/internal/service/funding_source"
	"terraform-provider-kion/internal/service/funding_source_enforcement"
	"terraform-provider-kion/internal/service/funding_source_note"
	"terraform-provider-kion/internal/service/funding_source_permission_mapping"
	"terraform-provider-kion/internal/service/gcp_account"
	"terraform-provider-kion/internal/service/gcp_iam_role"
	"terraform-provider-kion/internal/service/gcp_regions"
	"terraform-provider-kion/internal/service/gcp_service_account"
	"terraform-provider-kion/internal/service/global_permission_mapping"
	"terraform-provider-kion/internal/service/iam_policy"
	"terraform-provider-kion/internal/service/idms"
	"terraform-provider-kion/internal/service/idms_group_association"
	"terraform-provider-kion/internal/service/idms_open_id"
	"terraform-provider-kion/internal/service/idms_open_id_access_rule"
	"terraform-provider-kion/internal/service/idms_open_id_group_association"
	"terraform-provider-kion/internal/service/label"
	"terraform-provider-kion/internal/service/ou"
	"terraform-provider-kion/internal/service/ou_cloud_access_role"
	"terraform-provider-kion/internal/service/ou_cloud_access_role_exemption"
	"terraform-provider-kion/internal/service/ou_enforcement"
	"terraform-provider-kion/internal/service/ou_note"
	"terraform-provider-kion/internal/service/ou_permission_mapping"
	"terraform-provider-kion/internal/service/permission_scheme"
	"terraform-provider-kion/internal/service/project"
	"terraform-provider-kion/internal/service/project_cloud_access_role"
	"terraform-provider-kion/internal/service/project_cloud_access_role_exemption"
	"terraform-provider-kion/internal/service/project_enforcement"
	"terraform-provider-kion/internal/service/project_line_item"
	"terraform-provider-kion/internal/service/project_note"
	"terraform-provider-kion/internal/service/project_permission_mapping"
	"terraform-provider-kion/internal/service/saml_group_association"
	"terraform-provider-kion/internal/service/scope"
	"terraform-provider-kion/internal/service/scope_criteria"
	"terraform-provider-kion/internal/service/service_catalog"
	"terraform-provider-kion/internal/service/service_control_policy"
	"terraform-provider-kion/internal/service/user"
	"terraform-provider-kion/internal/service/user_group"
	"terraform-provider-kion/internal/service/webhook"
)

// ServicePackages returns all registered service packages.
// This function is updated by kgen when scaffolding new resources.
func ServicePackages() []conns.ServicePackage {
	return []conns.ServicePackage{
		account.NewServicePackage(),
		account_cache.NewServicePackage(),
		account_linkage.NewServicePackage(),
		ami.NewServicePackage(),
		app_api_key.NewServicePackage(),
		app_config.NewServicePackage(),
		app_role.NewServicePackage(),
		aws_account.NewServicePackage(),
		aws_resource_tag.NewServicePackage(),
		azure_account.NewServicePackage(),
		azure_arm_template.NewServicePackage(),
		azure_policy.NewServicePackage(),
		azure_role.NewServicePackage(),
		billing_rule.NewServicePackage(),
		billing_source.NewServicePackage(),
		billing_source_aws.NewServicePackage(),
		billing_source_gcp.NewServicePackage(),
		billing_source_govcloud.NewServicePackage(),
		billing_source_oci.NewServicePackage(),
		budget.NewServicePackage(),
		category.NewServicePackage(),
		cft.NewServicePackage(),
		cloud_rule.NewServicePackage(),
		compliance_check.NewServicePackage(),
		compliance_control.NewServicePackage(),
		compliance_family.NewServicePackage(),
		compliance_level.NewServicePackage(),
		compliance_program.NewServicePackage(),
		compliance_standard.NewServicePackage(),
		custom_account.NewServicePackage(),
		custom_variable.NewServicePackage(),
		custom_variable_override.NewServicePackage(),
		dashboard.NewServicePackage(),
		funding_source.NewServicePackage(),
		funding_source_enforcement.NewServicePackage(),
		funding_source_note.NewServicePackage(),
		funding_source_permission_mapping.NewServicePackage(),
		gcp_account.NewServicePackage(),
		gcp_iam_role.NewServicePackage(),
		gcp_regions.NewServicePackage(),
		gcp_service_account.NewServicePackage(),
		global_permission_mapping.NewServicePackage(),
		iam_policy.NewServicePackage(),
		idms.NewServicePackage(),
		idms_group_association.NewServicePackage(),
		idms_open_id.NewServicePackage(),
		idms_open_id_access_rule.NewServicePackage(),
		idms_open_id_group_association.NewServicePackage(),
		label.NewServicePackage(),
		ou.NewServicePackage(),
		ou_cloud_access_role.NewServicePackage(),
		ou_cloud_access_role_exemption.NewServicePackage(),
		ou_enforcement.NewServicePackage(),
		ou_note.NewServicePackage(),
		ou_permission_mapping.NewServicePackage(),
		permission_scheme.NewServicePackage(),
		project.NewServicePackage(),
		project_cloud_access_role.NewServicePackage(),
		project_cloud_access_role_exemption.NewServicePackage(),
		project_enforcement.NewServicePackage(),
		project_line_item.NewServicePackage(),
		project_note.NewServicePackage(),
		project_permission_mapping.NewServicePackage(),
		saml_group_association.NewServicePackage(),
		scope.NewServicePackage(),
		scope_criteria.NewServicePackage(),
		service_catalog.NewServicePackage(),
		service_control_policy.NewServicePackage(),
		user.NewServicePackage(),
		user_group.NewServicePackage(),
		webhook.NewServicePackage(),
	}
}
