// Code generated by kgen crud. DO NOT EDIT.

// Package project_enforcement implements the Terraform resource for project_enforcement, a parent-scoped
// resource with no by-id read: every op takes the parent id, and the read lists
// the children under the parent and finds the one matching state.
package project_enforcement

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

const ResNameProjectEnforcement = "ProjectEnforcement Resource"

var (
	_ resource.Resource                = &project_enforcementResource{}
	_ resource.ResourceWithConfigure   = &project_enforcementResource{}
	_ resource.ResourceWithImportState = &project_enforcementResource{}
)

// NewProjectEnforcementResource returns a new instance of the resource.
func NewProjectEnforcementResource() resource.Resource {
	return &project_enforcementResource{}
}

type project_enforcementResource struct {
	framework.ResourceWithConfigure
}

func (r *project_enforcementResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_enforcement"
}

func (r *project_enforcementResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = ProjectEnforcementResourceSchema(ctx)
}

// findProjectEnforcementRecord returns the record with the given id from the parent list.
func findProjectEnforcementRecord(list []generated.ProjectEnforcement, id int64) (generated.ProjectEnforcement, bool) {
	for _, rec := range list {
		if rec.ID.Set && int64(rec.ID.Value) == id {
			return rec, true
		}
	}
	return generated.ProjectEnforcement{}, false
}

// listProjectEnforcement fetches the parent's child records.
func (r *project_enforcementResource) listProjectEnforcement(ctx context.Context, parentID int64) ([]generated.ProjectEnforcement, error) {
	out, err := r.Meta().Client.GetProjectEnforcements(ctx, generated.GetProjectEnforcementsParams{ID: parentID})
	if err != nil {
		return nil, err
	}
	resp, ok := out.(*generated.ProjectEnforcementResponse)
	if !ok {
		return nil, fmt.Errorf("unexpected response type %T", out)
	}
	return resp.Data, nil
}

func flattenProjectEnforcement(ctx context.Context, rec generated.ProjectEnforcement, model *ProjectEnforcementModel) {
	model.AmountType = flex.OptStringToFramework(rec.AmountType)
	model.Description = flex.OptStringToFramework(rec.Description)
	model.Enabled = flex.OptNilBoolToFramework(rec.Enabled)
	if rec.ID.Set {
		model.Id = types.StringValue(strconv.FormatUint(rec.ID.Value, 10))
	}
	model.NotificationFrequency = flex.OptStringToFramework(rec.NotificationFrequency)
	model.Overburn = flex.OptNilBoolToFramework(rec.Overburn)
	model.SpendOption = flex.OptStringToFramework(rec.SpendOption)
	model.Threshold = flex.OptInt64ToFramework(rec.Threshold)
	model.ThresholdType = flex.OptStringToFramework(rec.ThresholdType)
	model.Timeframe = flex.OptStringToFramework(rec.Timeframe)
	model.Triggered = flex.OptNilBoolToFramework(rec.Triggered)
	if rec.CloudRuleID.Set {
		model.CloudRuleId = types.Int64Value(int64(rec.CloudRuleID.Value.ID.Value))
	} else {
		model.CloudRuleId = types.Int64Null()
	}
	notificationEmails, _ := flex.StringSliceToFrameworkSet(ctx, rec.NotificationEmails.Value)
	model.NotificationEmails = notificationEmails
	userGroupIds, _ := flex.Uint64SliceToFrameworkSet(ctx, rec.UserGroupIds.Value)
	model.UserGroupIds = userGroupIds
	userIds, _ := flex.Uint64SliceToFrameworkSet(ctx, rec.UserIds.Value)
	model.UserIds = userIds
}

func (r *project_enforcementResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	conn := r.Meta().Client

	var plan ProjectEnforcementModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	parentID := plan.ProjectId.ValueInt64()

	notificationEmails, notificationEmailsDiags := flex.StringSliceFromFrameworkSet(ctx, plan.NotificationEmails)
	resp.Diagnostics.Append(notificationEmailsDiags...)
	userIds, userIdsDiags := flex.Uint64SliceFromFrameworkSet(ctx, plan.UserIds)
	resp.Diagnostics.Append(userIdsDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := generated.OptProjectEnforcementCreate{
		Value: generated.ProjectEnforcementCreate{
			AmountType:            flex.OptStringFromFramework(plan.AmountType),
			CloudRuleID:           flex.OptNilUint64FromFramework(plan.CloudRuleId),
			Description:           flex.OptStringFromFramework(plan.Description),
			NotificationFrequency: flex.OptStringFromFramework(plan.NotificationFrequency),
			Overburn:              flex.OptNilBoolFromFramework(plan.Overburn),
			ServiceID:             flex.OptNilUint64FromFramework(plan.ServiceId),
			SpendOption:           flex.OptStringFromFramework(plan.SpendOption),
			Threshold:             flex.Int64ValueFromFramework(plan.Threshold),
			ThresholdType:         flex.OptStringFromFramework(plan.ThresholdType),
			Timeframe:             flex.StringValueFromFramework(plan.Timeframe),
			NotificationEmails:    generated.OptNilStringArray{Value: notificationEmails, Set: true},
			UserIds:               generated.OptNilUint64Array{Value: userIds, Set: true},
		},
		Set: true,
	}

	out, err := conn.PostProjectEnforcement(ctx, input, generated.PostProjectEnforcementParams{ID: parentID})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameProjectEnforcement), err.Error())
		return
	}
	id, diags := errs.CreatedID(out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	plan.Id = types.StringValue(strconv.FormatInt(id, 10))

	list, err := r.listProjectEnforcement(ctx, parentID)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after creation (ID: %d)", ResNameProjectEnforcement, id), err.Error())
		return
	}
	rec, found := findProjectEnforcementRecord(list, id)
	if !found {
		resp.Diagnostics.AddError(fmt.Sprintf("creating %s", ResNameProjectEnforcement), "created record not present in the parent list")
		return
	}
	flattenProjectEnforcement(ctx, rec, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *project_enforcementResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ProjectEnforcementModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	list, err := r.listProjectEnforcement(ctx, state.ProjectId.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s (ID: %d)", ResNameProjectEnforcement, id), err.Error())
		return
	}
	rec, found := findProjectEnforcementRecord(list, id)
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	flattenProjectEnforcement(ctx, rec, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *project_enforcementResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	conn := r.Meta().Client

	var plan ProjectEnforcementModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	parentID := plan.ProjectId.ValueInt64()
	id, err := strconv.ParseInt(plan.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	notificationEmails, notificationEmailsDiags := flex.StringSliceFromFrameworkSet(ctx, plan.NotificationEmails)
	resp.Diagnostics.Append(notificationEmailsDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := generated.OptProjectEnforcementUpdate{
		Value: generated.ProjectEnforcementUpdate{
			AmountType:            flex.OptStringFromFramework(plan.AmountType),
			CloudRuleID:           flex.OptNilUint64FromFramework(plan.CloudRuleId),
			Description:           flex.OptStringFromFramework(plan.Description),
			Enabled:               flex.OptNilBoolFromFramework(plan.Enabled),
			NotificationFrequency: flex.OptStringFromFramework(plan.NotificationFrequency),
			Overburn:              flex.OptNilBoolFromFramework(plan.Overburn),
			ServiceID:             flex.OptNilUint64FromFramework(plan.ServiceId),
			SpendOption:           flex.OptStringFromFramework(plan.SpendOption),
			Threshold:             flex.OptInt64FromFramework(plan.Threshold),
			ThresholdType:         flex.OptStringFromFramework(plan.ThresholdType),
			Timeframe:             flex.OptStringFromFramework(plan.Timeframe),
			NotificationEmails:    generated.OptNilStringArray{Value: notificationEmails, Set: true},
		},
		Set: true,
	}

	out, err := conn.PatchProjectEnforcements(ctx, input, generated.PatchProjectEnforcementsParams{ID: parentID, EnforcementID: id})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("updating %s (ID: %d)", ResNameProjectEnforcement, id), err.Error())
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("updating %s", ResNameProjectEnforcement), out)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	list, err := r.listProjectEnforcement(ctx, parentID)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s after update (ID: %d)", ResNameProjectEnforcement, id), err.Error())
		return
	}
	rec, found := findProjectEnforcementRecord(list, id)
	if found {
		flattenProjectEnforcement(ctx, rec, &plan)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *project_enforcementResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	conn := r.Meta().Client

	var state ProjectEnforcementModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id, err := strconv.ParseInt(state.Id.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", err.Error())
		return
	}

	out, err := conn.DeleteProjectEnforcements(ctx, generated.DeleteProjectEnforcementsParams{ID: state.ProjectId.ValueInt64(), EnforcementID: id})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("deleting %s (ID: %d)", ResNameProjectEnforcement, id), err.Error())
		return
	}
	if errs.IsNotFound(out) {
		return
	}
	diags := errs.ResponseDiagnostics(fmt.Sprintf("deleting %s", ResNameProjectEnforcement), out)
	resp.Diagnostics.Append(diags...)
}

// ImportState takes "project_id/id" because Read lists the children under
// their parent: with only the child id, project_id stays zero and the read
// 404s. Importing a real install failed this way 187 times before the parent was
// part of the import id.
func (r *project_enforcementResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", `expected "project_id/id"`)
		return
	}
	parentID, perr := strconv.ParseInt(parts[0], 10, 64)
	if perr != nil {
		resp.Diagnostics.AddError("Invalid import ID", `expected "project_id/id" with an integer parent id`)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("project_id"), parentID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[1])...)
}
