// Code generated by kgen schemas. DO NOT EDIT.

package project_enforcement

import (
	"context"
	"testing"

	// Aliased to avoid collision with the acceptance-testing import
	// "github.com/hashicorp/terraform-plugin-testing/helper/resource".
	fwresource "github.com/hashicorp/terraform-plugin-framework/resource"
)

// TestProjectEnforcementResourceSchema validates the generated schema via ValidateImplementation.
func TestProjectEnforcementResourceSchema(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	schemaRequest := fwresource.SchemaRequest{}
	schemaResponse := &fwresource.SchemaResponse{}

	NewProjectEnforcementResource().Schema(ctx, schemaRequest, schemaResponse)

	if schemaResponse.Diagnostics.HasError() {
		t.Fatalf("Schema method diagnostics: %+v", schemaResponse.Diagnostics)
	}

	diagnostics := schemaResponse.Schema.ValidateImplementation(ctx)

	if diagnostics.HasError() {
		t.Fatalf("Schema validation diagnostics: %+v", diagnostics)
	}
}
