// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package gcp_regions

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GcpRegionsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"regions": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "List of google cloud region names.",
				MarkdownDescription: "List of google cloud region names.",
			},
		},
		Description: "Retrieves the Google Cloud regions known to Kion.",
	}
}

type GcpRegionsDataSourceModel struct {
	Regions types.List `tfsdk:"regions"`
}
