// Code generated by kgen crud. DO NOT EDIT.

package gcp_regions

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/flex"
	"terraform-provider-kion/internal/framework"
)

// DSNameGcpRegions is the display name used in diagnostics.
const DSNameGcpRegions = "GCP Regions Data Source"

// minKionVersion / maxKionVersion are declared in gcp_regions_version_gen.go,
// generated by `kgen versions` from the SDK's per-version clients.

var (
	_ datasource.DataSource              = &gcpRegionsDataSource{}
	_ datasource.DataSourceWithConfigure = &gcpRegionsDataSource{}
)

// NewGcpRegionsDataSource returns a new instance of the kion_gcp_regions data source.
func NewGcpRegionsDataSource() datasource.DataSource {
	return &gcpRegionsDataSource{}
}

type gcpRegionsDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *gcpRegionsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gcp_regions"
}

func (d *gcpRegionsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	// Schema generated from the Kion OpenAPI spec (gcp_regions_data_source_schema_gen.go, DO NOT EDIT).
	resp.Schema = GcpRegionsDataSourceSchema(ctx)
}

func (d *gcpRegionsDataSource) Read(ctx context.Context, _ datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.Append(framework.RequireKionVersionInRange(d.Meta(), minKionVersion, maxKionVersion, "kion_gcp_regions")...)
	if resp.Diagnostics.HasError() {
		return
	}

	conn := d.Meta().Client
	out, err := conn.GetGCPRegionsList(ctx)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameGcpRegions), err.Error())
		return
	}
	api, ok := out.(*generated.ListGCPRegionsResponse)
	if !ok {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("reading "+DSNameGcpRegions, out)...)
		return
	}

	regions, listDiags := flex.StringSliceToFramework(ctx, api.Data)
	resp.Diagnostics.Append(listDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	model := GcpRegionsDataSourceModel{Regions: regions}
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}
