# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_project_cloud_access_role_exemption" "this" {
  ou_cloud_access_role_id = var.ou_cloud_access_role_id
  project_id              = var.project_id
  reason                  = var.reason
}
