# Generated by `kgen module` from the provider schema. Do not edit.

resource "kion_custom_account" "this" {
  account_alias  = var.account_alias
  account_name   = var.account_name
  account_number = var.account_number
  payer_id       = var.payer_id
  project_id     = var.project_id
  start_datecode = var.start_datecode
}
