# Generated by `kgen module` from the provider schema. Do not edit.

output "id" {
  description = "id of the kion_ou_enforcement."
  value       = kion_ou_enforcement.this.id
}

output "triggered" {
  description = "triggered of the kion_ou_enforcement."
  value       = kion_ou_enforcement.this.triggered
}
