// Code generated by kgen migrate. DO NOT EDIT.

package compliance_standard

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"terraform-provider-kion/internal/migratehelper"
)

var _ resource.ResourceWithUpgradeState = &compliance_standardResource{}

// UpgradeState migrates v0 (SDKv2 provider) state to the current schema by
// transforming the raw old-state JSON map and decoding it against the current
// schema. A shape that no longer fits (an object whose fields changed, etc.)
// fails in ValueFromJSON rather than silently.
func (r *compliance_standardResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	return map[int64]resource.StateUpgrader{
		0: {
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				var old map[string]json.RawMessage
				if err := json.Unmarshal(req.RawState.JSON, &old); err != nil {
					resp.Diagnostics.AddError("upgrading compliance_standard state", err.Error())
					return
				}
				nw := map[string]json.RawMessage{
					"cloud_rule_id":        migratehelper.Null,
					"compliance_check_ids": migratehelper.ProjectIDs(old["compliance_checks"], "id"),
					"created_at":           migratehelper.OrNull(old["created_at"]),
					"created_by_user_id":   migratehelper.OrNull(old["created_by_user_id"]),
					"ct_managed":           migratehelper.OrNull(old["ct_managed"]),
					"description":          migratehelper.OrNull(old["description"]),
					"id":                   migratehelper.OrNull(old["id"]),
					"last_updated":         migratehelper.OrNull(old["last_updated"]),
					"name":                 migratehelper.OrNull(old["name"]),
					"owner_user_group_ids": migratehelper.ProjectIDs(old["owner_user_groups"], "id"),
					"owner_user_ids":       migratehelper.ProjectIDs(old["owner_users"], "id"),
				}
				b, err := json.Marshal(nw)
				if err != nil {
					resp.Diagnostics.AddError("upgrading compliance_standard state", err.Error())
					return
				}
				val, err := tftypes.ValueFromJSON(b, resp.State.Schema.Type().TerraformType(ctx))
				if err != nil {
					resp.Diagnostics.AddError("upgrading compliance_standard state", err.Error())
					return
				}
				resp.State = tfsdk.State{Raw: val, Schema: resp.State.Schema}
			},
		},
	}
}
