// Code generated by kgen crud. DO NOT EDIT.

package compliance_standard_test

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"terraform-provider-kion/internal/acctest"
	"terraform-provider-kion/internal/errs"

	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"
)

func TestAccKionComplianceStandard_basic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_compliance_standard.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckComplianceStandardDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccComplianceStandardConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckComplianceStandardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "created_by_user_id", "1"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc compliance standard"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccKionComplianceStandard_update(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping long-running test in short mode")
	}

	ctx := acctest.Context(t)
	rName := acctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "kion_compliance_standard.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.PreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckComplianceStandardDestroy(ctx),
		Steps: []resource.TestStep{
			{
				Config: testAccComplianceStandardConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckComplianceStandardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "created_by_user_id", "1"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc compliance standard"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
				),
			},
			{
				Config: testAccComplianceStandardConfig_update(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					testAccCheckComplianceStandardExists(ctx, resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttr(resourceName, "created_by_user_id", "1"),
					resource.TestCheckResourceAttr(resourceName, "description", "test-acc compliance standard updated"),
					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf("%[1]s", rName)),
					resource.TestCheckResourceAttrSet(resourceName, "owner_user_ids"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckComplianceStandardExists(_ context.Context, name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			return fmt.Errorf("not found: %s", name)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for %s", name)
		}

		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
		if err != nil {
			return fmt.Errorf("parsing ID: %w", err)
		}

		ctx := context.Background()
		out, err := conn.Client.GetComplianceStandard(ctx, generated.GetComplianceStandardParams{ID: id})
		if err != nil {
			return fmt.Errorf("reading kion_compliance_standard (%d): %w", id, err)
		}
		if errs.IsNotFound(out) {
			return fmt.Errorf("kion_compliance_standard (%d) not found", id)
		}

		return nil
	}
}

func testAccCheckComplianceStandardDestroy(_ context.Context) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		conn, err := acctest.SharedClient()
		if err != nil {
			return fmt.Errorf("getting shared client: %w", err)
		}

		for _, rs := range s.RootModule().Resources {
			if rs.Type != "kion_compliance_standard" {
				continue
			}

			id, err := strconv.ParseInt(rs.Primary.ID, 10, 64)
			if err != nil {
				return fmt.Errorf("parsing ID: %w", err)
			}

			ctx := context.Background()
			out, err := conn.Client.GetComplianceStandard(ctx, generated.GetComplianceStandardParams{ID: id})
			if errs.IsNotFound(out) {
				continue
			}
			if err != nil {
				return fmt.Errorf("reading kion_compliance_standard (%d): %w", id, err)
			}

			return fmt.Errorf("kion_compliance_standard (%d) still exists", id)
		}

		return nil
	}
}

func testAccComplianceStandardConfig_basic(rName string) string {
	return fmt.Sprintf(`
resource "kion_compliance_standard" "test" {
  created_by_user_id = 1
  description = "test-acc compliance standard"
  name = "%[1]s"
  owner_user_ids = [1]
}
`, rName)
}

func testAccComplianceStandardConfig_update(rName string) string {
	return fmt.Sprintf(`
resource "kion_compliance_standard" "test" {
  created_by_user_id = 1
  description = "test-acc compliance standard updated"
  name = "%[1]s"
  owner_user_ids = [1]
}
`, rName)
}
