// Code generated by kgen crud. DO NOT EDIT.

package compliance_standard

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/kionsoftware/kion-sdk-go/generated/v3_16"

	"terraform-provider-kion/internal/errs"
	"terraform-provider-kion/internal/framework"
)

const DSNameComplianceStandard = "ComplianceStandard Data Source"

var (
	_ datasource.DataSource              = &compliance_standardDataSource{}
	_ datasource.DataSourceWithConfigure = &compliance_standardDataSource{}
)

// NewComplianceStandardDataSource returns a new instance of the data source.
func NewComplianceStandardDataSource() datasource.DataSource {
	return &compliance_standardDataSource{}
}

type compliance_standardDataSource struct {
	framework.DataSourceWithConfigure
}

func (d *compliance_standardDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compliance_standard"
}

func (d *compliance_standardDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Use this data source to look up a Kion ComplianceStandard by id.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "The ID of the ComplianceStandard to fetch.",
				Required:    true,
			},
		},
	}
}

func (d *compliance_standardDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	conn := d.Meta().Client

	var data compliance_standardDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := conn.GetComplianceStandard(ctx, generated.GetComplianceStandardParams{ID: data.Id.ValueInt64()})
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameComplianceStandard), err.Error())
		return
	}

	if errs.IsNotFound(out) {
		resp.Diagnostics.AddError(fmt.Sprintf("reading %s", DSNameComplianceStandard), "compliance_standard not found")
		return
	}

	api, ok := out.(*generated.ComplianceStandardResponse)
	if !ok || !api.Data.Set {
		resp.Diagnostics.Append(errs.ResponseDiagnostics("reading "+DSNameComplianceStandard, out)...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type compliance_standardDataSourceModel struct {
	Id types.Int64 `tfsdk:"id"`
}
